// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __AdvApprox_wrapper__
#define __AdvApprox_wrapper__

#include "/Library/OCE/0.14/include/oce/AdvApprox_ApproxAFunction.hxx"
#include "/Library/OCE/0.14/include/oce/AdvApprox_Cutting.hxx"
#include "/Library/OCE/0.14/include/oce/AdvApprox_DichoCutting.hxx"
#include "/Library/OCE/0.14/include/oce/AdvApprox_EvaluatorFunction.hxx"
#include "/Library/OCE/0.14/include/oce/AdvApprox_PrefAndRec.hxx"
#include "/Library/OCE/0.14/include/oce/AdvApprox_PrefCutting.hxx"
#include "/Library/OCE/0.14/include/oce/AdvApprox_SimpleApprox.hxx"

#endif __AdvApprox_wrapper__
