// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __AppBlend_wrapper__
#define __AppBlend_wrapper__

#include "/Library/OCE/0.14/include/oce/AppBlend_Approx.hxx"

#endif __AppBlend_wrapper__
