// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __ApproxInt_wrapper__
#define __ApproxInt_wrapper__

#include "/Library/OCE/0.14/include/oce/ApproxInt_SvSurfaces.hxx"

#endif __ApproxInt_wrapper__
