// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __Approx_wrapper__
#define __Approx_wrapper__

#include "/Library/OCE/0.14/include/oce/Approx_Array1OfAdHSurface.hxx"
#include "/Library/OCE/0.14/include/oce/Approx_Array1OfGTrsf2d.hxx"
#include "/Library/OCE/0.14/include/oce/Approx_Curve2d.hxx"
#include "/Library/OCE/0.14/include/oce/Approx_Curve3d.hxx"
#include "/Library/OCE/0.14/include/oce/Approx_CurveOnSurface.hxx"
#include "/Library/OCE/0.14/include/oce/Approx_CurvilinearParameter.hxx"
#include "/Library/OCE/0.14/include/oce/Approx_CurvlinFunc.hxx"
#include "/Library/OCE/0.14/include/oce/Approx_FitAndDivide.hxx"
#include "/Library/OCE/0.14/include/oce/Approx_FitAndDivide2d.hxx"
#include "/Library/OCE/0.14/include/oce/Approx_HArray1OfAdHSurface.hxx"
#include "/Library/OCE/0.14/include/oce/Approx_HArray1OfGTrsf2d.hxx"
#include "/Library/OCE/0.14/include/oce/Approx_MCurvesToBSpCurve.hxx"
#include "/Library/OCE/0.14/include/oce/Approx_MyLeastSquareOfFitAndDivide.hxx"
#include "/Library/OCE/0.14/include/oce/Approx_MyLeastSquareOfFitAndDivide2d.hxx"
#include "/Library/OCE/0.14/include/oce/Approx_ParametrizationType.hxx"
#include "/Library/OCE/0.14/include/oce/Approx_SameParameter.hxx"
#include "/Library/OCE/0.14/include/oce/Approx_SequenceNodeOfSequenceOfHArray1OfReal.hxx"
#include "/Library/OCE/0.14/include/oce/Approx_SequenceOfHArray1OfReal.hxx"
#include "/Library/OCE/0.14/include/oce/Approx_Status.hxx"
#include "/Library/OCE/0.14/include/oce/Approx_SweepApproximation.hxx"
#include "/Library/OCE/0.14/include/oce/Approx_SweepFunction.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Approx_CurvlinFunc.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Approx_HArray1OfAdHSurface.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Approx_HArray1OfGTrsf2d.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Approx_SequenceNodeOfSequenceOfHArray1OfReal.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Approx_SweepFunction.hxx"

#endif __Approx_wrapper__
