// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __AppStdL_wrapper__
#define __AppStdL_wrapper__

#include "/Library/OCE/0.14/include/oce/AppStdL_Application.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_AppStdL_Application.hxx"

#endif __AppStdL_wrapper__
