// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __BinMFunction_wrapper__
#define __BinMFunction_wrapper__

#include "/Library/OCE/0.14/include/oce/BinMFunction.hxx"
#include "/Library/OCE/0.14/include/oce/BinMFunction_FunctionDriver.hxx"
#include "/Library/OCE/0.14/include/oce/BinMFunction_GraphNodeDriver.hxx"
#include "/Library/OCE/0.14/include/oce/BinMFunction_ScopeDriver.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BinMFunction_FunctionDriver.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BinMFunction_GraphNodeDriver.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BinMFunction_ScopeDriver.hxx"

#endif __BinMFunction_wrapper__
