// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __BinMDocStd_wrapper__
#define __BinMDocStd_wrapper__

#include "/Library/OCE/0.14/include/oce/BinMDocStd.hxx"
#include "/Library/OCE/0.14/include/oce/BinMDocStd_XLinkDriver.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BinMDocStd_XLinkDriver.hxx"

#endif __BinMDocStd_wrapper__
