// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __BinMNaming_wrapper__
#define __BinMNaming_wrapper__

#include "/Library/OCE/0.14/include/oce/BinMNaming.hxx"
#include "/Library/OCE/0.14/include/oce/BinMNaming_NamedShapeDriver.hxx"
#include "/Library/OCE/0.14/include/oce/BinMNaming_NamingDriver.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BinMNaming_NamedShapeDriver.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BinMNaming_NamingDriver.hxx"

#endif __BinMNaming_wrapper__
