// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __BinMPrsStd_wrapper__
#define __BinMPrsStd_wrapper__

#include "/Library/OCE/0.14/include/oce/BinMPrsStd.hxx"
#include "/Library/OCE/0.14/include/oce/BinMPrsStd_AISPresentationDriver.hxx"
#include "/Library/OCE/0.14/include/oce/BinMPrsStd_PositionDriver.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BinMPrsStd_AISPresentationDriver.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BinMPrsStd_PositionDriver.hxx"

#endif __BinMPrsStd_wrapper__
