// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __BinXCAFDrivers_wrapper__
#define __BinXCAFDrivers_wrapper__

#include "/Library/OCE/0.14/include/oce/BinXCAFDrivers.hxx"
#include "/Library/OCE/0.14/include/oce/BinXCAFDrivers_DocumentRetrievalDriver.hxx"
#include "/Library/OCE/0.14/include/oce/BinXCAFDrivers_DocumentStorageDriver.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BinXCAFDrivers_DocumentRetrievalDriver.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BinXCAFDrivers_DocumentStorageDriver.hxx"

#endif __BinXCAFDrivers_wrapper__
