// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __Bisector_wrapper__
#define __Bisector_wrapper__

#include "/Library/OCE/0.14/include/oce/Bisector.hxx"
#include "/Library/OCE/0.14/include/oce/Bisector_Bisec.hxx"
#include "/Library/OCE/0.14/include/oce/Bisector_BisecAna.hxx"
#include "/Library/OCE/0.14/include/oce/Bisector_BisecCC.hxx"
#include "/Library/OCE/0.14/include/oce/Bisector_BisecPC.hxx"
#include "/Library/OCE/0.14/include/oce/Bisector_Curve.hxx"
#include "/Library/OCE/0.14/include/oce/Bisector_FunctionH.hxx"
#include "/Library/OCE/0.14/include/oce/Bisector_FunctionInter.hxx"
#include "/Library/OCE/0.14/include/oce/Bisector_Inter.hxx"
#include "/Library/OCE/0.14/include/oce/Bisector_PointOnBis.hxx"
#include "/Library/OCE/0.14/include/oce/Bisector_PolyBis.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Bisector_BisecAna.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Bisector_BisecCC.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Bisector_BisecPC.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Bisector_Curve.hxx"

#endif __Bisector_wrapper__
