// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __BiTgte_wrapper__
#define __BiTgte_wrapper__

#include "/Library/OCE/0.14/include/oce/BiTgte_Blend.hxx"
#include "/Library/OCE/0.14/include/oce/BiTgte_ContactType.hxx"
#include "/Library/OCE/0.14/include/oce/BiTgte_CurveOnEdge.hxx"
#include "/Library/OCE/0.14/include/oce/BiTgte_CurveOnVertex.hxx"
#include "/Library/OCE/0.14/include/oce/BiTgte_DataMapIteratorOfDataMapOfShapeBox.hxx"
#include "/Library/OCE/0.14/include/oce/BiTgte_DataMapNodeOfDataMapOfShapeBox.hxx"
#include "/Library/OCE/0.14/include/oce/BiTgte_DataMapOfShapeBox.hxx"
#include "/Library/OCE/0.14/include/oce/BiTgte_HCurveOnEdge.hxx"
#include "/Library/OCE/0.14/include/oce/BiTgte_HCurveOnVertex.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BiTgte_DataMapNodeOfDataMapOfShapeBox.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BiTgte_HCurveOnEdge.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BiTgte_HCurveOnVertex.hxx"

#endif __BiTgte_wrapper__
