// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __BlendFunc_wrapper__
#define __BlendFunc_wrapper__

#include "/Library/OCE/0.14/include/oce/BlendFunc.hxx"
#include "/Library/OCE/0.14/include/oce/BlendFunc_CSCircular.hxx"
#include "/Library/OCE/0.14/include/oce/BlendFunc_CSConstRad.hxx"
#include "/Library/OCE/0.14/include/oce/BlendFunc_ChAsym.hxx"
#include "/Library/OCE/0.14/include/oce/BlendFunc_ChAsymInv.hxx"
#include "/Library/OCE/0.14/include/oce/BlendFunc_ChamfInv.hxx"
#include "/Library/OCE/0.14/include/oce/BlendFunc_Chamfer.hxx"
#include "/Library/OCE/0.14/include/oce/BlendFunc_ConstRad.hxx"
#include "/Library/OCE/0.14/include/oce/BlendFunc_ConstRadInv.hxx"
#include "/Library/OCE/0.14/include/oce/BlendFunc_Corde.hxx"
#include "/Library/OCE/0.14/include/oce/BlendFunc_EvolRad.hxx"
#include "/Library/OCE/0.14/include/oce/BlendFunc_EvolRadInv.hxx"
#include "/Library/OCE/0.14/include/oce/BlendFunc_Ruled.hxx"
#include "/Library/OCE/0.14/include/oce/BlendFunc_RuledInv.hxx"
#include "/Library/OCE/0.14/include/oce/BlendFunc_SectionShape.hxx"
#include "/Library/OCE/0.14/include/oce/BlendFunc_Tensor.hxx"

#endif __BlendFunc_wrapper__
