// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __BndLib_wrapper__
#define __BndLib_wrapper__

#include "/Library/OCE/0.14/include/oce/BndLib.hxx"
#include "/Library/OCE/0.14/include/oce/BndLib_Add2dCurve.hxx"
#include "/Library/OCE/0.14/include/oce/BndLib_Add3dCurve.hxx"
#include "/Library/OCE/0.14/include/oce/BndLib_AddSurface.hxx"

#endif __BndLib_wrapper__
