// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __BOPAlgo_wrapper__
#define __BOPAlgo_wrapper__

#include "/Library/OCE/0.14/include/oce/BOPAlgo_Algo.hxx"
#include "/Library/OCE/0.14/include/oce/BOPAlgo_ArgumentAnalyzer.hxx"
#include "/Library/OCE/0.14/include/oce/BOPAlgo_BOP.hxx"
#include "/Library/OCE/0.14/include/oce/BOPAlgo_Builder.hxx"
#include "/Library/OCE/0.14/include/oce/BOPAlgo_BuilderArea.hxx"
#include "/Library/OCE/0.14/include/oce/BOPAlgo_BuilderFace.hxx"
#include "/Library/OCE/0.14/include/oce/BOPAlgo_BuilderShape.hxx"
#include "/Library/OCE/0.14/include/oce/BOPAlgo_BuilderSolid.hxx"
#include "/Library/OCE/0.14/include/oce/BOPAlgo_CheckResult.hxx"
#include "/Library/OCE/0.14/include/oce/BOPAlgo_CheckStatus.hxx"
#include "/Library/OCE/0.14/include/oce/BOPAlgo_CheckerSI.hxx"
#include "/Library/OCE/0.14/include/oce/BOPAlgo_ListOfCheckResult.hxx"
#include "/Library/OCE/0.14/include/oce/BOPAlgo_Operation.hxx"
#include "/Library/OCE/0.14/include/oce/BOPAlgo_PArgumentAnalyzer.hxx"
#include "/Library/OCE/0.14/include/oce/BOPAlgo_PBOP.hxx"
#include "/Library/OCE/0.14/include/oce/BOPAlgo_PBuilder.hxx"
#include "/Library/OCE/0.14/include/oce/BOPAlgo_PPaveFiller.hxx"
#include "/Library/OCE/0.14/include/oce/BOPAlgo_PWireEdgeSet.hxx"
#include "/Library/OCE/0.14/include/oce/BOPAlgo_PaveFiller.hxx"
#include "/Library/OCE/0.14/include/oce/BOPAlgo_SectionAttribute.hxx"
#include "/Library/OCE/0.14/include/oce/BOPAlgo_Tools.hxx"
#include "/Library/OCE/0.14/include/oce/BOPAlgo_WireEdgeSet.hxx"
#include "/Library/OCE/0.14/include/oce/BOPAlgo_WireSplitter.hxx"

#endif __BOPAlgo_wrapper__
