// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __BOPTools_wrapper__
#define __BOPTools_wrapper__

#include "/Library/OCE/0.14/include/oce/BOPTools.hxx"
#include "/Library/OCE/0.14/include/oce/BOPTools_AlgoTools.hxx"
#include "/Library/OCE/0.14/include/oce/BOPTools_AlgoTools2D.hxx"
#include "/Library/OCE/0.14/include/oce/BOPTools_AlgoTools3D.hxx"
#include "/Library/OCE/0.14/include/oce/BOPTools_ConnexityBlock.hxx"
#include "/Library/OCE/0.14/include/oce/BOPTools_CoupleOfShape.hxx"
#include "/Library/OCE/0.14/include/oce/BOPTools_DataMapOfShapeSet.hxx"
#include "/Library/OCE/0.14/include/oce/BOPTools_EdgeSet.hxx"
#include "/Library/OCE/0.14/include/oce/BOPTools_ListOfConnexityBlock.hxx"
#include "/Library/OCE/0.14/include/oce/BOPTools_ListOfCoupleOfShape.hxx"
#include "/Library/OCE/0.14/include/oce/BOPTools_ListOfEdgeSet.hxx"
#include "/Library/OCE/0.14/include/oce/BOPTools_ListOfShapeSet.hxx"
#include "/Library/OCE/0.14/include/oce/BOPTools_MapOfSet.hxx"
#include "/Library/OCE/0.14/include/oce/BOPTools_Set.hxx"
#include "/Library/OCE/0.14/include/oce/BOPTools_SetMapHasher.hxx"
#include "/Library/OCE/0.14/include/oce/BOPTools_ShapeSet.hxx"

#endif __BOPTools_wrapper__
