// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __BRepPrim_wrapper__
#define __BRepPrim_wrapper__

#include "/Library/OCE/0.14/include/oce/BRepPrim_Builder.hxx"
#include "/Library/OCE/0.14/include/oce/BRepPrim_Cone.hxx"
#include "/Library/OCE/0.14/include/oce/BRepPrim_Cylinder.hxx"
#include "/Library/OCE/0.14/include/oce/BRepPrim_FaceBuilder.hxx"
#include "/Library/OCE/0.14/include/oce/BRepPrim_GWedge.hxx"
#include "/Library/OCE/0.14/include/oce/BRepPrim_OneAxis.hxx"
#include "/Library/OCE/0.14/include/oce/BRepPrim_Revolution.hxx"
#include "/Library/OCE/0.14/include/oce/BRepPrim_Sphere.hxx"
#include "/Library/OCE/0.14/include/oce/BRepPrim_Torus.hxx"
#include "/Library/OCE/0.14/include/oce/BRepPrim_Wedge.hxx"

#endif __BRepPrim_wrapper__
