// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __BRepAdaptor_wrapper__
#define __BRepAdaptor_wrapper__

#include "/Library/OCE/0.14/include/oce/BRepAdaptor_Array1OfCurve.hxx"
#include "/Library/OCE/0.14/include/oce/BRepAdaptor_CompCurve.hxx"
#include "/Library/OCE/0.14/include/oce/BRepAdaptor_Curve.hxx"
#include "/Library/OCE/0.14/include/oce/BRepAdaptor_Curve2d.hxx"
#include "/Library/OCE/0.14/include/oce/BRepAdaptor_HArray1OfCurve.hxx"
#include "/Library/OCE/0.14/include/oce/BRepAdaptor_HCompCurve.hxx"
#include "/Library/OCE/0.14/include/oce/BRepAdaptor_HCurve.hxx"
#include "/Library/OCE/0.14/include/oce/BRepAdaptor_HCurve2d.hxx"
#include "/Library/OCE/0.14/include/oce/BRepAdaptor_HSurface.hxx"
#include "/Library/OCE/0.14/include/oce/BRepAdaptor_Surface.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BRepAdaptor_HArray1OfCurve.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BRepAdaptor_HCompCurve.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BRepAdaptor_HCurve.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BRepAdaptor_HCurve2d.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BRepAdaptor_HSurface.hxx"

#endif __BRepAdaptor_wrapper__
