// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __BRepClass3d_wrapper__
#define __BRepClass3d_wrapper__

#include "/Library/OCE/0.14/include/oce/BRepClass3d.hxx"
#include "/Library/OCE/0.14/include/oce/BRepClass3d_DataMapIteratorOfMapOfInter.hxx"
#include "/Library/OCE/0.14/include/oce/BRepClass3d_DataMapNodeOfMapOfInter.hxx"
#include "/Library/OCE/0.14/include/oce/BRepClass3d_Intersector3d.hxx"
#include "/Library/OCE/0.14/include/oce/BRepClass3d_MapOfInter.hxx"
#include "/Library/OCE/0.14/include/oce/BRepClass3d_SClassifier.hxx"
#include "/Library/OCE/0.14/include/oce/BRepClass3d_SolidClassifier.hxx"
#include "/Library/OCE/0.14/include/oce/BRepClass3d_SolidExplorer.hxx"
#include "/Library/OCE/0.14/include/oce/BRepClass3d_SolidPassiveClassifier.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BRepClass3d_DataMapNodeOfMapOfInter.hxx"

#endif __BRepClass3d_wrapper__
