// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __BRepLProp_wrapper__
#define __BRepLProp_wrapper__

#include "/Library/OCE/0.14/include/oce/BRepLProp.hxx"
#include "/Library/OCE/0.14/include/oce/BRepLProp_CLProps.hxx"
#include "/Library/OCE/0.14/include/oce/BRepLProp_CurveTool.hxx"
#include "/Library/OCE/0.14/include/oce/BRepLProp_SLProps.hxx"
#include "/Library/OCE/0.14/include/oce/BRepLProp_SurfaceTool.hxx"

#endif __BRepLProp_wrapper__
