// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __BRepToIGES_wrapper__
#define __BRepToIGES_wrapper__

#include "/Library/OCE/0.14/include/oce/BRepToIGES_BREntity.hxx"
#include "/Library/OCE/0.14/include/oce/BRepToIGES_BRShell.hxx"
#include "/Library/OCE/0.14/include/oce/BRepToIGES_BRSolid.hxx"
#include "/Library/OCE/0.14/include/oce/BRepToIGES_BRWire.hxx"

#endif __BRepToIGES_wrapper__
