// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __BRepTools_wrapper__
#define __BRepTools_wrapper__

#include "/Library/OCE/0.14/include/oce/BRepTools.hxx"
#include "/Library/OCE/0.14/include/oce/BRepTools_DataMapIteratorOfMapOfVertexPnt2d.hxx"
#include "/Library/OCE/0.14/include/oce/BRepTools_DataMapNodeOfMapOfVertexPnt2d.hxx"
#include "/Library/OCE/0.14/include/oce/BRepTools_GTrsfModification.hxx"
#include "/Library/OCE/0.14/include/oce/BRepTools_MapOfVertexPnt2d.hxx"
#include "/Library/OCE/0.14/include/oce/BRepTools_Modification.hxx"
#include "/Library/OCE/0.14/include/oce/BRepTools_Modifier.hxx"
#include "/Library/OCE/0.14/include/oce/BRepTools_NurbsConvertModification.hxx"
#include "/Library/OCE/0.14/include/oce/BRepTools_Quilt.hxx"
#include "/Library/OCE/0.14/include/oce/BRepTools_ReShape.hxx"
#include "/Library/OCE/0.14/include/oce/BRepTools_ShapeSet.hxx"
#include "/Library/OCE/0.14/include/oce/BRepTools_Substitution.hxx"
#include "/Library/OCE/0.14/include/oce/BRepTools_TrsfModification.hxx"
#include "/Library/OCE/0.14/include/oce/BRepTools_WireExplorer.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BRepTools_DataMapNodeOfMapOfVertexPnt2d.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BRepTools_GTrsfModification.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BRepTools_Modification.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BRepTools_NurbsConvertModification.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BRepTools_ReShape.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BRepTools_TrsfModification.hxx"

#endif __BRepTools_wrapper__
