// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __BRepIntCurveSurface_wrapper__
#define __BRepIntCurveSurface_wrapper__

#include "/Library/OCE/0.14/include/oce/BRepIntCurveSurface_Inter.hxx"

#endif __BRepIntCurveSurface_wrapper__
