// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __BRepOffsetAPI_wrapper__
#define __BRepOffsetAPI_wrapper__

#include "/Library/OCE/0.14/include/oce/BRepOffsetAPI_DraftAngle.hxx"
#include "/Library/OCE/0.14/include/oce/BRepOffsetAPI_FindContigousEdges.hxx"
#include "/Library/OCE/0.14/include/oce/BRepOffsetAPI_MakeDraft.hxx"
#include "/Library/OCE/0.14/include/oce/BRepOffsetAPI_MakeEvolved.hxx"
#include "/Library/OCE/0.14/include/oce/BRepOffsetAPI_MakeFilling.hxx"
#include "/Library/OCE/0.14/include/oce/BRepOffsetAPI_MakeOffset.hxx"
#include "/Library/OCE/0.14/include/oce/BRepOffsetAPI_MakeOffsetShape.hxx"
#include "/Library/OCE/0.14/include/oce/BRepOffsetAPI_MakePipe.hxx"
#include "/Library/OCE/0.14/include/oce/BRepOffsetAPI_MakePipeShell.hxx"
#include "/Library/OCE/0.14/include/oce/BRepOffsetAPI_MakeThickSolid.hxx"
#include "/Library/OCE/0.14/include/oce/BRepOffsetAPI_MiddlePath.hxx"
#include "/Library/OCE/0.14/include/oce/BRepOffsetAPI_NormalProjection.hxx"
#include "/Library/OCE/0.14/include/oce/BRepOffsetAPI_SequenceNodeOfSequenceOfSequenceOfReal.hxx"
#include "/Library/OCE/0.14/include/oce/BRepOffsetAPI_SequenceNodeOfSequenceOfSequenceOfShape.hxx"
#include "/Library/OCE/0.14/include/oce/BRepOffsetAPI_SequenceOfSequenceOfReal.hxx"
#include "/Library/OCE/0.14/include/oce/BRepOffsetAPI_SequenceOfSequenceOfShape.hxx"
#include "/Library/OCE/0.14/include/oce/BRepOffsetAPI_Sewing.hxx"
#include "/Library/OCE/0.14/include/oce/BRepOffsetAPI_ThruSections.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BRepOffsetAPI_SequenceNodeOfSequenceOfSequenceOfReal.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BRepOffsetAPI_SequenceNodeOfSequenceOfSequenceOfShape.hxx"

#endif __BRepOffsetAPI_wrapper__
