// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __BRepClass_wrapper__
#define __BRepClass_wrapper__

#include "/Library/OCE/0.14/include/oce/BRepClass_Edge.hxx"
#include "/Library/OCE/0.14/include/oce/BRepClass_FClass2dOfFClassifier.hxx"
#include "/Library/OCE/0.14/include/oce/BRepClass_FClassifier.hxx"
#include "/Library/OCE/0.14/include/oce/BRepClass_FaceClassifier.hxx"
#include "/Library/OCE/0.14/include/oce/BRepClass_FaceExplorer.hxx"
#include "/Library/OCE/0.14/include/oce/BRepClass_FacePassiveClassifier.hxx"
#include "/Library/OCE/0.14/include/oce/BRepClass_Intersector.hxx"

#endif __BRepClass_wrapper__
