// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __BRepCheck_wrapper__
#define __BRepCheck_wrapper__

#include "/Library/OCE/0.14/include/oce/BRepCheck.hxx"
#include "/Library/OCE/0.14/include/oce/BRepCheck_Analyzer.hxx"
#include "/Library/OCE/0.14/include/oce/BRepCheck_DataMapIteratorOfDataMapOfShapeListOfStatus.hxx"
#include "/Library/OCE/0.14/include/oce/BRepCheck_DataMapIteratorOfDataMapOfShapeResult.hxx"
#include "/Library/OCE/0.14/include/oce/BRepCheck_DataMapNodeOfDataMapOfShapeListOfStatus.hxx"
#include "/Library/OCE/0.14/include/oce/BRepCheck_DataMapNodeOfDataMapOfShapeResult.hxx"
#include "/Library/OCE/0.14/include/oce/BRepCheck_DataMapOfShapeListOfStatus.hxx"
#include "/Library/OCE/0.14/include/oce/BRepCheck_DataMapOfShapeResult.hxx"
#include "/Library/OCE/0.14/include/oce/BRepCheck_Edge.hxx"
#include "/Library/OCE/0.14/include/oce/BRepCheck_Face.hxx"
#include "/Library/OCE/0.14/include/oce/BRepCheck_ListIteratorOfListOfStatus.hxx"
#include "/Library/OCE/0.14/include/oce/BRepCheck_ListNodeOfListOfStatus.hxx"
#include "/Library/OCE/0.14/include/oce/BRepCheck_ListOfStatus.hxx"
#include "/Library/OCE/0.14/include/oce/BRepCheck_Result.hxx"
#include "/Library/OCE/0.14/include/oce/BRepCheck_Shell.hxx"
#include "/Library/OCE/0.14/include/oce/BRepCheck_Status.hxx"
#include "/Library/OCE/0.14/include/oce/BRepCheck_Vertex.hxx"
#include "/Library/OCE/0.14/include/oce/BRepCheck_Wire.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BRepCheck_DataMapNodeOfDataMapOfShapeListOfStatus.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BRepCheck_DataMapNodeOfDataMapOfShapeResult.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BRepCheck_Edge.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BRepCheck_Face.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BRepCheck_ListNodeOfListOfStatus.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BRepCheck_Result.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BRepCheck_Shell.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BRepCheck_Vertex.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_BRepCheck_Wire.hxx"

#endif __BRepCheck_wrapper__
