// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __BSplCLib_wrapper__
#define __BSplCLib_wrapper__

#include "/Library/OCE/0.14/include/oce/BSplCLib.hxx"
#include "/Library/OCE/0.14/include/oce/BSplCLib_EvaluatorFunction.hxx"
#include "/Library/OCE/0.14/include/oce/BSplCLib_KnotDistribution.hxx"
#include "/Library/OCE/0.14/include/oce/BSplCLib_MultDistribution.hxx"

#endif __BSplCLib_wrapper__
