// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __ChFi3d_wrapper__
#define __ChFi3d_wrapper__

#include "/Library/OCE/0.14/include/oce/ChFi3d.hxx"
#include "/Library/OCE/0.14/include/oce/ChFi3d_Builder.hxx"
#include "/Library/OCE/0.14/include/oce/ChFi3d_Builder_0.hxx"
#include "/Library/OCE/0.14/include/oce/ChFi3d_ChBuilder.hxx"
#include "/Library/OCE/0.14/include/oce/ChFi3d_FilBuilder.hxx"
#include "/Library/OCE/0.14/include/oce/ChFi3d_FilletShape.hxx"
#include "/Library/OCE/0.14/include/oce/ChFi3d_SearchSing.hxx"

#endif __ChFi3d_wrapper__
