// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __Convert_wrapper__
#define __Convert_wrapper__

#include "/Library/OCE/0.14/include/oce/Convert_CircleToBSplineCurve.hxx"
#include "/Library/OCE/0.14/include/oce/Convert_CompBezierCurves2dToBSplineCurve2d.hxx"
#include "/Library/OCE/0.14/include/oce/Convert_CompBezierCurvesToBSplineCurve.hxx"
#include "/Library/OCE/0.14/include/oce/Convert_CompPolynomialToPoles.hxx"
#include "/Library/OCE/0.14/include/oce/Convert_ConeToBSplineSurface.hxx"
#include "/Library/OCE/0.14/include/oce/Convert_ConicToBSplineCurve.hxx"
#include "/Library/OCE/0.14/include/oce/Convert_CosAndSinEvalFunction.hxx"
#include "/Library/OCE/0.14/include/oce/Convert_CylinderToBSplineSurface.hxx"
#include "/Library/OCE/0.14/include/oce/Convert_ElementarySurfaceToBSplineSurface.hxx"
#include "/Library/OCE/0.14/include/oce/Convert_EllipseToBSplineCurve.hxx"
#include "/Library/OCE/0.14/include/oce/Convert_GridPolynomialToPoles.hxx"
#include "/Library/OCE/0.14/include/oce/Convert_HyperbolaToBSplineCurve.hxx"
#include "/Library/OCE/0.14/include/oce/Convert_ParabolaToBSplineCurve.hxx"
#include "/Library/OCE/0.14/include/oce/Convert_ParameterisationType.hxx"
#include "/Library/OCE/0.14/include/oce/Convert_PolynomialCosAndSin.hxx"
#include "/Library/OCE/0.14/include/oce/Convert_SequenceNodeOfSequenceOfArray1OfPoles.hxx"
#include "/Library/OCE/0.14/include/oce/Convert_SequenceOfArray1OfPoles.hxx"
#include "/Library/OCE/0.14/include/oce/Convert_SequenceOfArray1OfPoles2d.hxx"
#include "/Library/OCE/0.14/include/oce/Convert_SphereToBSplineSurface.hxx"
#include "/Library/OCE/0.14/include/oce/Convert_TorusToBSplineSurface.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Convert_SequenceNodeOfSequenceOfArray1OfPoles.hxx"

#endif __Convert_wrapper__
