// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __CPnts_wrapper__
#define __CPnts_wrapper__

#include "/Library/OCE/0.14/include/oce/CPnts_AbscissaPoint.hxx"
#include "/Library/OCE/0.14/include/oce/CPnts_MyGaussFunction.hxx"
#include "/Library/OCE/0.14/include/oce/CPnts_MyRootFunction.hxx"
#include "/Library/OCE/0.14/include/oce/CPnts_RealFunction.hxx"
#include "/Library/OCE/0.14/include/oce/CPnts_UniformDeflection.hxx"

#endif __CPnts_wrapper__
