// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __CSLib_wrapper__
#define __CSLib_wrapper__

#include "/Library/OCE/0.14/include/oce/CSLib.hxx"
#include "/Library/OCE/0.14/include/oce/CSLib_Class2d.hxx"
#include "/Library/OCE/0.14/include/oce/CSLib_DerivativeStatus.hxx"
#include "/Library/OCE/0.14/include/oce/CSLib_NormalPolyDef.hxx"
#include "/Library/OCE/0.14/include/oce/CSLib_NormalStatus.hxx"

#endif __CSLib_wrapper__
