// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __Dico_wrapper__
#define __Dico_wrapper__

#include "/Library/OCE/0.14/include/oce/Dico_DictionaryOfInteger.hxx"
#include "/Library/OCE/0.14/include/oce/Dico_DictionaryOfTransient.hxx"
#include "/Library/OCE/0.14/include/oce/Dico_IteratorOfDictionaryOfInteger.hxx"
#include "/Library/OCE/0.14/include/oce/Dico_IteratorOfDictionaryOfTransient.hxx"
#include "/Library/OCE/0.14/include/oce/Dico_StackItemOfDictionaryOfInteger.hxx"
#include "/Library/OCE/0.14/include/oce/Dico_StackItemOfDictionaryOfTransient.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Dico_DictionaryOfInteger.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Dico_DictionaryOfTransient.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Dico_StackItemOfDictionaryOfInteger.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Dico_StackItemOfDictionaryOfTransient.hxx"

#endif __Dico_wrapper__
