// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __Draft_wrapper__
#define __Draft_wrapper__

#include "/Library/OCE/0.14/include/oce/Draft.hxx"
#include "/Library/OCE/0.14/include/oce/Draft_DataMapIteratorOfDataMapOfEdgeEdgeInfo.hxx"
#include "/Library/OCE/0.14/include/oce/Draft_DataMapIteratorOfDataMapOfFaceFaceInfo.hxx"
#include "/Library/OCE/0.14/include/oce/Draft_DataMapIteratorOfDataMapOfVertexVertexInfo.hxx"
#include "/Library/OCE/0.14/include/oce/Draft_DataMapNodeOfDataMapOfEdgeEdgeInfo.hxx"
#include "/Library/OCE/0.14/include/oce/Draft_DataMapNodeOfDataMapOfFaceFaceInfo.hxx"
#include "/Library/OCE/0.14/include/oce/Draft_DataMapNodeOfDataMapOfVertexVertexInfo.hxx"
#include "/Library/OCE/0.14/include/oce/Draft_DataMapOfEdgeEdgeInfo.hxx"
#include "/Library/OCE/0.14/include/oce/Draft_DataMapOfFaceFaceInfo.hxx"
#include "/Library/OCE/0.14/include/oce/Draft_DataMapOfVertexVertexInfo.hxx"
#include "/Library/OCE/0.14/include/oce/Draft_EdgeInfo.hxx"
#include "/Library/OCE/0.14/include/oce/Draft_ErrorStatus.hxx"
#include "/Library/OCE/0.14/include/oce/Draft_FaceInfo.hxx"
#include "/Library/OCE/0.14/include/oce/Draft_Modification.hxx"
#include "/Library/OCE/0.14/include/oce/Draft_VertexInfo.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Draft_DataMapNodeOfDataMapOfEdgeEdgeInfo.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Draft_DataMapNodeOfDataMapOfFaceFaceInfo.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Draft_DataMapNodeOfDataMapOfVertexVertexInfo.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Draft_Modification.hxx"

#endif __Draft_wrapper__
