// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __DsgPrs_wrapper__
#define __DsgPrs_wrapper__

#include "/Library/OCE/0.14/include/oce/DsgPrs.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_AnglePresentation.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_ArrowSide.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_Chamf2dPresentation.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_ConcentricPresentation.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_DatumPrs.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_DatumTool.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_DiameterPresentation.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_EllipseRadiusPresentation.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_EqualDistancePresentation.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_EqualRadiusPresentation.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_FilletRadiusPresentation.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_FixPresentation.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_IdenticPresentation.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_LengthPresentation.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_MidPointPresentation.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_OffsetPresentation.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_ParalPresentation.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_PerpenPresentation.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_RadiusPresentation.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_ShadedPlanePresentation.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_ShapeDirPresentation.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_SymbPresentation.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_SymmetricPresentation.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_TangentPresentation.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_XYZAxisPresentation.hxx"
#include "/Library/OCE/0.14/include/oce/DsgPrs_XYZPlanePresentation.hxx"

#endif __DsgPrs_wrapper__
