// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __FairCurve_wrapper__
#define __FairCurve_wrapper__

#include "/Library/OCE/0.14/include/oce/FairCurve_AnalysisCode.hxx"
#include "/Library/OCE/0.14/include/oce/FairCurve_Batten.hxx"
#include "/Library/OCE/0.14/include/oce/FairCurve_BattenLaw.hxx"
#include "/Library/OCE/0.14/include/oce/FairCurve_DistributionOfEnergy.hxx"
#include "/Library/OCE/0.14/include/oce/FairCurve_DistributionOfJerk.hxx"
#include "/Library/OCE/0.14/include/oce/FairCurve_DistributionOfSagging.hxx"
#include "/Library/OCE/0.14/include/oce/FairCurve_DistributionOfTension.hxx"
#include "/Library/OCE/0.14/include/oce/FairCurve_Energy.hxx"
#include "/Library/OCE/0.14/include/oce/FairCurve_EnergyOfBatten.hxx"
#include "/Library/OCE/0.14/include/oce/FairCurve_EnergyOfMVC.hxx"
#include "/Library/OCE/0.14/include/oce/FairCurve_MinimalVariation.hxx"
#include "/Library/OCE/0.14/include/oce/FairCurve_Newton.hxx"

#endif __FairCurve_wrapper__
