// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __FilletSurf_wrapper__
#define __FilletSurf_wrapper__

#include "/Library/OCE/0.14/include/oce/FilletSurf_Builder.hxx"
#include "/Library/OCE/0.14/include/oce/FilletSurf_ErrorTypeStatus.hxx"
#include "/Library/OCE/0.14/include/oce/FilletSurf_InternalBuilder.hxx"
#include "/Library/OCE/0.14/include/oce/FilletSurf_StatusDone.hxx"
#include "/Library/OCE/0.14/include/oce/FilletSurf_StatusType.hxx"

#endif __FilletSurf_wrapper__
