// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __Font_wrapper__
#define __Font_wrapper__

#include "/Library/OCE/0.14/include/oce/Font_FontAspect.hxx"
#include "/Library/OCE/0.14/include/oce/Font_FontMgr.hxx"
#include "/Library/OCE/0.14/include/oce/Font_NListOfSystemFont.hxx"
#include "/Library/OCE/0.14/include/oce/Font_NameOfFont.hxx"
#include "/Library/OCE/0.14/include/oce/Font_SystemFont.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Font_FontMgr.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Font_SystemFont.hxx"

#endif __Font_wrapper__
