// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __GC_wrapper__
#define __GC_wrapper__

#include "/Library/OCE/0.14/include/oce/GC_MakeArcOfCircle.hxx"
#include "/Library/OCE/0.14/include/oce/GC_MakeArcOfEllipse.hxx"
#include "/Library/OCE/0.14/include/oce/GC_MakeArcOfHyperbola.hxx"
#include "/Library/OCE/0.14/include/oce/GC_MakeArcOfParabola.hxx"
#include "/Library/OCE/0.14/include/oce/GC_MakeCircle.hxx"
#include "/Library/OCE/0.14/include/oce/GC_MakeConicalSurface.hxx"
#include "/Library/OCE/0.14/include/oce/GC_MakeCylindricalSurface.hxx"
#include "/Library/OCE/0.14/include/oce/GC_MakeEllipse.hxx"
#include "/Library/OCE/0.14/include/oce/GC_MakeHyperbola.hxx"
#include "/Library/OCE/0.14/include/oce/GC_MakeLine.hxx"
#include "/Library/OCE/0.14/include/oce/GC_MakeMirror.hxx"
#include "/Library/OCE/0.14/include/oce/GC_MakePlane.hxx"
#include "/Library/OCE/0.14/include/oce/GC_MakeRotation.hxx"
#include "/Library/OCE/0.14/include/oce/GC_MakeScale.hxx"
#include "/Library/OCE/0.14/include/oce/GC_MakeSegment.hxx"
#include "/Library/OCE/0.14/include/oce/GC_MakeTranslation.hxx"
#include "/Library/OCE/0.14/include/oce/GC_MakeTrimmedCone.hxx"
#include "/Library/OCE/0.14/include/oce/GC_MakeTrimmedCylinder.hxx"
#include "/Library/OCE/0.14/include/oce/GC_Root.hxx"

#endif __GC_wrapper__
