// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __GccInt_wrapper__
#define __GccInt_wrapper__

#include "/Library/OCE/0.14/include/oce/GccInt_BCirc.hxx"
#include "/Library/OCE/0.14/include/oce/GccInt_BElips.hxx"
#include "/Library/OCE/0.14/include/oce/GccInt_BHyper.hxx"
#include "/Library/OCE/0.14/include/oce/GccInt_BLine.hxx"
#include "/Library/OCE/0.14/include/oce/GccInt_BParab.hxx"
#include "/Library/OCE/0.14/include/oce/GccInt_BPoint.hxx"
#include "/Library/OCE/0.14/include/oce/GccInt_Bisec.hxx"
#include "/Library/OCE/0.14/include/oce/GccInt_IType.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_GccInt_BCirc.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_GccInt_BElips.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_GccInt_BHyper.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_GccInt_BLine.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_GccInt_BParab.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_GccInt_BPoint.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_GccInt_Bisec.hxx"

#endif __GccInt_wrapper__
