// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __GccIter_wrapper__
#define __GccIter_wrapper__

#include "/Library/OCE/0.14/include/oce/GccIter_IsParallel.hxx"
#include "/Library/OCE/0.14/include/oce/GccIter_Type1.hxx"
#include "/Library/OCE/0.14/include/oce/GccIter_Type2.hxx"
#include "/Library/OCE/0.14/include/oce/GccIter_Type3.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_GccIter_IsParallel.hxx"

#endif __GccIter_wrapper__
