// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __GeomLib_wrapper__
#define __GeomLib_wrapper__

#include "/Library/OCE/0.14/include/oce/GeomLib.hxx"
#include "/Library/OCE/0.14/include/oce/GeomLib_Array1OfMat.hxx"
#include "/Library/OCE/0.14/include/oce/GeomLib_Check2dBSplineCurve.hxx"
#include "/Library/OCE/0.14/include/oce/GeomLib_CheckBSplineCurve.hxx"
#include "/Library/OCE/0.14/include/oce/GeomLib_DenominatorMultiplier.hxx"
#include "/Library/OCE/0.14/include/oce/GeomLib_DenominatorMultiplierPtr.hxx"
#include "/Library/OCE/0.14/include/oce/GeomLib_Interpolate.hxx"
#include "/Library/OCE/0.14/include/oce/GeomLib_InterpolationErrors.hxx"
#include "/Library/OCE/0.14/include/oce/GeomLib_IsPlanarSurface.hxx"
#include "/Library/OCE/0.14/include/oce/GeomLib_LogSample.hxx"
#include "/Library/OCE/0.14/include/oce/GeomLib_MakeCurvefromApprox.hxx"
#include "/Library/OCE/0.14/include/oce/GeomLib_PolyFunc.hxx"
#include "/Library/OCE/0.14/include/oce/GeomLib_Tool.hxx"

#endif __GeomLib_wrapper__
