// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __GeomProjLib_wrapper__
#define __GeomProjLib_wrapper__

#include "/Library/OCE/0.14/include/oce/GeomProjLib.hxx"

#endif __GeomProjLib_wrapper__
