// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __GeomToIGES_wrapper__
#define __GeomToIGES_wrapper__

#include "/Library/OCE/0.14/include/oce/GeomToIGES_GeomCurve.hxx"
#include "/Library/OCE/0.14/include/oce/GeomToIGES_GeomEntity.hxx"
#include "/Library/OCE/0.14/include/oce/GeomToIGES_GeomPoint.hxx"
#include "/Library/OCE/0.14/include/oce/GeomToIGES_GeomSurface.hxx"
#include "/Library/OCE/0.14/include/oce/GeomToIGES_GeomVector.hxx"

#endif __GeomToIGES_wrapper__
