// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __GeomAbs_wrapper__
#define __GeomAbs_wrapper__

#include "/Library/OCE/0.14/include/oce/GeomAbs_BSplKnotDistribution.hxx"
#include "/Library/OCE/0.14/include/oce/GeomAbs_CurveForm.hxx"
#include "/Library/OCE/0.14/include/oce/GeomAbs_CurveType.hxx"
#include "/Library/OCE/0.14/include/oce/GeomAbs_IsoType.hxx"
#include "/Library/OCE/0.14/include/oce/GeomAbs_JoinType.hxx"
#include "/Library/OCE/0.14/include/oce/GeomAbs_Shape.hxx"
#include "/Library/OCE/0.14/include/oce/GeomAbs_SurfaceForm.hxx"
#include "/Library/OCE/0.14/include/oce/GeomAbs_SurfaceType.hxx"
#include "/Library/OCE/0.14/include/oce/GeomAbs_UVSense.hxx"

#endif __GeomAbs_wrapper__
