// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __Geom2dInt_wrapper__
#define __Geom2dInt_wrapper__

#include "/Library/OCE/0.14/include/oce/Geom2dInt_ExactIntersectionPointOfTheIntPCurvePCurveOfGInter.hxx"
#include "/Library/OCE/0.14/include/oce/Geom2dInt_GInter.hxx"
#include "/Library/OCE/0.14/include/oce/Geom2dInt_Geom2dCurveTool.hxx"
#include "/Library/OCE/0.14/include/oce/Geom2dInt_IntConicCurveOfGInter.hxx"
#include "/Library/OCE/0.14/include/oce/Geom2dInt_MyImpParToolOfTheIntersectorOfTheIntConicCurveOfGInter.hxx"
#include "/Library/OCE/0.14/include/oce/Geom2dInt_PCLocFOfTheLocateExtPCOfTheProjPCurOfGInter.hxx"
#include "/Library/OCE/0.14/include/oce/Geom2dInt_SeqPCOfPCLocFOfTheLocateExtPCOfTheProjPCurOfGInter.hxx"
#include "/Library/OCE/0.14/include/oce/Geom2dInt_SequenceNodeOfSeqPCOfPCLocFOfTheLocateExtPCOfTheProjPCurOfGInter.hxx"
#include "/Library/OCE/0.14/include/oce/Geom2dInt_TheCurveLocatorOfTheProjPCurOfGInter.hxx"
#include "/Library/OCE/0.14/include/oce/Geom2dInt_TheDistBetweenPCurvesOfTheIntPCurvePCurveOfGInter.hxx"
#include "/Library/OCE/0.14/include/oce/Geom2dInt_TheIntConicCurveOfGInter.hxx"
#include "/Library/OCE/0.14/include/oce/Geom2dInt_TheIntPCurvePCurveOfGInter.hxx"
#include "/Library/OCE/0.14/include/oce/Geom2dInt_TheIntersectorOfTheIntConicCurveOfGInter.hxx"
#include "/Library/OCE/0.14/include/oce/Geom2dInt_TheLocateExtPCOfTheProjPCurOfGInter.hxx"
#include "/Library/OCE/0.14/include/oce/Geom2dInt_ThePolygon2dOfTheIntPCurvePCurveOfGInter.hxx"
#include "/Library/OCE/0.14/include/oce/Geom2dInt_TheProjPCurOfGInter.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Geom2dInt_SequenceNodeOfSeqPCOfPCLocFOfTheLocateExtPCOfTheProjPCurOfGInter.hxx"

#endif __Geom2dInt_wrapper__
