// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __Geom2dAPI_wrapper__
#define __Geom2dAPI_wrapper__

#include "/Library/OCE/0.14/include/oce/Geom2dAPI_ExtremaCurveCurve.hxx"
#include "/Library/OCE/0.14/include/oce/Geom2dAPI_InterCurveCurve.hxx"
#include "/Library/OCE/0.14/include/oce/Geom2dAPI_Interpolate.hxx"
#include "/Library/OCE/0.14/include/oce/Geom2dAPI_PointsToBSpline.hxx"
#include "/Library/OCE/0.14/include/oce/Geom2dAPI_ProjectPointOnCurve.hxx"

#endif __Geom2dAPI_wrapper__
