// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __GeomTools_wrapper__
#define __GeomTools_wrapper__

#include "/Library/OCE/0.14/include/oce/GeomTools.hxx"
#include "/Library/OCE/0.14/include/oce/GeomTools_Curve2dSet.hxx"
#include "/Library/OCE/0.14/include/oce/GeomTools_CurveSet.hxx"
#include "/Library/OCE/0.14/include/oce/GeomTools_SurfaceSet.hxx"
#include "/Library/OCE/0.14/include/oce/GeomTools_UndefinedTypeHandler.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_GeomTools_UndefinedTypeHandler.hxx"

#endif __GeomTools_wrapper__
