// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __GeomLProp_wrapper__
#define __GeomLProp_wrapper__

#include "/Library/OCE/0.14/include/oce/GeomLProp.hxx"
#include "/Library/OCE/0.14/include/oce/GeomLProp_CLProps.hxx"
#include "/Library/OCE/0.14/include/oce/GeomLProp_CurveTool.hxx"
#include "/Library/OCE/0.14/include/oce/GeomLProp_SLProps.hxx"
#include "/Library/OCE/0.14/include/oce/GeomLProp_SurfaceTool.hxx"

#endif __GeomLProp_wrapper__
