// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __GProp_wrapper__
#define __GProp_wrapper__

#include "/Library/OCE/0.14/include/oce/GProp.hxx"
#include "/Library/OCE/0.14/include/oce/GProp_CelGProps.hxx"
#include "/Library/OCE/0.14/include/oce/GProp_EquaType.hxx"
#include "/Library/OCE/0.14/include/oce/GProp_GProps.hxx"
#include "/Library/OCE/0.14/include/oce/GProp_PEquation.hxx"
#include "/Library/OCE/0.14/include/oce/GProp_PGProps.hxx"
#include "/Library/OCE/0.14/include/oce/GProp_PrincipalProps.hxx"
#include "/Library/OCE/0.14/include/oce/GProp_SelGProps.hxx"
#include "/Library/OCE/0.14/include/oce/GProp_UndefinedAxis.hxx"
#include "/Library/OCE/0.14/include/oce/GProp_ValueType.hxx"
#include "/Library/OCE/0.14/include/oce/GProp_VelGProps.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_GProp_UndefinedAxis.hxx"

#endif __GProp_wrapper__
