// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __GraphDS_wrapper__
#define __GraphDS_wrapper__

#include "/Library/OCE/0.14/include/oce/GraphDS_DataMapIteratorOfEntityRoleMap.hxx"
#include "/Library/OCE/0.14/include/oce/GraphDS_DataMapNodeOfEntityRoleMap.hxx"
#include "/Library/OCE/0.14/include/oce/GraphDS_EntityRole.hxx"
#include "/Library/OCE/0.14/include/oce/GraphDS_EntityRoleMap.hxx"
#include "/Library/OCE/0.14/include/oce/GraphDS_RelationRole.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_GraphDS_DataMapNodeOfEntityRoleMap.hxx"

#endif __GraphDS_wrapper__
