// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __GraphTools_wrapper__
#define __GraphTools_wrapper__

#include "/Library/OCE/0.14/include/oce/GraphTools_ListIteratorOfListOfSequenceOfInteger.hxx"
#include "/Library/OCE/0.14/include/oce/GraphTools_ListIteratorOfSCList.hxx"
#include "/Library/OCE/0.14/include/oce/GraphTools_ListNodeOfListOfSequenceOfInteger.hxx"
#include "/Library/OCE/0.14/include/oce/GraphTools_ListNodeOfSCList.hxx"
#include "/Library/OCE/0.14/include/oce/GraphTools_ListOfSequenceOfInteger.hxx"
#include "/Library/OCE/0.14/include/oce/GraphTools_RGNode.hxx"
#include "/Library/OCE/0.14/include/oce/GraphTools_SC.hxx"
#include "/Library/OCE/0.14/include/oce/GraphTools_SCList.hxx"
#include "/Library/OCE/0.14/include/oce/GraphTools_TSNode.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_GraphTools_ListNodeOfListOfSequenceOfInteger.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_GraphTools_ListNodeOfSCList.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_GraphTools_SC.hxx"

#endif __GraphTools_wrapper__
