// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __HatchGen_wrapper__
#define __HatchGen_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_HatchGen_SequenceNodeOfDomains.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_HatchGen_SequenceNodeOfPointsOnElement.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_HatchGen_SequenceNodeOfPointsOnHatching.hxx"
#include "/Library/OCE/0.14/include/oce/HatchGen_Domain.hxx"
#include "/Library/OCE/0.14/include/oce/HatchGen_Domains.hxx"
#include "/Library/OCE/0.14/include/oce/HatchGen_ErrorStatus.hxx"
#include "/Library/OCE/0.14/include/oce/HatchGen_IntersectionPoint.hxx"
#include "/Library/OCE/0.14/include/oce/HatchGen_IntersectionType.hxx"
#include "/Library/OCE/0.14/include/oce/HatchGen_PointOnElement.hxx"
#include "/Library/OCE/0.14/include/oce/HatchGen_PointOnHatching.hxx"
#include "/Library/OCE/0.14/include/oce/HatchGen_PointsOnElement.hxx"
#include "/Library/OCE/0.14/include/oce/HatchGen_PointsOnHatching.hxx"
#include "/Library/OCE/0.14/include/oce/HatchGen_SequenceNodeOfDomains.hxx"
#include "/Library/OCE/0.14/include/oce/HatchGen_SequenceNodeOfPointsOnElement.hxx"
#include "/Library/OCE/0.14/include/oce/HatchGen_SequenceNodeOfPointsOnHatching.hxx"

#endif __HatchGen_wrapper__
