// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __IGESControl_wrapper__
#define __IGESControl_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_IGESControl_ActorWrite.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_IGESControl_AlgoContainer.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_IGESControl_Controller.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_IGESControl_IGESBoundary.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_IGESControl_ToolContainer.hxx"
#include "/Library/OCE/0.14/include/oce/IGESControl_ActorWrite.hxx"
#include "/Library/OCE/0.14/include/oce/IGESControl_AlgoContainer.hxx"
#include "/Library/OCE/0.14/include/oce/IGESControl_Controller.hxx"
#include "/Library/OCE/0.14/include/oce/IGESControl_IGESBoundary.hxx"
#include "/Library/OCE/0.14/include/oce/IGESControl_Reader.hxx"
#include "/Library/OCE/0.14/include/oce/IGESControl_ToolContainer.hxx"
#include "/Library/OCE/0.14/include/oce/IGESControl_Writer.hxx"

#endif __IGESControl_wrapper__
