// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __IGESToBRep_wrapper__
#define __IGESToBRep_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_IGESToBRep_Actor.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_IGESToBRep_AlgoContainer.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_IGESToBRep_IGESBoundary.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_IGESToBRep_ToolContainer.hxx"
#include "/Library/OCE/0.14/include/oce/IGESToBRep.hxx"
#include "/Library/OCE/0.14/include/oce/IGESToBRep_Actor.hxx"
#include "/Library/OCE/0.14/include/oce/IGESToBRep_AlgoContainer.hxx"
#include "/Library/OCE/0.14/include/oce/IGESToBRep_BRepEntity.hxx"
#include "/Library/OCE/0.14/include/oce/IGESToBRep_BasicCurve.hxx"
#include "/Library/OCE/0.14/include/oce/IGESToBRep_BasicSurface.hxx"
#include "/Library/OCE/0.14/include/oce/IGESToBRep_CurveAndSurface.hxx"
#include "/Library/OCE/0.14/include/oce/IGESToBRep_IGESBoundary.hxx"
#include "/Library/OCE/0.14/include/oce/IGESToBRep_Reader.hxx"
#include "/Library/OCE/0.14/include/oce/IGESToBRep_ToolContainer.hxx"
#include "/Library/OCE/0.14/include/oce/IGESToBRep_TopoCurve.hxx"
#include "/Library/OCE/0.14/include/oce/IGESToBRep_TopoSurface.hxx"

#endif __IGESToBRep_wrapper__
