// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __IGESConvGeom_wrapper__
#define __IGESConvGeom_wrapper__

#include "/Library/OCE/0.14/include/oce/IGESConvGeom.hxx"
#include "/Library/OCE/0.14/include/oce/IGESConvGeom_GeomBuilder.hxx"

#endif __IGESConvGeom_wrapper__
