// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __IntAna_wrapper__
#define __IntAna_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_IntAna_ListNodeOfListOfCurve.hxx"
#include "/Library/OCE/0.14/include/oce/IntAna_Curve.hxx"
#include "/Library/OCE/0.14/include/oce/IntAna_Int3Pln.hxx"
#include "/Library/OCE/0.14/include/oce/IntAna_IntConicQuad.hxx"
#include "/Library/OCE/0.14/include/oce/IntAna_IntLinTorus.hxx"
#include "/Library/OCE/0.14/include/oce/IntAna_IntQuadQuad.hxx"
#include "/Library/OCE/0.14/include/oce/IntAna_ListIteratorOfListOfCurve.hxx"
#include "/Library/OCE/0.14/include/oce/IntAna_ListNodeOfListOfCurve.hxx"
#include "/Library/OCE/0.14/include/oce/IntAna_ListOfCurve.hxx"
#include "/Library/OCE/0.14/include/oce/IntAna_QuadQuadGeo.hxx"
#include "/Library/OCE/0.14/include/oce/IntAna_Quadric.hxx"
#include "/Library/OCE/0.14/include/oce/IntAna_ResultType.hxx"

#endif __IntAna_wrapper__
