// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __IntAna2d_wrapper__
#define __IntAna2d_wrapper__

#include "/Library/OCE/0.14/include/oce/IntAna2d_AnaIntersection.hxx"
#include "/Library/OCE/0.14/include/oce/IntAna2d_Conic.hxx"
#include "/Library/OCE/0.14/include/oce/IntAna2d_IntPoint.hxx"
#include "/Library/OCE/0.14/include/oce/IntAna2d_Outils.hxx"

#endif __IntAna2d_wrapper__
