// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __IntCurvesFace_wrapper__
#define __IntCurvesFace_wrapper__

#include "/Library/OCE/0.14/include/oce/IntCurvesFace_Intersector.hxx"
#include "/Library/OCE/0.14/include/oce/IntCurvesFace_ShapeIntersector.hxx"

#endif __IntCurvesFace_wrapper__
