// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __IntCurve_wrapper__
#define __IntCurve_wrapper__

#include "/Library/OCE/0.14/include/oce/IntCurve_IConicTool.hxx"
#include "/Library/OCE/0.14/include/oce/IntCurve_IntConicConic.hxx"
#include "/Library/OCE/0.14/include/oce/IntCurve_IntConicConic_1.hxx"
#include "/Library/OCE/0.14/include/oce/IntCurve_IntConicConic_Tool.hxx"
#include "/Library/OCE/0.14/include/oce/IntCurve_IntImpConicParConic.hxx"
#include "/Library/OCE/0.14/include/oce/IntCurve_MyImpParToolOfIntImpConicParConic.hxx"
#include "/Library/OCE/0.14/include/oce/IntCurve_PConic.hxx"
#include "/Library/OCE/0.14/include/oce/IntCurve_PConicTool.hxx"
#include "/Library/OCE/0.14/include/oce/IntCurve_ProjectOnPConicTool.hxx"

#endif __IntCurve_wrapper__
