// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __Intf_wrapper__
#define __Intf_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_Intf_SequenceNodeOfSeqOfSectionLine.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Intf_SequenceNodeOfSeqOfSectionPoint.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Intf_SequenceNodeOfSeqOfTangentZone.hxx"
#include "/Library/OCE/0.14/include/oce/Intf.hxx"
#include "/Library/OCE/0.14/include/oce/Intf_Array1OfLin.hxx"
#include "/Library/OCE/0.14/include/oce/Intf_Interference.hxx"
#include "/Library/OCE/0.14/include/oce/Intf_InterferencePolygon2d.hxx"
#include "/Library/OCE/0.14/include/oce/Intf_PIType.hxx"
#include "/Library/OCE/0.14/include/oce/Intf_Polygon2d.hxx"
#include "/Library/OCE/0.14/include/oce/Intf_SectionLine.hxx"
#include "/Library/OCE/0.14/include/oce/Intf_SectionPoint.hxx"
#include "/Library/OCE/0.14/include/oce/Intf_SeqOfSectionLine.hxx"
#include "/Library/OCE/0.14/include/oce/Intf_SeqOfSectionPoint.hxx"
#include "/Library/OCE/0.14/include/oce/Intf_SeqOfTangentZone.hxx"
#include "/Library/OCE/0.14/include/oce/Intf_SequenceNodeOfSeqOfSectionLine.hxx"
#include "/Library/OCE/0.14/include/oce/Intf_SequenceNodeOfSeqOfSectionPoint.hxx"
#include "/Library/OCE/0.14/include/oce/Intf_SequenceNodeOfSeqOfTangentZone.hxx"
#include "/Library/OCE/0.14/include/oce/Intf_TangentZone.hxx"
#include "/Library/OCE/0.14/include/oce/Intf_Tool.hxx"

#endif __Intf_wrapper__
