// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __IntImp_wrapper__
#define __IntImp_wrapper__

#include "/Library/OCE/0.14/include/oce/IntImp_ComputeTangence.hxx"
#include "/Library/OCE/0.14/include/oce/IntImp_ConstIsoparametric.hxx"

#endif __IntImp_wrapper__
