// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __IntPoly_wrapper__
#define __IntPoly_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_IntPoly_IndexedMapNodeOfIndexedMapOfPnt.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_IntPoly_IndexedMapNodeOfIndexedMapOfPnt2d.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_IntPoly_SequenceNodeOfSequenceOfSequenceOfPnt.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_IntPoly_SequenceNodeOfSequenceOfSequenceOfPnt2d.hxx"
#include "/Library/OCE/0.14/include/oce/IntPoly_IndexedMapNodeOfIndexedMapOfPnt.hxx"
#include "/Library/OCE/0.14/include/oce/IntPoly_IndexedMapNodeOfIndexedMapOfPnt2d.hxx"
#include "/Library/OCE/0.14/include/oce/IntPoly_IndexedMapOfPnt.hxx"
#include "/Library/OCE/0.14/include/oce/IntPoly_IndexedMapOfPnt2d.hxx"
#include "/Library/OCE/0.14/include/oce/IntPoly_PlaneSection.hxx"
#include "/Library/OCE/0.14/include/oce/IntPoly_Pnt2dHasher.hxx"
#include "/Library/OCE/0.14/include/oce/IntPoly_PntHasher.hxx"
#include "/Library/OCE/0.14/include/oce/IntPoly_SequenceNodeOfSequenceOfSequenceOfPnt.hxx"
#include "/Library/OCE/0.14/include/oce/IntPoly_SequenceNodeOfSequenceOfSequenceOfPnt2d.hxx"
#include "/Library/OCE/0.14/include/oce/IntPoly_SequenceOfSequenceOfPnt.hxx"
#include "/Library/OCE/0.14/include/oce/IntPoly_SequenceOfSequenceOfPnt2d.hxx"
#include "/Library/OCE/0.14/include/oce/IntPoly_ShapeSection.hxx"

#endif __IntPoly_wrapper__
