// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __Intrv_wrapper__
#define __Intrv_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_Intrv_SequenceNodeOfSequenceOfInterval.hxx"
#include "/Library/OCE/0.14/include/oce/Intrv_Interval.hxx"
#include "/Library/OCE/0.14/include/oce/Intrv_Intervals.hxx"
#include "/Library/OCE/0.14/include/oce/Intrv_Position.hxx"
#include "/Library/OCE/0.14/include/oce/Intrv_SequenceNodeOfSequenceOfInterval.hxx"
#include "/Library/OCE/0.14/include/oce/Intrv_SequenceOfInterval.hxx"

#endif __Intrv_wrapper__
