// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __IntStart_wrapper__
#define __IntStart_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_IntStart_SITopolTool.hxx"
#include "/Library/OCE/0.14/include/oce/IntStart_SITopolTool.hxx"

#endif __IntStart_wrapper__
