// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __Law_wrapper__
#define __Law_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_Law_BSpFunc.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Law_BSpline.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Law_Composite.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Law_Constant.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Law_Function.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Law_Interpol.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Law_Linear.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Law_ListNodeOfLaws.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Law_S.hxx"
#include "/Library/OCE/0.14/include/oce/Law.hxx"
#include "/Library/OCE/0.14/include/oce/Law_BSpFunc.hxx"
#include "/Library/OCE/0.14/include/oce/Law_BSpline.hxx"
#include "/Library/OCE/0.14/include/oce/Law_BSplineKnotSplitting.hxx"
#include "/Library/OCE/0.14/include/oce/Law_Composite.hxx"
#include "/Library/OCE/0.14/include/oce/Law_Constant.hxx"
#include "/Library/OCE/0.14/include/oce/Law_Function.hxx"
#include "/Library/OCE/0.14/include/oce/Law_Interpol.hxx"
#include "/Library/OCE/0.14/include/oce/Law_Interpolate.hxx"
#include "/Library/OCE/0.14/include/oce/Law_Laws.hxx"
#include "/Library/OCE/0.14/include/oce/Law_Linear.hxx"
#include "/Library/OCE/0.14/include/oce/Law_ListIteratorOfLaws.hxx"
#include "/Library/OCE/0.14/include/oce/Law_ListNodeOfLaws.hxx"
#include "/Library/OCE/0.14/include/oce/Law_S.hxx"

#endif __Law_wrapper__
