// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __LDOMParser_wrapper__
#define __LDOMParser_wrapper__

#include "/Library/OCE/0.14/include/oce/LDOMParser.hxx"

#endif __LDOMParser_wrapper__
