// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __LocalAnalysis_wrapper__
#define __LocalAnalysis_wrapper__

#include "/Library/OCE/0.14/include/oce/LocalAnalysis.hxx"
#include "/Library/OCE/0.14/include/oce/LocalAnalysis_CurveContinuity.hxx"
#include "/Library/OCE/0.14/include/oce/LocalAnalysis_StatusErrorType.hxx"
#include "/Library/OCE/0.14/include/oce/LocalAnalysis_SurfaceContinuity.hxx"

#endif __LocalAnalysis_wrapper__
