// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __Message_wrapper__
#define __Message_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_Message_Algorithm.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Message_ListNodeOfListOfMsg.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Message_Messenger.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Message_Printer.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Message_PrinterOStream.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Message_ProgressIndicator.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Message_SequenceNodeOfSequenceOfPrinters.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Message_SequenceNodeOfSequenceOfProgressScale.hxx"
#include "/Library/OCE/0.14/include/oce/Message.hxx"
#include "/Library/OCE/0.14/include/oce/Message_Gravity.hxx"
#include "/Library/OCE/0.14/include/oce/Message_ListIteratorOfListOfMsg.hxx"
#include "/Library/OCE/0.14/include/oce/Message_ListNodeOfListOfMsg.hxx"
#include "/Library/OCE/0.14/include/oce/Message_ListOfMsg.hxx"
#include "/Library/OCE/0.14/include/oce/Message_Messenger.hxx"
#include "/Library/OCE/0.14/include/oce/Message_Msg.hxx"
#include "/Library/OCE/0.14/include/oce/Message_MsgFile.hxx"
#include "/Library/OCE/0.14/include/oce/Message_Printer.hxx"
#include "/Library/OCE/0.14/include/oce/Message_PrinterOStream.hxx"
#include "/Library/OCE/0.14/include/oce/Message_ProgressIndicator.hxx"
#include "/Library/OCE/0.14/include/oce/Message_ProgressScale.hxx"
#include "/Library/OCE/0.14/include/oce/Message_ProgressSentry.hxx"
#include "/Library/OCE/0.14/include/oce/Message_SequenceNodeOfSequenceOfPrinters.hxx"
#include "/Library/OCE/0.14/include/oce/Message_SequenceNodeOfSequenceOfProgressScale.hxx"
#include "/Library/OCE/0.14/include/oce/Message_SequenceOfPrinters.hxx"
#include "/Library/OCE/0.14/include/oce/Message_SequenceOfProgressScale.hxx"
#include "/Library/OCE/0.14/include/oce/Message_Status.hxx"
#include "/Library/OCE/0.14/include/oce/Message_StatusType.hxx"

#endif __Message_wrapper__
