// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __MFunction_wrapper__
#define __MFunction_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_MFunction_FunctionRetrievalDriver.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_MFunction_FunctionStorageDriver.hxx"
#include "/Library/OCE/0.14/include/oce/MFunction.hxx"
#include "/Library/OCE/0.14/include/oce/MFunction_FunctionRetrievalDriver.hxx"
#include "/Library/OCE/0.14/include/oce/MFunction_FunctionStorageDriver.hxx"

#endif __MFunction_wrapper__
