// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __MgtBRep_wrapper__
#define __MgtBRep_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_MgtBRep_TranslateTool.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_MgtBRep_TranslateTool1.hxx"
#include "/Library/OCE/0.14/include/oce/MgtBRep.hxx"
#include "/Library/OCE/0.14/include/oce/MgtBRep_TranslateTool.hxx"
#include "/Library/OCE/0.14/include/oce/MgtBRep_TranslateTool1.hxx"
#include "/Library/OCE/0.14/include/oce/MgtBRep_TriangleMode.hxx"

#endif __MgtBRep_wrapper__
