// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __MMgt_wrapper__
#define __MMgt_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_MMgt_TShared.hxx"
#include "/Library/OCE/0.14/include/oce/MMgt_StackManager.hxx"
#include "/Library/OCE/0.14/include/oce/MMgt_TShared.hxx"

#endif __MMgt_wrapper__
