// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __NIS_wrapper__
#define __NIS_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_NIS_InteractiveObject.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_NIS_View.hxx"
#include "/Library/OCE/0.14/include/oce/NIS_Allocator.hxx"
#include "/Library/OCE/0.14/include/oce/NIS_DrawList.hxx"
#include "/Library/OCE/0.14/include/oce/NIS_Drawer.hxx"
#include "/Library/OCE/0.14/include/oce/NIS_InteractiveContext.hxx"
#include "/Library/OCE/0.14/include/oce/NIS_InteractiveObject.hxx"
#include "/Library/OCE/0.14/include/oce/NIS_ObjectsIterator.hxx"
#include "/Library/OCE/0.14/include/oce/NIS_SelectFilter.hxx"
#include "/Library/OCE/0.14/include/oce/NIS_Surface.hxx"
#include "/Library/OCE/0.14/include/oce/NIS_SurfaceDrawer.hxx"
#include "/Library/OCE/0.14/include/oce/NIS_Triangulated.hxx"
#include "/Library/OCE/0.14/include/oce/NIS_TriangulatedDrawer.hxx"
#include "/Library/OCE/0.14/include/oce/NIS_View.hxx"

#endif __NIS_wrapper__
