// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __NMTTools_wrapper__
#define __NMTTools_wrapper__

#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/NMTTools_CheckerSI.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/NMTTools_CommonBlock.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/NMTTools_CommonBlockAPI.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/NMTTools_CommonBlockPool.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/NMTTools_CoupleOfShape.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/NMTTools_DEProcessor.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/NMTTools_DataMapIteratorOfDataMapOfIntegerFaceInfo.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/NMTTools_DataMapIteratorOfDataMapOfIntegerListOfPaveBlock.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/NMTTools_DataMapOfIntegerFaceInfo.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/NMTTools_DataMapOfIntegerListOfPaveBlock.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/NMTTools_FaceInfo.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/NMTTools_IndexedDataMapOfIndexedMapOfInteger.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/NMTTools_IndexedDataMapOfShapeIndexedMapOfShape.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/NMTTools_IndexedDataMapOfShapePaveBlock.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/NMTTools_ListIteratorOfListOfCommonBlock.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/NMTTools_ListIteratorOfListOfCoupleOfShape.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/NMTTools_ListOfCommonBlock.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/NMTTools_ListOfCoupleOfShape.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/NMTTools_MapIteratorOfMapOfPaveBlock.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/NMTTools_MapOfPaveBlock.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/NMTTools_PPaveFiller.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/NMTTools_PaveFiller.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/NMTTools_Tools.hxx"

#endif __NMTTools_wrapper__
