// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __PCDMShape_wrapper__
#define __PCDMShape_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_PCDMShape_Document.hxx"
#include "/Library/OCE/0.14/include/oce/PCDMShape_Document.hxx"

#endif __PCDMShape_wrapper__
