// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __PColPGeom2d_wrapper__
#define __PColPGeom2d_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_PColPGeom2d_HArray1OfBSplineCurve.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PColPGeom2d_HArray1OfBezierCurve.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PColPGeom2d_HArray1OfBoundedCurve.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PColPGeom2d_HArray1OfCurve.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PColPGeom2d_VArrayNodeOfFieldOfHArray1OfBSplineCurve.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PColPGeom2d_VArrayNodeOfFieldOfHArray1OfBezierCurve.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PColPGeom2d_VArrayNodeOfFieldOfHArray1OfBoundedCurve.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PColPGeom2d_VArrayNodeOfFieldOfHArray1OfCurve.hxx"
#include "/Library/OCE/0.14/include/oce/PColPGeom2d_FieldOfHArray1OfBSplineCurve.hxx"
#include "/Library/OCE/0.14/include/oce/PColPGeom2d_FieldOfHArray1OfBezierCurve.hxx"
#include "/Library/OCE/0.14/include/oce/PColPGeom2d_FieldOfHArray1OfBoundedCurve.hxx"
#include "/Library/OCE/0.14/include/oce/PColPGeom2d_FieldOfHArray1OfCurve.hxx"
#include "/Library/OCE/0.14/include/oce/PColPGeom2d_HArray1OfBSplineCurve.hxx"
#include "/Library/OCE/0.14/include/oce/PColPGeom2d_HArray1OfBezierCurve.hxx"
#include "/Library/OCE/0.14/include/oce/PColPGeom2d_HArray1OfBoundedCurve.hxx"
#include "/Library/OCE/0.14/include/oce/PColPGeom2d_HArray1OfCurve.hxx"
#include "/Library/OCE/0.14/include/oce/PColPGeom2d_VArrayNodeOfFieldOfHArray1OfBSplineCurve.hxx"
#include "/Library/OCE/0.14/include/oce/PColPGeom2d_VArrayNodeOfFieldOfHArray1OfBezierCurve.hxx"
#include "/Library/OCE/0.14/include/oce/PColPGeom2d_VArrayNodeOfFieldOfHArray1OfBoundedCurve.hxx"
#include "/Library/OCE/0.14/include/oce/PColPGeom2d_VArrayNodeOfFieldOfHArray1OfCurve.hxx"
#include "/Library/OCE/0.14/include/oce/PColPGeom2d_VArrayTNodeOfFieldOfHArray1OfBSplineCurve.hxx"
#include "/Library/OCE/0.14/include/oce/PColPGeom2d_VArrayTNodeOfFieldOfHArray1OfBezierCurve.hxx"
#include "/Library/OCE/0.14/include/oce/PColPGeom2d_VArrayTNodeOfFieldOfHArray1OfBoundedCurve.hxx"
#include "/Library/OCE/0.14/include/oce/PColPGeom2d_VArrayTNodeOfFieldOfHArray1OfCurve.hxx"

#endif __PColPGeom2d_wrapper__
