// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __PCollection_wrapper__
#define __PCollection_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_PCollection_HAsciiString.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PCollection_HExtendedString.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PCollection_IsContained.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PCollection_IsNotRoot.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PCollection_IsNullTree.hxx"
#include "/Library/OCE/0.14/include/oce/PCollection_AccessMode.hxx"
#include "/Library/OCE/0.14/include/oce/PCollection_CompareOfInteger.hxx"
#include "/Library/OCE/0.14/include/oce/PCollection_CompareOfReal.hxx"
#include "/Library/OCE/0.14/include/oce/PCollection_HAsciiString.hxx"
#include "/Library/OCE/0.14/include/oce/PCollection_HExtendedString.hxx"
#include "/Library/OCE/0.14/include/oce/PCollection_IsContained.hxx"
#include "/Library/OCE/0.14/include/oce/PCollection_IsNotRoot.hxx"
#include "/Library/OCE/0.14/include/oce/PCollection_IsNullTree.hxx"
#include "/Library/OCE/0.14/include/oce/PCollection_PrivCompareOfInteger.hxx"
#include "/Library/OCE/0.14/include/oce/PCollection_PrivCompareOfReal.hxx"
#include "/Library/OCE/0.14/include/oce/PCollection_Side.hxx"

#endif __PCollection_wrapper__
