// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __PDF_wrapper__
#define __PDF_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_PDF_Attribute.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PDF_Data.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PDF_HAttributeArray1.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PDF_Reference.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PDF_TagSource.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PDF_VArrayNodeOfFieldOfHAttributeArray1.hxx"
#include "/Library/OCE/0.14/include/oce/PDF_Attribute.hxx"
#include "/Library/OCE/0.14/include/oce/PDF_Data.hxx"
#include "/Library/OCE/0.14/include/oce/PDF_FieldOfHAttributeArray1.hxx"
#include "/Library/OCE/0.14/include/oce/PDF_HAttributeArray1.hxx"
#include "/Library/OCE/0.14/include/oce/PDF_Reference.hxx"
#include "/Library/OCE/0.14/include/oce/PDF_TagSource.hxx"
#include "/Library/OCE/0.14/include/oce/PDF_VArrayNodeOfFieldOfHAttributeArray1.hxx"
#include "/Library/OCE/0.14/include/oce/PDF_VArrayTNodeOfFieldOfHAttributeArray1.hxx"

#endif __PDF_wrapper__
