// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __PFunction_wrapper__
#define __PFunction_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_PFunction_Function.hxx"
#include "/Library/OCE/0.14/include/oce/PFunction_Function.hxx"

#endif __PFunction_wrapper__
