// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __PMMgt_wrapper__
#define __PMMgt_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_PMMgt_PManaged.hxx"
#include "/Library/OCE/0.14/include/oce/PMMgt_PManaged.hxx"

#endif __PMMgt_wrapper__
