// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __Poly_wrapper__
#define __Poly_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_Poly_CoherentTriangulation.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Poly_HArray1OfTriangle.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Poly_Polygon2D.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Poly_Polygon3D.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Poly_PolygonOnTriangulation.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Poly_Triangulation.hxx"
#include "/Library/OCE/0.14/include/oce/Poly.hxx"
#include "/Library/OCE/0.14/include/oce/Poly_Array1OfTriangle.hxx"
#include "/Library/OCE/0.14/include/oce/Poly_CoherentLink.hxx"
#include "/Library/OCE/0.14/include/oce/Poly_CoherentNode.hxx"
#include "/Library/OCE/0.14/include/oce/Poly_CoherentTriPtr.hxx"
#include "/Library/OCE/0.14/include/oce/Poly_CoherentTriangle.hxx"
#include "/Library/OCE/0.14/include/oce/Poly_CoherentTriangulation.hxx"
#include "/Library/OCE/0.14/include/oce/Poly_Connect.hxx"
#include "/Library/OCE/0.14/include/oce/Poly_HArray1OfTriangle.hxx"
#include "/Library/OCE/0.14/include/oce/Poly_ListOfTriangulation.hxx"
#include "/Library/OCE/0.14/include/oce/Poly_MakeLoops.hxx"
#include "/Library/OCE/0.14/include/oce/Poly_Polygon2D.hxx"
#include "/Library/OCE/0.14/include/oce/Poly_Polygon3D.hxx"
#include "/Library/OCE/0.14/include/oce/Poly_PolygonOnTriangulation.hxx"
#include "/Library/OCE/0.14/include/oce/Poly_Triangle.hxx"
#include "/Library/OCE/0.14/include/oce/Poly_Triangulation.hxx"

#endif __Poly_wrapper__
