// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __Primitives_wrapper__
#define __Primitives_wrapper__

#include "/Library/OCE/0.14/include/oce/Primitives_Direction.hxx"

#endif __Primitives_wrapper__
