// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __ProjLib_wrapper__
#define __ProjLib_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_ProjLib_HCompProjectedCurve.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_ProjLib_HProjectedCurve.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_ProjLib_HSequenceOfHSequenceOfPnt.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_ProjLib_SequenceNodeOfSequenceOfHSequenceOfPnt.hxx"
#include "/Library/OCE/0.14/include/oce/ProjLib.hxx"
#include "/Library/OCE/0.14/include/oce/ProjLib_CompProjectedCurve.hxx"
#include "/Library/OCE/0.14/include/oce/ProjLib_ComputeApprox.hxx"
#include "/Library/OCE/0.14/include/oce/ProjLib_ComputeApproxOnPolarSurface.hxx"
#include "/Library/OCE/0.14/include/oce/ProjLib_Cone.hxx"
#include "/Library/OCE/0.14/include/oce/ProjLib_Cylinder.hxx"
#include "/Library/OCE/0.14/include/oce/ProjLib_HCompProjectedCurve.hxx"
#include "/Library/OCE/0.14/include/oce/ProjLib_HProjectedCurve.hxx"
#include "/Library/OCE/0.14/include/oce/ProjLib_HSequenceOfHSequenceOfPnt.hxx"
#include "/Library/OCE/0.14/include/oce/ProjLib_Plane.hxx"
#include "/Library/OCE/0.14/include/oce/ProjLib_PrjFunc.hxx"
#include "/Library/OCE/0.14/include/oce/ProjLib_PrjResolve.hxx"
#include "/Library/OCE/0.14/include/oce/ProjLib_ProjectOnPlane.hxx"
#include "/Library/OCE/0.14/include/oce/ProjLib_ProjectOnSurface.hxx"
#include "/Library/OCE/0.14/include/oce/ProjLib_ProjectedCurve.hxx"
#include "/Library/OCE/0.14/include/oce/ProjLib_Projector.hxx"
#include "/Library/OCE/0.14/include/oce/ProjLib_SequenceNodeOfSequenceOfHSequenceOfPnt.hxx"
#include "/Library/OCE/0.14/include/oce/ProjLib_SequenceOfHSequenceOfPnt.hxx"
#include "/Library/OCE/0.14/include/oce/ProjLib_Sphere.hxx"
#include "/Library/OCE/0.14/include/oce/ProjLib_Torus.hxx"

#endif __ProjLib_wrapper__
