// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __PrsMgr_wrapper__
#define __PrsMgr_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_PrsMgr_PresentableObject.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PrsMgr_Presentation.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PrsMgr_Presentation3d.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PrsMgr_PresentationManager.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PrsMgr_PresentationManager3d.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PrsMgr_Prs.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PrsMgr_SequenceNodeOfPresentations.hxx"
#include "/Library/OCE/0.14/include/oce/PrsMgr_KindOfPrs.hxx"
#include "/Library/OCE/0.14/include/oce/PrsMgr_ModedPresentation.hxx"
#include "/Library/OCE/0.14/include/oce/PrsMgr_PresentableObject.hxx"
#include "/Library/OCE/0.14/include/oce/PrsMgr_PresentableObjectPointer.hxx"
#include "/Library/OCE/0.14/include/oce/PrsMgr_Presentation.hxx"
#include "/Library/OCE/0.14/include/oce/PrsMgr_Presentation3d.hxx"
#include "/Library/OCE/0.14/include/oce/PrsMgr_Presentation3dPointer.hxx"
#include "/Library/OCE/0.14/include/oce/PrsMgr_PresentationManager.hxx"
#include "/Library/OCE/0.14/include/oce/PrsMgr_PresentationManager3d.hxx"
#include "/Library/OCE/0.14/include/oce/PrsMgr_Presentations.hxx"
#include "/Library/OCE/0.14/include/oce/PrsMgr_Prs.hxx"
#include "/Library/OCE/0.14/include/oce/PrsMgr_SequenceNodeOfPresentations.hxx"
#include "/Library/OCE/0.14/include/oce/PrsMgr_TypeOfPresentation3d.hxx"

#endif __PrsMgr_wrapper__
