// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __PS_wrapper__
#define __PS_wrapper__

#include "/Library/OCE/0.14/include/oce/PShort_FieldOfHArray1OfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/PShort_FieldOfHArray2OfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/PShort_HArray1OfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/PShort_HArray2OfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/PShort_HSequenceOfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/PShort_SeqExplorerOfHSequenceOfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/PShort_SeqNodeOfHSequenceOfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/PShort_VArrayNodeOfFieldOfHArray1OfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/PShort_VArrayNodeOfFieldOfHArray2OfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/PShort_VArrayTNodeOfFieldOfHArray1OfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/PShort_VArrayTNodeOfFieldOfHArray2OfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/PStandard_ArrayNode.hxx"

#endif __PS_wrapper__
