// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __PShort_wrapper__
#define __PShort_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_PShort_HArray1OfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PShort_HArray2OfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PShort_HSequenceOfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PShort_SeqNodeOfHSequenceOfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PShort_VArrayNodeOfFieldOfHArray1OfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PShort_VArrayNodeOfFieldOfHArray2OfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/PShort_FieldOfHArray1OfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/PShort_FieldOfHArray2OfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/PShort_HArray1OfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/PShort_HArray2OfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/PShort_HSequenceOfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/PShort_SeqExplorerOfHSequenceOfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/PShort_SeqNodeOfHSequenceOfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/PShort_VArrayNodeOfFieldOfHArray1OfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/PShort_VArrayNodeOfFieldOfHArray2OfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/PShort_VArrayTNodeOfFieldOfHArray1OfShortReal.hxx"
#include "/Library/OCE/0.14/include/oce/PShort_VArrayTNodeOfFieldOfHArray2OfShortReal.hxx"

#endif __PShort_wrapper__
