// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __PTColStd_wrapper__
#define __PTColStd_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_PTColStd_DataMapNodeOfPersistentTransientMap.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PTColStd_DataMapNodeOfTransientPersistentMap.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_PTColStd_DoubleMapNodeOfDoubleMapOfTransientPersistent.hxx"
#include "/Library/OCE/0.14/include/oce/PTColStd_DataMapIteratorOfPersistentTransientMap.hxx"
#include "/Library/OCE/0.14/include/oce/PTColStd_DataMapIteratorOfTransientPersistentMap.hxx"
#include "/Library/OCE/0.14/include/oce/PTColStd_DataMapNodeOfPersistentTransientMap.hxx"
#include "/Library/OCE/0.14/include/oce/PTColStd_DataMapNodeOfTransientPersistentMap.hxx"
#include "/Library/OCE/0.14/include/oce/PTColStd_DoubleMapIteratorOfDoubleMapOfTransientPersistent.hxx"
#include "/Library/OCE/0.14/include/oce/PTColStd_DoubleMapNodeOfDoubleMapOfTransientPersistent.hxx"
#include "/Library/OCE/0.14/include/oce/PTColStd_DoubleMapOfTransientPersistent.hxx"
#include "/Library/OCE/0.14/include/oce/PTColStd_MapPersistentHasher.hxx"
#include "/Library/OCE/0.14/include/oce/PTColStd_PersistentTransientMap.hxx"
#include "/Library/OCE/0.14/include/oce/PTColStd_TransientPersistentMap.hxx"

#endif __PTColStd_wrapper__
