// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __Resource_wrapper__
#define __Resource_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_Resource_DataMapNodeOfDataMapOfAsciiStringAsciiString.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Resource_DataMapNodeOfDataMapOfAsciiStringExtendedString.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Resource_Manager.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_Resource_NoSuchResource.hxx"
#include "/Library/OCE/0.14/include/oce/Resource_ConvertUnicode.hxx"
#include "/Library/OCE/0.14/include/oce/Resource_DataMapIteratorOfDataMapOfAsciiStringAsciiString.hxx"
#include "/Library/OCE/0.14/include/oce/Resource_DataMapIteratorOfDataMapOfAsciiStringExtendedString.hxx"
#include "/Library/OCE/0.14/include/oce/Resource_DataMapNodeOfDataMapOfAsciiStringAsciiString.hxx"
#include "/Library/OCE/0.14/include/oce/Resource_DataMapNodeOfDataMapOfAsciiStringExtendedString.hxx"
#include "/Library/OCE/0.14/include/oce/Resource_DataMapOfAsciiStringAsciiString.hxx"
#include "/Library/OCE/0.14/include/oce/Resource_DataMapOfAsciiStringExtendedString.hxx"
#include "/Library/OCE/0.14/include/oce/Resource_FormatType.hxx"
#include "/Library/OCE/0.14/include/oce/Resource_LexicalCompare.hxx"
#include "/Library/OCE/0.14/include/oce/Resource_Manager.hxx"
#include "/Library/OCE/0.14/include/oce/Resource_NoSuchResource.hxx"
#include "/Library/OCE/0.14/include/oce/Resource_QuickSortOfArray1.hxx"
#include "/Library/OCE/0.14/include/oce/Resource_Unicode.hxx"

#endif __Resource_wrapper__
