// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __RWHeaderSection_wrapper__
#define __RWHeaderSection_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_RWHeaderSection_GeneralModule.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_RWHeaderSection_ReadWriteModule.hxx"
#include "/Library/OCE/0.14/include/oce/RWHeaderSection.hxx"
#include "/Library/OCE/0.14/include/oce/RWHeaderSection_GeneralModule.hxx"
#include "/Library/OCE/0.14/include/oce/RWHeaderSection_RWFileDescription.hxx"
#include "/Library/OCE/0.14/include/oce/RWHeaderSection_RWFileName.hxx"
#include "/Library/OCE/0.14/include/oce/RWHeaderSection_RWFileSchema.hxx"
#include "/Library/OCE/0.14/include/oce/RWHeaderSection_ReadWriteModule.hxx"

#endif __RWHeaderSection_wrapper__
