// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __SGEOM_wrapper__
#define __SGEOM_wrapper__

#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/Handle_SGEOM_Application.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/Handle_SGEOM_DataMapNodeOfDataMapOfAsciiStringTransient.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/SGEOM_Application.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/SGEOM_BaseDriver.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/SGEOM_DataMapIteratorOfDataMapOfAsciiStringTransient.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/SGEOM_DataMapNodeOfDataMapOfAsciiStringTransient.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/SGEOM_DataMapOfAsciiStringTransient.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/SGEOM_Engine.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/SGEOM_Function.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/SGEOM_IOperations.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/SGEOM_ISubShape.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/SGEOM_OCCTVersion.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/SGEOM_Object.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/SGEOM_Parameter.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/SGEOM_PythonDump.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/SGEOM_Solver.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/SGEOM_SubShapeDriver.hxx"

#endif __SGEOM_wrapper__
