// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __ShapeProcessAPI_wrapper__
#define __ShapeProcessAPI_wrapper__

#include "/Library/OCE/0.14/include/oce/ShapeProcessAPI_ApplySequence.hxx"

#endif __ShapeProcessAPI_wrapper__
