// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __ShapeExtend_wrapper__
#define __ShapeExtend_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_ShapeExtend_BasicMsgRegistrator.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_ShapeExtend_ComplexCurve.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_ShapeExtend_CompositeSurface.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_ShapeExtend_DataMapNodeOfDataMapOfShapeListOfMsg.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_ShapeExtend_DataMapNodeOfDataMapOfTransientListOfMsg.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_ShapeExtend_MsgRegistrator.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_ShapeExtend_WireData.hxx"
#include "/Library/OCE/0.14/include/oce/ShapeExtend.hxx"
#include "/Library/OCE/0.14/include/oce/ShapeExtend_BasicMsgRegistrator.hxx"
#include "/Library/OCE/0.14/include/oce/ShapeExtend_ComplexCurve.hxx"
#include "/Library/OCE/0.14/include/oce/ShapeExtend_CompositeSurface.hxx"
#include "/Library/OCE/0.14/include/oce/ShapeExtend_DataMapIteratorOfDataMapOfShapeListOfMsg.hxx"
#include "/Library/OCE/0.14/include/oce/ShapeExtend_DataMapIteratorOfDataMapOfTransientListOfMsg.hxx"
#include "/Library/OCE/0.14/include/oce/ShapeExtend_DataMapNodeOfDataMapOfShapeListOfMsg.hxx"
#include "/Library/OCE/0.14/include/oce/ShapeExtend_DataMapNodeOfDataMapOfTransientListOfMsg.hxx"
#include "/Library/OCE/0.14/include/oce/ShapeExtend_DataMapOfShapeListOfMsg.hxx"
#include "/Library/OCE/0.14/include/oce/ShapeExtend_DataMapOfTransientListOfMsg.hxx"
#include "/Library/OCE/0.14/include/oce/ShapeExtend_Explorer.hxx"
#include "/Library/OCE/0.14/include/oce/ShapeExtend_MsgRegistrator.hxx"
#include "/Library/OCE/0.14/include/oce/ShapeExtend_Parametrisation.hxx"
#include "/Library/OCE/0.14/include/oce/ShapeExtend_Status.hxx"
#include "/Library/OCE/0.14/include/oce/ShapeExtend_WireData.hxx"

#endif __ShapeExtend_wrapper__
