// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __ShapeConstruct_wrapper__
#define __ShapeConstruct_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_ShapeConstruct_ProjectCurveOnSurface.hxx"
#include "/Library/OCE/0.14/include/oce/ShapeConstruct.hxx"
#include "/Library/OCE/0.14/include/oce/ShapeConstruct_CompBezierCurves2dToBSplineCurve2d.hxx"
#include "/Library/OCE/0.14/include/oce/ShapeConstruct_CompBezierCurvesToBSplineCurve.hxx"
#include "/Library/OCE/0.14/include/oce/ShapeConstruct_Curve.hxx"
#include "/Library/OCE/0.14/include/oce/ShapeConstruct_MakeTriangulation.hxx"
#include "/Library/OCE/0.14/include/oce/ShapeConstruct_ProjectCurveOnSurface.hxx"

#endif __ShapeConstruct_wrapper__
