// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __ShHealOper_wrapper__
#define __ShHealOper_wrapper__

#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/ShHealOper_ChangeOrientation.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/ShHealOper_CloseContour.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/ShHealOper_EdgeDivide.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/ShHealOper_FillHoles.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/ShHealOper_RemoveFace.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/ShHealOper_RemoveInternalWires.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/ShHealOper_Sewing.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/ShHealOper_ShapeProcess.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/ShHealOper_SplitCurve2d.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/ShHealOper_SplitCurve3d.hxx"
#include "/Users/thomas/Devel/pythonocc/src/wrapper/GEOM/include-geom-7.2.0.9-pythonocc/ShHealOper_Tool.hxx"

#endif __ShHealOper_wrapper__
