// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __SMESHDS_wrapper__
#define __SMESHDS_wrapper__

#include "/Users/thomas/Devel/pythonocc/src/contrib/smesh-5.1.2.2/inc/SMESHDS_Command.hxx"
#include "/Users/thomas/Devel/pythonocc/src/contrib/smesh-5.1.2.2/inc/SMESHDS_CommandType.hxx"
#include "/Users/thomas/Devel/pythonocc/src/contrib/smesh-5.1.2.2/inc/SMESHDS_DataMapOfShape.hxx"
#include "/Users/thomas/Devel/pythonocc/src/contrib/smesh-5.1.2.2/inc/SMESHDS_Document.hxx"
#include "/Users/thomas/Devel/pythonocc/src/contrib/smesh-5.1.2.2/inc/SMESHDS_Group.hxx"
#include "/Users/thomas/Devel/pythonocc/src/contrib/smesh-5.1.2.2/inc/SMESHDS_GroupBase.hxx"
#include "/Users/thomas/Devel/pythonocc/src/contrib/smesh-5.1.2.2/inc/SMESHDS_GroupOnGeom.hxx"
#include "/Users/thomas/Devel/pythonocc/src/contrib/smesh-5.1.2.2/inc/SMESHDS_Hypothesis.hxx"
#include "/Users/thomas/Devel/pythonocc/src/contrib/smesh-5.1.2.2/inc/SMESHDS_Mesh.hxx"
#include "/Users/thomas/Devel/pythonocc/src/contrib/smesh-5.1.2.2/inc/SMESHDS_Script.hxx"
#include "/Users/thomas/Devel/pythonocc/src/contrib/smesh-5.1.2.2/inc/SMESHDS_SubMesh.hxx"

#endif __SMESHDS_wrapper__
