// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __StdFail_wrapper__
#define __StdFail_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_StdFail_InfiniteSolutions.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_StdFail_NotDone.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_StdFail_Undefined.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_StdFail_UndefinedDerivative.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_StdFail_UndefinedValue.hxx"
#include "/Library/OCE/0.14/include/oce/StdFail_InfiniteSolutions.hxx"
#include "/Library/OCE/0.14/include/oce/StdFail_NotDone.hxx"
#include "/Library/OCE/0.14/include/oce/StdFail_Undefined.hxx"
#include "/Library/OCE/0.14/include/oce/StdFail_UndefinedDerivative.hxx"
#include "/Library/OCE/0.14/include/oce/StdFail_UndefinedValue.hxx"

#endif __StdFail_wrapper__
