// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __StdSelect_wrapper__
#define __StdSelect_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_StdSelect_BRepOwner.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_StdSelect_EdgeFilter.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_StdSelect_FaceFilter.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_StdSelect_IndexedDataMapNodeOfIndexedDataMapOfOwnerPrs.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_StdSelect_Prs.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_StdSelect_Shape.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_StdSelect_ShapeTypeFilter.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_StdSelect_ViewerSelector3d.hxx"
#include "/Library/OCE/0.14/include/oce/StdSelect.hxx"
#include "/Library/OCE/0.14/include/oce/StdSelect_BRepHilighter.hxx"
#include "/Library/OCE/0.14/include/oce/StdSelect_BRepOwner.hxx"
#include "/Library/OCE/0.14/include/oce/StdSelect_BRepSelectionTool.hxx"
#include "/Library/OCE/0.14/include/oce/StdSelect_DisplayMode.hxx"
#include "/Library/OCE/0.14/include/oce/StdSelect_EdgeFilter.hxx"
#include "/Library/OCE/0.14/include/oce/StdSelect_FaceFilter.hxx"
#include "/Library/OCE/0.14/include/oce/StdSelect_IndexedDataMapNodeOfIndexedDataMapOfOwnerPrs.hxx"
#include "/Library/OCE/0.14/include/oce/StdSelect_IndexedDataMapOfOwnerPrs.hxx"
#include "/Library/OCE/0.14/include/oce/StdSelect_Prs.hxx"
#include "/Library/OCE/0.14/include/oce/StdSelect_SensitivityMode.hxx"
#include "/Library/OCE/0.14/include/oce/StdSelect_Shape.hxx"
#include "/Library/OCE/0.14/include/oce/StdSelect_ShapeTypeFilter.hxx"
#include "/Library/OCE/0.14/include/oce/StdSelect_TypeOfEdge.hxx"
#include "/Library/OCE/0.14/include/oce/StdSelect_TypeOfFace.hxx"
#include "/Library/OCE/0.14/include/oce/StdSelect_TypeOfResult.hxx"

#endif __StdSelect_wrapper__
