// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __STEPControl_wrapper__
#define __STEPControl_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_STEPControl_ActorRead.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_STEPControl_ActorWrite.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_STEPControl_Controller.hxx"
#include "/Library/OCE/0.14/include/oce/STEPControl_ActorRead.hxx"
#include "/Library/OCE/0.14/include/oce/STEPControl_ActorWrite.hxx"
#include "/Library/OCE/0.14/include/oce/STEPControl_Controller.hxx"
#include "/Library/OCE/0.14/include/oce/STEPControl_Reader.hxx"
#include "/Library/OCE/0.14/include/oce/STEPControl_StepModelType.hxx"
#include "/Library/OCE/0.14/include/oce/STEPControl_Writer.hxx"

#endif __STEPControl_wrapper__
