// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __StepFile_wrapper__
#define __StepFile_wrapper__

#include "/Library/OCE/0.14/include/oce/StepFile_CallFailure.hxx"
#include "/Library/OCE/0.14/include/oce/StepFile_Read.hxx"
#include "/Library/OCE/0.14/include/oce/StepFile_Transfer.hxx"

#endif __StepFile_wrapper__
