// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __STEPEdit_wrapper__
#define __STEPEdit_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_STEPEdit_EditContext.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_STEPEdit_EditSDR.hxx"
#include "/Library/OCE/0.14/include/oce/STEPEdit.hxx"
#include "/Library/OCE/0.14/include/oce/STEPEdit_EditContext.hxx"
#include "/Library/OCE/0.14/include/oce/STEPEdit_EditSDR.hxx"

#endif __STEPEdit_wrapper__
