// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __TopBas_wrapper__
#define __TopBas_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_TopBas_ListNodeOfListOfTestInterference.hxx"
#include "/Library/OCE/0.14/include/oce/TopBas_ListIteratorOfListOfTestInterference.hxx"
#include "/Library/OCE/0.14/include/oce/TopBas_ListNodeOfListOfTestInterference.hxx"
#include "/Library/OCE/0.14/include/oce/TopBas_ListOfTestInterference.hxx"
#include "/Library/OCE/0.14/include/oce/TopBas_TestInterference.hxx"

#endif __TopBas_wrapper__
