// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __TopCnx_wrapper__
#define __TopCnx_wrapper__

#include "/Library/OCE/0.14/include/oce/TopCnx_EdgeFaceTransition.hxx"

#endif __TopCnx_wrapper__
