// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __TransferBRep_wrapper__
#define __TransferBRep_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_TransferBRep_BinderOfShape.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_TransferBRep_HSequenceOfTransferResultInfo.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_TransferBRep_OrientedShapeMapper.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_TransferBRep_SequenceNodeOfSequenceOfTransferResultInfo.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_TransferBRep_ShapeBinder.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_TransferBRep_ShapeListBinder.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_TransferBRep_ShapeMapper.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_TransferBRep_TransferResultInfo.hxx"
#include "/Library/OCE/0.14/include/oce/TransferBRep.hxx"
#include "/Library/OCE/0.14/include/oce/TransferBRep_BinderOfShape.hxx"
#include "/Library/OCE/0.14/include/oce/TransferBRep_HSequenceOfTransferResultInfo.hxx"
#include "/Library/OCE/0.14/include/oce/TransferBRep_OrientedShapeMapper.hxx"
#include "/Library/OCE/0.14/include/oce/TransferBRep_Reader.hxx"
#include "/Library/OCE/0.14/include/oce/TransferBRep_SequenceNodeOfSequenceOfTransferResultInfo.hxx"
#include "/Library/OCE/0.14/include/oce/TransferBRep_SequenceOfTransferResultInfo.hxx"
#include "/Library/OCE/0.14/include/oce/TransferBRep_ShapeBinder.hxx"
#include "/Library/OCE/0.14/include/oce/TransferBRep_ShapeInfo.hxx"
#include "/Library/OCE/0.14/include/oce/TransferBRep_ShapeListBinder.hxx"
#include "/Library/OCE/0.14/include/oce/TransferBRep_ShapeMapper.hxx"
#include "/Library/OCE/0.14/include/oce/TransferBRep_TransferResultInfo.hxx"

#endif __TransferBRep_wrapper__
