// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __Voxel_wrapper__
#define __Voxel_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_Voxel_Prs.hxx"
#include "/Library/OCE/0.14/include/oce/Voxel_BoolDS.hxx"
#include "/Library/OCE/0.14/include/oce/Voxel_BooleanOperation.hxx"
#include "/Library/OCE/0.14/include/oce/Voxel_CollisionDetection.hxx"
#include "/Library/OCE/0.14/include/oce/Voxel_ColorDS.hxx"
#include "/Library/OCE/0.14/include/oce/Voxel_DS.hxx"
#include "/Library/OCE/0.14/include/oce/Voxel_FastConverter.hxx"
#include "/Library/OCE/0.14/include/oce/Voxel_FloatDS.hxx"
#include "/Library/OCE/0.14/include/oce/Voxel_OctBoolDS.hxx"
#include "/Library/OCE/0.14/include/oce/Voxel_Prs.hxx"
#include "/Library/OCE/0.14/include/oce/Voxel_ROctBoolDS.hxx"
#include "/Library/OCE/0.14/include/oce/Voxel_Reader.hxx"
#include "/Library/OCE/0.14/include/oce/Voxel_Selector.hxx"
#include "/Library/OCE/0.14/include/oce/Voxel_SplitData.hxx"
#include "/Library/OCE/0.14/include/oce/Voxel_TypeDef.hxx"
#include "/Library/OCE/0.14/include/oce/Voxel_VoxelDisplayMode.hxx"
#include "/Library/OCE/0.14/include/oce/Voxel_VoxelFileFormat.hxx"
#include "/Library/OCE/0.14/include/oce/Voxel_Writer.hxx"

#endif __Voxel_wrapper__
