// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __VrmlAPI_wrapper__
#define __VrmlAPI_wrapper__

#include "/Library/OCE/0.14/include/oce/VrmlAPI.hxx"
#include "/Library/OCE/0.14/include/oce/VrmlAPI_RepresentationOfShape.hxx"
#include "/Library/OCE/0.14/include/oce/VrmlAPI_Writer.hxx"

#endif __VrmlAPI_wrapper__
