// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __VrmlConverter_wrapper__
#define __VrmlConverter_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_VrmlConverter_Drawer.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_VrmlConverter_IsoAspect.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_VrmlConverter_LineAspect.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_VrmlConverter_PointAspect.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_VrmlConverter_Projector.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_VrmlConverter_ShadingAspect.hxx"
#include "/Library/OCE/0.14/include/oce/VrmlConverter_Curve.hxx"
#include "/Library/OCE/0.14/include/oce/VrmlConverter_DeflectionCurve.hxx"
#include "/Library/OCE/0.14/include/oce/VrmlConverter_Drawer.hxx"
#include "/Library/OCE/0.14/include/oce/VrmlConverter_HLRShape.hxx"
#include "/Library/OCE/0.14/include/oce/VrmlConverter_IsoAspect.hxx"
#include "/Library/OCE/0.14/include/oce/VrmlConverter_LineAspect.hxx"
#include "/Library/OCE/0.14/include/oce/VrmlConverter_PointAspect.hxx"
#include "/Library/OCE/0.14/include/oce/VrmlConverter_Projector.hxx"
#include "/Library/OCE/0.14/include/oce/VrmlConverter_ShadedShape.hxx"
#include "/Library/OCE/0.14/include/oce/VrmlConverter_ShadingAspect.hxx"
#include "/Library/OCE/0.14/include/oce/VrmlConverter_TypeOfCamera.hxx"
#include "/Library/OCE/0.14/include/oce/VrmlConverter_TypeOfLight.hxx"
#include "/Library/OCE/0.14/include/oce/VrmlConverter_WFDeflectionRestrictedFace.hxx"
#include "/Library/OCE/0.14/include/oce/VrmlConverter_WFDeflectionShape.hxx"
#include "/Library/OCE/0.14/include/oce/VrmlConverter_WFRestrictedFace.hxx"
#include "/Library/OCE/0.14/include/oce/VrmlConverter_WFShape.hxx"

#endif __VrmlConverter_wrapper__
