// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __XmlDrivers_wrapper__
#define __XmlDrivers_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_XmlDrivers_DocumentRetrievalDriver.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_XmlDrivers_DocumentStorageDriver.hxx"
#include "/Library/OCE/0.14/include/oce/XmlDrivers.hxx"
#include "/Library/OCE/0.14/include/oce/XmlDrivers_DocumentRetrievalDriver.hxx"
#include "/Library/OCE/0.14/include/oce/XmlDrivers_DocumentStorageDriver.hxx"

#endif __XmlDrivers_wrapper__
