// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __XmlMFunction_wrapper__
#define __XmlMFunction_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_XmlMFunction_FunctionDriver.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_XmlMFunction_GraphNodeDriver.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_XmlMFunction_ScopeDriver.hxx"
#include "/Library/OCE/0.14/include/oce/XmlMFunction.hxx"
#include "/Library/OCE/0.14/include/oce/XmlMFunction_FunctionDriver.hxx"
#include "/Library/OCE/0.14/include/oce/XmlMFunction_GraphNodeDriver.hxx"
#include "/Library/OCE/0.14/include/oce/XmlMFunction_ScopeDriver.hxx"

#endif __XmlMFunction_wrapper__
