// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __XSAlgo_wrapper__
#define __XSAlgo_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_XSAlgo_AlgoContainer.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_XSAlgo_ToolContainer.hxx"
#include "/Library/OCE/0.14/include/oce/XSAlgo.hxx"
#include "/Library/OCE/0.14/include/oce/XSAlgo_AlgoContainer.hxx"
#include "/Library/OCE/0.14/include/oce/XSAlgo_Caller.hxx"
#include "/Library/OCE/0.14/include/oce/XSAlgo_ToolContainer.hxx"

#endif __XSAlgo_wrapper__
