// HXX wrapper generated by pythonOCC generate_code.py script.
#ifndef __XSControl_wrapper__
#define __XSControl_wrapper__

#include "/Library/OCE/0.14/include/oce/Handle_XSControl_ConnectedShapes.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_XSControl_Controller.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_XSControl_SelectForTransfer.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_XSControl_SignTransferStatus.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_XSControl_TransferReader.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_XSControl_TransferWriter.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_XSControl_Vars.hxx"
#include "/Library/OCE/0.14/include/oce/Handle_XSControl_WorkSession.hxx"
#include "/Library/OCE/0.14/include/oce/XSControl.hxx"
#include "/Library/OCE/0.14/include/oce/XSControl_ConnectedShapes.hxx"
#include "/Library/OCE/0.14/include/oce/XSControl_Controller.hxx"
#include "/Library/OCE/0.14/include/oce/XSControl_FuncShape.hxx"
#include "/Library/OCE/0.14/include/oce/XSControl_Functions.hxx"
#include "/Library/OCE/0.14/include/oce/XSControl_Reader.hxx"
#include "/Library/OCE/0.14/include/oce/XSControl_SelectForTransfer.hxx"
#include "/Library/OCE/0.14/include/oce/XSControl_SignTransferStatus.hxx"
#include "/Library/OCE/0.14/include/oce/XSControl_TransferReader.hxx"
#include "/Library/OCE/0.14/include/oce/XSControl_TransferWriter.hxx"
#include "/Library/OCE/0.14/include/oce/XSControl_Utils.hxx"
#include "/Library/OCE/0.14/include/oce/XSControl_Vars.hxx"
#include "/Library/OCE/0.14/include/oce/XSControl_WorkSession.hxx"
#include "/Library/OCE/0.14/include/oce/XSControl_Writer.hxx"

#endif __XSControl_wrapper__
