/*

Copyright 2008-2009 Thomas Paviot (tpaviot@gmail.com)

This file is part of pythonOCC.

pythonOCC is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

pythonOCC is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with pythonOCC.  If not, see <http://www.gnu.org/licenses/>.

*/
%{

// Headers necessary to define wrapped classes.

#include<BRep_Builder.hxx>
#include<BRep_Curve3D.hxx>
#include<BRep_CurveOn2Surfaces.hxx>
#include<BRep_CurveOnClosedSurface.hxx>
#include<BRep_CurveOnSurface.hxx>
#include<BRep_CurveRepresentation.hxx>
#include<BRep_GCurve.hxx>
#include<BRep_ListIteratorOfListOfCurveRepresentation.hxx>
#include<BRep_ListIteratorOfListOfPointRepresentation.hxx>
#include<BRep_ListNodeOfListOfCurveRepresentation.hxx>
#include<BRep_ListNodeOfListOfPointRepresentation.hxx>
#include<BRep_ListOfCurveRepresentation.hxx>
#include<BRep_ListOfPointRepresentation.hxx>
#include<BRep_PointOnCurve.hxx>
#include<BRep_PointOnCurveOnSurface.hxx>
#include<BRep_PointOnSurface.hxx>
#include<BRep_PointRepresentation.hxx>
#include<BRep_PointsOnSurface.hxx>
#include<BRep_Polygon3D.hxx>
#include<BRep_PolygonOnClosedSurface.hxx>
#include<BRep_PolygonOnClosedTriangulation.hxx>
#include<BRep_PolygonOnSurface.hxx>
#include<BRep_PolygonOnTriangulation.hxx>
#include<BRep_TEdge.hxx>
#include<BRep_TFace.hxx>
#include<BRep_TVertex.hxx>
#include<BRep_Tool.hxx>
#include<Handle_BRep_Curve3D.hxx>
#include<Handle_BRep_CurveOn2Surfaces.hxx>
#include<Handle_BRep_CurveOnClosedSurface.hxx>
#include<Handle_BRep_CurveOnSurface.hxx>
#include<Handle_BRep_CurveRepresentation.hxx>
#include<Handle_BRep_GCurve.hxx>
#include<Handle_BRep_ListNodeOfListOfCurveRepresentation.hxx>
#include<Handle_BRep_ListNodeOfListOfPointRepresentation.hxx>
#include<Handle_BRep_PointOnCurve.hxx>
#include<Handle_BRep_PointOnCurveOnSurface.hxx>
#include<Handle_BRep_PointOnSurface.hxx>
#include<Handle_BRep_PointRepresentation.hxx>
#include<Handle_BRep_PointsOnSurface.hxx>
#include<Handle_BRep_Polygon3D.hxx>
#include<Handle_BRep_PolygonOnClosedSurface.hxx>
#include<Handle_BRep_PolygonOnClosedTriangulation.hxx>
#include<Handle_BRep_PolygonOnSurface.hxx>
#include<Handle_BRep_PolygonOnTriangulation.hxx>
#include<Handle_BRep_TEdge.hxx>
#include<Handle_BRep_TFace.hxx>
#include<Handle_BRep_TVertex.hxx>

// Additional headers necessary for compilation.

#include<BRepAdaptor_Array1OfCurve.hxx>
#include<BRepAdaptor_CompCurve.hxx>
#include<BRepAdaptor_Curve.hxx>
#include<BRepAdaptor_Curve2d.hxx>
#include<BRepAdaptor_HArray1OfCurve.hxx>
#include<BRepAdaptor_HCompCurve.hxx>
#include<BRepAdaptor_HCurve.hxx>
#include<BRepAdaptor_HCurve2d.hxx>
#include<BRepAdaptor_HSurface.hxx>
#include<BRepAdaptor_Surface.hxx>
#include<BRepAlgo.hxx>
#include<BRepAlgoAPI_BooleanOperation.hxx>
#include<BRepAlgoAPI_Common.hxx>
#include<BRepAlgoAPI_Cut.hxx>
#include<BRepAlgoAPI_Fuse.hxx>
#include<BRepAlgoAPI_Section.hxx>
#include<BRepAlgo_AsDes.hxx>
#include<BRepAlgo_BooleanOperation.hxx>
#include<BRepAlgo_BooleanOperations.hxx>
#include<BRepAlgo_CheckStatus.hxx>
#include<BRepAlgo_Common.hxx>
#include<BRepAlgo_Cut.hxx>
#include<BRepAlgo_DSAccess.hxx>
#include<BRepAlgo_DataMapIteratorOfDataMapOfShapeBoolean.hxx>
#include<BRepAlgo_DataMapIteratorOfDataMapOfShapeInterference.hxx>
#include<BRepAlgo_DataMapIteratorOfDataMapOfShapeListOfInteger.hxx>
#include<BRepAlgo_DataMapNodeOfDataMapOfShapeBoolean.hxx>
#include<BRepAlgo_DataMapNodeOfDataMapOfShapeInterference.hxx>
#include<BRepAlgo_DataMapNodeOfDataMapOfShapeListOfInteger.hxx>
#include<BRepAlgo_DataMapOfShapeBoolean.hxx>
#include<BRepAlgo_DataMapOfShapeInterference.hxx>
#include<BRepAlgo_DataMapOfShapeListOfInteger.hxx>
#include<BRepAlgo_EdgeConnector.hxx>
#include<BRepAlgo_FaceRestrictor.hxx>
#include<BRepAlgo_Fuse.hxx>
#include<BRepAlgo_Image.hxx>
#include<BRepAlgo_Loop.hxx>
#include<BRepAlgo_NormalProjection.hxx>
#include<BRepAlgo_Section.hxx>
#include<BRepAlgo_SequenceNodeOfSequenceOfSequenceOfInteger.hxx>
#include<BRepAlgo_SequenceOfSequenceOfInteger.hxx>
#include<BRepAlgo_Tool.hxx>
#include<BRepAlgo_TopOpe.hxx>
#include<BRepApprox_Approx.hxx>
#include<BRepApprox_ApproxLine.hxx>
#include<BRepApprox_BSpGradient_BFGSOfMyBSplGradientOfTheComputeLineOfApprox.hxx>
#include<BRepApprox_BSpParFunctionOfMyBSplGradientOfTheComputeLineOfApprox.hxx>
#include<BRepApprox_BSpParLeastSquareOfMyBSplGradientOfTheComputeLineOfApprox.hxx>
#include<BRepApprox_Gradient_BFGSOfMyGradientOfTheComputeLineBezierOfApprox.hxx>
#include<BRepApprox_Gradient_BFGSOfMyGradientbisOfTheComputeLineOfApprox.hxx>
#include<BRepApprox_MyBSplGradientOfTheComputeLineOfApprox.hxx>
#include<BRepApprox_MyGradientOfTheComputeLineBezierOfApprox.hxx>
#include<BRepApprox_MyGradientbisOfTheComputeLineOfApprox.hxx>
#include<BRepApprox_ParFunctionOfMyGradientOfTheComputeLineBezierOfApprox.hxx>
#include<BRepApprox_ParFunctionOfMyGradientbisOfTheComputeLineOfApprox.hxx>
#include<BRepApprox_ParLeastSquareOfMyGradientOfTheComputeLineBezierOfApprox.hxx>
#include<BRepApprox_ParLeastSquareOfMyGradientbisOfTheComputeLineOfApprox.hxx>
#include<BRepApprox_ResConstraintOfMyGradientOfTheComputeLineBezierOfApprox.hxx>
#include<BRepApprox_ResConstraintOfMyGradientbisOfTheComputeLineOfApprox.hxx>
#include<BRepApprox_SurfaceTool.hxx>
#include<BRepApprox_TheComputeLineBezierOfApprox.hxx>
#include<BRepApprox_TheComputeLineOfApprox.hxx>
#include<BRepApprox_TheFunctionOfTheInt2SOfThePrmPrmSvSurfacesOfApprox.hxx>
#include<BRepApprox_TheImpPrmSvSurfacesOfApprox.hxx>
#include<BRepApprox_TheInt2SOfThePrmPrmSvSurfacesOfApprox.hxx>
#include<BRepApprox_TheMultiLineOfApprox.hxx>
#include<BRepApprox_TheMultiLineToolOfApprox.hxx>
#include<BRepApprox_ThePrmPrmSvSurfacesOfApprox.hxx>
#include<BRepApprox_TheZerImpFuncOfTheImpPrmSvSurfacesOfApprox.hxx>
#include<BRepBlend_AppFunc.hxx>
#include<BRepBlend_AppFuncRoot.hxx>
#include<BRepBlend_AppFuncRst.hxx>
#include<BRepBlend_AppFuncRstRst.hxx>
#include<BRepBlend_AppSurf.hxx>
#include<BRepBlend_AppSurface.hxx>
#include<BRepBlend_BlendTool.hxx>
#include<BRepBlend_CSCircular.hxx>
#include<BRepBlend_CSConstRad.hxx>
#include<BRepBlend_CSWalking.hxx>
#include<BRepBlend_ChAsym.hxx>
#include<BRepBlend_ChAsymInv.hxx>
#include<BRepBlend_ChamfInv.hxx>
#include<BRepBlend_Chamfer.hxx>
#include<BRepBlend_ConstRad.hxx>
#include<BRepBlend_ConstRadInv.hxx>
#include<BRepBlend_Corde.hxx>
#include<BRepBlend_CurvPointRadInv.hxx>
#include<BRepBlend_EvolRad.hxx>
#include<BRepBlend_EvolRadInv.hxx>
#include<BRepBlend_Extremity.hxx>
#include<BRepBlend_HCurve2dTool.hxx>
#include<BRepBlend_HCurveTool.hxx>
#include<BRepBlend_HSurfaceTool.hxx>
#include<BRepBlend_Line.hxx>
#include<BRepBlend_PointOnRst.hxx>
#include<BRepBlend_RstRstConstRad.hxx>
#include<BRepBlend_RstRstEvolRad.hxx>
#include<BRepBlend_RstRstLineBuilder.hxx>
#include<BRepBlend_Ruled.hxx>
#include<BRepBlend_RuledInv.hxx>
#include<BRepBlend_SequenceNodeOfSequenceOfLine.hxx>
#include<BRepBlend_SequenceNodeOfSequenceOfPointOnRst.hxx>
#include<BRepBlend_SequenceOfLine.hxx>
#include<BRepBlend_SequenceOfPointOnRst.hxx>
#include<BRepBlend_SurfCurvConstRadInv.hxx>
#include<BRepBlend_SurfCurvEvolRadInv.hxx>
#include<BRepBlend_SurfPointConstRadInv.hxx>
#include<BRepBlend_SurfPointEvolRadInv.hxx>
#include<BRepBlend_SurfRstConstRad.hxx>
#include<BRepBlend_SurfRstEvolRad.hxx>
#include<BRepBlend_SurfRstLineBuilder.hxx>
#include<BRepBlend_Walking.hxx>
#include<BRepBndLib.hxx>
#include<BRepBuilderAPI.hxx>
#include<BRepBuilderAPI_Collect.hxx>
#include<BRepBuilderAPI_Command.hxx>
#include<BRepBuilderAPI_Copy.hxx>
#include<BRepBuilderAPI_EdgeError.hxx>
#include<BRepBuilderAPI_FaceError.hxx>
#include<BRepBuilderAPI_FindPlane.hxx>
#include<BRepBuilderAPI_GTransform.hxx>
#include<BRepBuilderAPI_MakeEdge.hxx>
#include<BRepBuilderAPI_MakeEdge2d.hxx>
#include<BRepBuilderAPI_MakeFace.hxx>
#include<BRepBuilderAPI_MakePolygon.hxx>
#include<BRepBuilderAPI_MakeShape.hxx>
#include<BRepBuilderAPI_MakeShell.hxx>
#include<BRepBuilderAPI_MakeSolid.hxx>
#include<BRepBuilderAPI_MakeVertex.hxx>
#include<BRepBuilderAPI_MakeWire.hxx>
#include<BRepBuilderAPI_ModifyShape.hxx>
#include<BRepBuilderAPI_NurbsConvert.hxx>
#include<BRepBuilderAPI_PipeError.hxx>
#include<BRepBuilderAPI_Sewing.hxx>
#include<BRepBuilderAPI_ShapeModification.hxx>
#include<BRepBuilderAPI_ShellError.hxx>
#include<BRepBuilderAPI_Transform.hxx>
#include<BRepBuilderAPI_TransitionMode.hxx>
#include<BRepBuilderAPI_WireError.hxx>
#include<BRepCheck.hxx>
#include<BRepCheck_Analyzer.hxx>
#include<BRepCheck_DataMapIteratorOfDataMapOfShapeListOfStatus.hxx>
#include<BRepCheck_DataMapIteratorOfDataMapOfShapeResult.hxx>
#include<BRepCheck_DataMapNodeOfDataMapOfShapeListOfStatus.hxx>
#include<BRepCheck_DataMapNodeOfDataMapOfShapeResult.hxx>
#include<BRepCheck_DataMapOfShapeListOfStatus.hxx>
#include<BRepCheck_DataMapOfShapeResult.hxx>
#include<BRepCheck_Edge.hxx>
#include<BRepCheck_Face.hxx>
#include<BRepCheck_ListIteratorOfListOfStatus.hxx>
#include<BRepCheck_ListNodeOfListOfStatus.hxx>
#include<BRepCheck_ListOfStatus.hxx>
#include<BRepCheck_Result.hxx>
#include<BRepCheck_Shell.hxx>
#include<BRepCheck_Status.hxx>
#include<BRepCheck_Vertex.hxx>
#include<BRepCheck_Wire.hxx>
#include<BRepClass3d_DataMapIteratorOfMapOfInter.hxx>
#include<BRepClass3d_DataMapNodeOfMapOfInter.hxx>
#include<BRepClass3d_Intersector3d.hxx>
#include<BRepClass3d_MapOfInter.hxx>
#include<BRepClass3d_SClassifier.hxx>
#include<BRepClass3d_SolidClassifier.hxx>
#include<BRepClass3d_SolidExplorer.hxx>
#include<BRepClass3d_SolidPassiveClassifier.hxx>
#include<BRepClass_Edge.hxx>
#include<BRepClass_FClass2dOfFClassifier.hxx>
#include<BRepClass_FClassifier.hxx>
#include<BRepClass_FaceClassifier.hxx>
#include<BRepClass_FaceExplorer.hxx>
#include<BRepClass_FacePassiveClassifier.hxx>
#include<BRepClass_Intersector.hxx>
#include<BRepExtrema_DistShapeShape.hxx>
#include<BRepExtrema_DistanceSS.hxx>
#include<BRepExtrema_ExtCC.hxx>
#include<BRepExtrema_ExtCF.hxx>
#include<BRepExtrema_ExtFF.hxx>
#include<BRepExtrema_ExtPC.hxx>
#include<BRepExtrema_ExtPF.hxx>
#include<BRepExtrema_Poly.hxx>
#include<BRepExtrema_SeqOfSolution.hxx>
#include<BRepExtrema_SequenceNodeOfSeqOfSolution.hxx>
#include<BRepExtrema_SolutionElem.hxx>
#include<BRepExtrema_SupportType.hxx>
#include<BRepExtrema_UnCompatibleShape.hxx>
#include<BRepFeat.hxx>
#include<BRepFeat_Builder.hxx>
#include<BRepFeat_Form.hxx>
#include<BRepFeat_Gluer.hxx>
#include<BRepFeat_LocalOperation.hxx>
#include<BRepFeat_MakeCylindricalHole.hxx>
#include<BRepFeat_MakeDPrism.hxx>
#include<BRepFeat_MakeLinearForm.hxx>
#include<BRepFeat_MakePipe.hxx>
#include<BRepFeat_MakePrism.hxx>
#include<BRepFeat_MakeRevol.hxx>
#include<BRepFeat_MakeRevolutionForm.hxx>
#include<BRepFeat_PerfSelection.hxx>
#include<BRepFeat_RibSlot.hxx>
#include<BRepFeat_SplitShape.hxx>
#include<BRepFeat_Status.hxx>
#include<BRepFeat_StatusError.hxx>
#include<BRepFill.hxx>
#include<BRepFill_ACRLaw.hxx>
#include<BRepFill_ApproxSeewing.hxx>
#include<BRepFill_CompatibleWires.hxx>
#include<BRepFill_ComputeCLine.hxx>
#include<BRepFill_CurveConstraint.hxx>
#include<BRepFill_DataMapIteratorOfDataMapOfNodeDataMapOfShapeShape.hxx>
#include<BRepFill_DataMapIteratorOfDataMapOfNodeShape.hxx>
#include<BRepFill_DataMapIteratorOfDataMapOfOrientedShapeListOfShape.hxx>
#include<BRepFill_DataMapIteratorOfDataMapOfShapeDataMapOfShapeListOfShape.hxx>
#include<BRepFill_DataMapIteratorOfDataMapOfShapeSequenceOfPnt.hxx>
#include<BRepFill_DataMapIteratorOfDataMapOfShapeSequenceOfReal.hxx>
#include<BRepFill_DataMapIteratorOfDataMapOfShapeSequenceOfShape.hxx>
#include<BRepFill_DataMapNodeOfDataMapOfNodeDataMapOfShapeShape.hxx>
#include<BRepFill_DataMapNodeOfDataMapOfNodeShape.hxx>
#include<BRepFill_DataMapNodeOfDataMapOfOrientedShapeListOfShape.hxx>
#include<BRepFill_DataMapNodeOfDataMapOfShapeDataMapOfShapeListOfShape.hxx>
#include<BRepFill_DataMapNodeOfDataMapOfShapeSequenceOfPnt.hxx>
#include<BRepFill_DataMapNodeOfDataMapOfShapeSequenceOfReal.hxx>
#include<BRepFill_DataMapNodeOfDataMapOfShapeSequenceOfShape.hxx>
#include<BRepFill_DataMapOfNodeDataMapOfShapeShape.hxx>
#include<BRepFill_DataMapOfNodeShape.hxx>
#include<BRepFill_DataMapOfOrientedShapeListOfShape.hxx>
#include<BRepFill_DataMapOfShapeDataMapOfShapeListOfShape.hxx>
#include<BRepFill_DataMapOfShapeSequenceOfPnt.hxx>
#include<BRepFill_DataMapOfShapeSequenceOfReal.hxx>
#include<BRepFill_DataMapOfShapeSequenceOfShape.hxx>
#include<BRepFill_Draft.hxx>
#include<BRepFill_DraftLaw.hxx>
#include<BRepFill_Edge3DLaw.hxx>
#include<BRepFill_EdgeFaceAndOrder.hxx>
#include<BRepFill_EdgeOnSurfLaw.hxx>
#include<BRepFill_Evolved.hxx>
#include<BRepFill_FaceAndOrder.hxx>
#include<BRepFill_Filling.hxx>
#include<BRepFill_Generator.hxx>
#include<BRepFill_ListIteratorOfListOfOffsetWire.hxx>
#include<BRepFill_ListNodeOfListOfOffsetWire.hxx>
#include<BRepFill_ListOfOffsetWire.hxx>
#include<BRepFill_LocationLaw.hxx>
#include<BRepFill_MultiLine.hxx>
#include<BRepFill_MultiLineTool.hxx>
#include<BRepFill_MyLeastSquareOfComputeCLine.hxx>
#include<BRepFill_NSections.hxx>
#include<BRepFill_OffsetAncestors.hxx>
#include<BRepFill_OffsetWire.hxx>
#include<BRepFill_Pipe.hxx>
#include<BRepFill_PipeShell.hxx>
#include<BRepFill_Section.hxx>
#include<BRepFill_SectionLaw.hxx>
#include<BRepFill_SectionPlacement.hxx>
#include<BRepFill_SequenceNodeOfSequenceOfEdgeFaceAndOrder.hxx>
#include<BRepFill_SequenceNodeOfSequenceOfFaceAndOrder.hxx>
#include<BRepFill_SequenceNodeOfSequenceOfSection.hxx>
#include<BRepFill_SequenceOfEdgeFaceAndOrder.hxx>
#include<BRepFill_SequenceOfFaceAndOrder.hxx>
#include<BRepFill_SequenceOfSection.hxx>
#include<BRepFill_ShapeLaw.hxx>
#include<BRepFill_Sweep.hxx>
#include<BRepFill_TransitionStyle.hxx>
#include<BRepFill_TrimEdgeTool.hxx>
#include<BRepFill_TrimShellCorner.hxx>
#include<BRepFill_TrimSurfaceTool.hxx>
#include<BRepFilletAPI_LocalOperation.hxx>
#include<BRepFilletAPI_MakeChamfer.hxx>
#include<BRepFilletAPI_MakeFillet.hxx>
#include<BRepFilletAPI_MakeFillet2d.hxx>
#include<BRepGProp.hxx>
#include<BRepGProp_Cinert.hxx>
#include<BRepGProp_Domain.hxx>
#include<BRepGProp_EdgeTool.hxx>
#include<BRepGProp_Face.hxx>
#include<BRepGProp_Sinert.hxx>
#include<BRepGProp_TFunctionOfVinertGK.hxx>
#include<BRepGProp_UFunctionOfVinertGK.hxx>
#include<BRepGProp_Vinert.hxx>
#include<BRepGProp_VinertGK.hxx>
#include<BRepIntCurveSurface_Inter.hxx>
#include<BRepLProp.hxx>
#include<BRepLProp_CLProps.hxx>
#include<BRepLProp_CurveTool.hxx>
#include<BRepLProp_SLProps.hxx>
#include<BRepLProp_SurfaceTool.hxx>
#include<BRepLib.hxx>
#include<BRepLib_Command.hxx>
#include<BRepLib_EdgeError.hxx>
#include<BRepLib_FaceError.hxx>
#include<BRepLib_FindSurface.hxx>
#include<BRepLib_FuseEdges.hxx>
#include<BRepLib_MakeEdge.hxx>
#include<BRepLib_MakeEdge2d.hxx>
#include<BRepLib_MakeFace.hxx>
#include<BRepLib_MakePolygon.hxx>
#include<BRepLib_MakeShape.hxx>
#include<BRepLib_MakeShell.hxx>
#include<BRepLib_MakeSolid.hxx>
#include<BRepLib_MakeVertex.hxx>
#include<BRepLib_MakeWire.hxx>
#include<BRepLib_ShapeModification.hxx>
#include<BRepLib_ShellError.hxx>
#include<BRepLib_WireError.hxx>
#include<BRepMAT2d_BisectingLocus.hxx>
#include<BRepMAT2d_DataMapIteratorOfDataMapOfBasicEltShape.hxx>
#include<BRepMAT2d_DataMapIteratorOfDataMapOfShapeSequenceOfBasicElt.hxx>
#include<BRepMAT2d_DataMapNodeOfDataMapOfBasicEltShape.hxx>
#include<BRepMAT2d_DataMapNodeOfDataMapOfShapeSequenceOfBasicElt.hxx>
#include<BRepMAT2d_DataMapOfBasicEltShape.hxx>
#include<BRepMAT2d_DataMapOfShapeSequenceOfBasicElt.hxx>
#include<BRepMAT2d_Explorer.hxx>
#include<BRepMAT2d_LinkTopoBilo.hxx>
#include<BRepMAT2d_SequenceNodeOfSequenceOfBasicElt.hxx>
#include<BRepMAT2d_SequenceOfBasicElt.hxx>
#include<BRepMesh.hxx>
#include<BRepMesh_Array1OfBiPoint.hxx>
#include<BRepMesh_Array1OfVertexOfDelaun.hxx>
#include<BRepMesh_BiPoint.hxx>
#include<BRepMesh_Classifier.hxx>
#include<BRepMesh_ComparatorOfIndexedVertexOfDelaun.hxx>
#include<BRepMesh_ComparatorOfVertexOfDelaun.hxx>
#include<BRepMesh_DataMapIteratorOfDataMapOfCouplePnt.hxx>
#include<BRepMesh_DataMapIteratorOfDataMapOfIntegerFace.hxx>
#include<BRepMesh_DataMapIteratorOfDataMapOfIntegerListOfXY.hxx>
#include<BRepMesh_DataMapIteratorOfDataMapOfMeshVertexInteger.hxx>
#include<BRepMesh_DataMapIteratorOfDataMapOfShapeEdgeDiscret.hxx>
#include<BRepMesh_DataMapIteratorOfDataMapOfShapeReal.hxx>
#include<BRepMesh_DataMapIteratorOfDataMapOfShapeSurfaceGrid.hxx>
#include<BRepMesh_DataMapIteratorOfDataMapOfVertexInteger.hxx>
#include<BRepMesh_DataMapNodeOfDataMapOfCouplePnt.hxx>
#include<BRepMesh_DataMapNodeOfDataMapOfIntegerFace.hxx>
#include<BRepMesh_DataMapNodeOfDataMapOfIntegerListOfXY.hxx>
#include<BRepMesh_DataMapNodeOfDataMapOfMeshVertexInteger.hxx>
#include<BRepMesh_DataMapNodeOfDataMapOfShapeEdgeDiscret.hxx>
#include<BRepMesh_DataMapNodeOfDataMapOfShapeReal.hxx>
#include<BRepMesh_DataMapNodeOfDataMapOfShapeSurfaceGrid.hxx>
#include<BRepMesh_DataMapNodeOfDataMapOfVertexInteger.hxx>
#include<BRepMesh_DataMapOfCouplePnt.hxx>
#include<BRepMesh_DataMapOfIntegerFace.hxx>
#include<BRepMesh_DataMapOfIntegerListOfXY.hxx>
#include<BRepMesh_DataMapOfMeshVertexInteger.hxx>
#include<BRepMesh_DataMapOfShapeEdgeDiscret.hxx>
#include<BRepMesh_DataMapOfShapeReal.hxx>
#include<BRepMesh_DataMapOfShapeSurfaceGrid.hxx>
#include<BRepMesh_DataMapOfVertexInteger.hxx>
#include<BRepMesh_DataStructureOfDelaun.hxx>
#include<BRepMesh_Delaun.hxx>
#include<BRepMesh_DiscretFactory.hxx>
#include<BRepMesh_DiscretRoot.hxx>
#include<BRepMesh_Edge.hxx>
#include<BRepMesh_EdgeDiscret.hxx>
#include<BRepMesh_ElemHasherOfDataStructureOfDelaun.hxx>
#include<BRepMesh_FactoryError.hxx>
#include<BRepMesh_FastDiscret.hxx>
#include<BRepMesh_GeomTool.hxx>
#include<BRepMesh_HArray1OfVertexOfDelaun.hxx>
#include<BRepMesh_HeapSortIndexedVertexOfDelaun.hxx>
#include<BRepMesh_HeapSortVertexOfDelaun.hxx>
#include<BRepMesh_IDMapOfLinkOfDataStructureOfDelaun.hxx>
#include<BRepMesh_IDMapOfNodeOfDataStructureOfDelaun.hxx>
#include<BRepMesh_IMapOfElementOfDataStructureOfDelaun.hxx>
#include<BRepMesh_IncrementalMesh.hxx>
#include<BRepMesh_IndexedDataMapNodeOfIDMapOfLinkOfDataStructureOfDelaun.hxx>
#include<BRepMesh_IndexedDataMapNodeOfIDMapOfNodeOfDataStructureOfDelaun.hxx>
#include<BRepMesh_IndexedMapNodeOfIMapOfElementOfDataStructureOfDelaun.hxx>
#include<BRepMesh_IndexedMapNodeOfIndexedMapOfVertex.hxx>
#include<BRepMesh_IndexedMapOfVertex.hxx>
#include<BRepMesh_LinkHasherOfDataStructureOfDelaun.hxx>
#include<BRepMesh_ListIteratorOfListOfSurfaceGrid.hxx>
#include<BRepMesh_ListIteratorOfListOfVertex.hxx>
#include<BRepMesh_ListIteratorOfListOfXY.hxx>
#include<BRepMesh_ListNodeOfListOfSurfaceGrid.hxx>
#include<BRepMesh_ListNodeOfListOfVertex.hxx>
#include<BRepMesh_ListNodeOfListOfXY.hxx>
#include<BRepMesh_ListOfSurfaceGrid.hxx>
#include<BRepMesh_ListOfVertex.hxx>
#include<BRepMesh_ListOfXY.hxx>
#include<BRepMesh_MapIteratorOfMapOfAsciiString.hxx>
#include<BRepMesh_MapOfAsciiString.hxx>
#include<BRepMesh_NodeHasherOfDataStructureOfDelaun.hxx>
#include<BRepMesh_PDiscretRoot.hxx>
#include<BRepMesh_PluginMacro.hxx>
#include<BRepMesh_SelectorOfDataStructureOfDelaun.hxx>
#include<BRepMesh_ShapeTool.hxx>
#include<BRepMesh_Status.hxx>
#include<BRepMesh_StdMapNodeOfMapOfAsciiString.hxx>
#include<BRepMesh_SurfaceGrid.hxx>
#include<BRepMesh_Triangle.hxx>
#include<BRepMesh_Vertex.hxx>
#include<BRepMesh_VertexHasher.hxx>
#include<BRepOffset.hxx>
#include<BRepOffsetAPI_DataMapIteratorOfDataMapOfShapeSequenceOfShape.hxx>
#include<BRepOffsetAPI_DataMapNodeOfDataMapOfShapeSequenceOfShape.hxx>
#include<BRepOffsetAPI_DataMapOfShapeSequenceOfShape.hxx>
#include<BRepOffsetAPI_DraftAngle.hxx>
#include<BRepOffsetAPI_FindContigousEdges.hxx>
#include<BRepOffsetAPI_MakeDraft.hxx>
#include<BRepOffsetAPI_MakeEvolved.hxx>
#include<BRepOffsetAPI_MakeFilling.hxx>
#include<BRepOffsetAPI_MakeOffset.hxx>
#include<BRepOffsetAPI_MakeOffsetShape.hxx>
#include<BRepOffsetAPI_MakePipe.hxx>
#include<BRepOffsetAPI_MakePipeShell.hxx>
#include<BRepOffsetAPI_MakeThickSolid.hxx>
#include<BRepOffsetAPI_NormalProjection.hxx>
#include<BRepOffsetAPI_SequenceNodeOfSequenceOfSequenceOfReal.hxx>
#include<BRepOffsetAPI_SequenceNodeOfSequenceOfSequenceOfShape.hxx>
#include<BRepOffsetAPI_SequenceOfSequenceOfReal.hxx>
#include<BRepOffsetAPI_SequenceOfSequenceOfShape.hxx>
#include<BRepOffsetAPI_Sewing.hxx>
#include<BRepOffsetAPI_ThruSections.hxx>
#include<BRepOffset_Analyse.hxx>
#include<BRepOffset_DataMapIteratorOfDataMapOfShapeListOfInterval.hxx>
#include<BRepOffset_DataMapIteratorOfDataMapOfShapeMapOfShape.hxx>
#include<BRepOffset_DataMapIteratorOfDataMapOfShapeOffset.hxx>
#include<BRepOffset_DataMapIteratorOfDataMapOfShapeReal.hxx>
#include<BRepOffset_DataMapNodeOfDataMapOfShapeListOfInterval.hxx>
#include<BRepOffset_DataMapNodeOfDataMapOfShapeMapOfShape.hxx>
#include<BRepOffset_DataMapNodeOfDataMapOfShapeOffset.hxx>
#include<BRepOffset_DataMapNodeOfDataMapOfShapeReal.hxx>
#include<BRepOffset_DataMapOfShapeListOfInterval.hxx>
#include<BRepOffset_DataMapOfShapeMapOfShape.hxx>
#include<BRepOffset_DataMapOfShapeOffset.hxx>
#include<BRepOffset_DataMapOfShapeReal.hxx>
#include<BRepOffset_Error.hxx>
#include<BRepOffset_Inter2d.hxx>
#include<BRepOffset_Inter3d.hxx>
#include<BRepOffset_Interval.hxx>
#include<BRepOffset_ListIteratorOfListOfInterval.hxx>
#include<BRepOffset_ListNodeOfListOfInterval.hxx>
#include<BRepOffset_ListOfInterval.hxx>
#include<BRepOffset_MakeLoops.hxx>
#include<BRepOffset_MakeOffset.hxx>
#include<BRepOffset_Mode.hxx>
#include<BRepOffset_Offset.hxx>
#include<BRepOffset_Status.hxx>
#include<BRepOffset_Tool.hxx>
#include<BRepOffset_Type.hxx>
#include<BRepPrimAPI_MakeBox.hxx>
#include<BRepPrimAPI_MakeCone.hxx>
#include<BRepPrimAPI_MakeCylinder.hxx>
#include<BRepPrimAPI_MakeHalfSpace.hxx>
#include<BRepPrimAPI_MakeOneAxis.hxx>
#include<BRepPrimAPI_MakePrism.hxx>
#include<BRepPrimAPI_MakeRevol.hxx>
#include<BRepPrimAPI_MakeRevolution.hxx>
#include<BRepPrimAPI_MakeSphere.hxx>
#include<BRepPrimAPI_MakeSweep.hxx>
#include<BRepPrimAPI_MakeTorus.hxx>
#include<BRepPrimAPI_MakeWedge.hxx>
#include<BRepPrim_Builder.hxx>
#include<BRepPrim_Cone.hxx>
#include<BRepPrim_Cylinder.hxx>
#include<BRepPrim_FaceBuilder.hxx>
#include<BRepPrim_GWedge.hxx>
#include<BRepPrim_OneAxis.hxx>
#include<BRepPrim_Revolution.hxx>
#include<BRepPrim_Sphere.hxx>
#include<BRepPrim_Torus.hxx>
#include<BRepPrim_Wedge.hxx>
#include<BRepProj_Projection.hxx>
#include<BRepSweep_Array2OfShapesOfNumLinearRegularSweep.hxx>
#include<BRepSweep_Builder.hxx>
#include<BRepSweep_Iterator.hxx>
#include<BRepSweep_NumLinearRegularSweep.hxx>
#include<BRepSweep_Prism.hxx>
#include<BRepSweep_Revol.hxx>
#include<BRepSweep_Rotation.hxx>
#include<BRepSweep_SequenceNodeOfSequenceOfShapesOfNumLinearRegularSweep.hxx>
#include<BRepSweep_SequenceOfShapesOfNumLinearRegularSweep.hxx>
#include<BRepSweep_Tool.hxx>
#include<BRepSweep_Translation.hxx>
#include<BRepSweep_Trsf.hxx>
#include<BRepToIGESBRep_Entity.hxx>
#include<BRepToIGES_BREntity.hxx>
#include<BRepToIGES_BRShell.hxx>
#include<BRepToIGES_BRSolid.hxx>
#include<BRepToIGES_BRWire.hxx>
#include<BRepTools.hxx>
#include<BRepTools_DataMapIteratorOfMapOfVertexPnt2d.hxx>
#include<BRepTools_DataMapNodeOfMapOfVertexPnt2d.hxx>
#include<BRepTools_GTrsfModification.hxx>
#include<BRepTools_MapOfVertexPnt2d.hxx>
#include<BRepTools_Modification.hxx>
#include<BRepTools_Modifier.hxx>
#include<BRepTools_NurbsConvertModification.hxx>
#include<BRepTools_Quilt.hxx>
#include<BRepTools_ReShape.hxx>
#include<BRepTools_ShapeSet.hxx>
#include<BRepTools_Substitution.hxx>
#include<BRepTools_TrsfModification.hxx>
#include<BRepTools_WireExplorer.hxx>
#include<BRepTopAdaptor_DataMapIteratorOfMapOfShapeTool.hxx>
#include<BRepTopAdaptor_DataMapNodeOfMapOfShapeTool.hxx>
#include<BRepTopAdaptor_FClass2d.hxx>
#include<BRepTopAdaptor_HVertex.hxx>
#include<BRepTopAdaptor_MapOfShapeTool.hxx>
#include<BRepTopAdaptor_SeqOfPtr.hxx>
#include<BRepTopAdaptor_SequenceNodeOfSeqOfPtr.hxx>
#include<BRepTopAdaptor_Tool.hxx>
#include<BRepTopAdaptor_TopolTool.hxx>

// Needed headers necessary for compilation.

#include<Handle_Standard_Transient.hxx>
#include<Handle_Geom_Curve.hxx>
#include<TopLoc_Location.hxx>
#include<Handle_Geom2d_Curve.hxx>
#include<Handle_Geom_Surface.hxx>
#include<Handle_Poly_Triangulation.hxx>
#include<Handle_Poly_Polygon3D.hxx>
#include<Handle_Poly_Polygon2D.hxx>
#include<Handle_Poly_PolygonOnTriangulation.hxx>
#include<gp_Pnt.hxx>
#include<gp_Pnt2d.hxx>
#include<TopoDS_Shape.hxx>
#include<TopoDS_Face.hxx>
#include<TopoDS_Edge.hxx>
#include<TopoDS_Vertex.hxx>
#include<Handle_TopoDS_TShape.hxx>
%}
