%rename(TColQuantity_Array1OfLength) TColQuantity_Array1OfLength;
%rename(TColQuantity_Array2OfLength) TColQuantity_Array2OfLength;
%rename(TColQuantity_HArray2OfLength) TColQuantity_HArray2OfLength;
%rename(TColQuantity_HArray1OfLength) TColQuantity_HArray1OfLength;
%rename(Handle_TColQuantity_HArray2OfLength) Handle_TColQuantity_HArray2OfLength;
%rename(Handle_TColQuantity_HArray1OfLength) Handle_TColQuantity_HArray1OfLength;
