%rename(BRepGProp_Face) BRepGProp_Face;
%rename(BRepGProp_Cinert) BRepGProp_Cinert;
%rename(BRepGProp_Domain) BRepGProp_Domain;
%rename(BRepGProp) BRepGProp;
%rename(BRepGProp_EdgeTool) BRepGProp_EdgeTool;
%rename(BRepGProp_Sinert) BRepGProp_Sinert;
%rename(BRepGProp_TFunctionOfVinertGK) BRepGProp_TFunctionOfVinertGK;
%rename(BRepGProp_UFunctionOfVinertGK) BRepGProp_UFunctionOfVinertGK;
%rename(BRepGProp_Vinert) BRepGProp_Vinert;
