%rename(Handle_DNaming_DataMapNodeOfDataMapOfShapeOfName) Handle_DNaming_DataMapNodeOfDataMapOfShapeOfName;
%rename(DNaming_DataMapNodeOfDataMapOfShapeOfName) DNaming_DataMapNodeOfDataMapOfShapeOfName;
%rename(DNaming_DataMapOfShapeOfName) DNaming_DataMapOfShapeOfName;
%rename(DNaming_DataMapIteratorOfDataMapOfShapeOfName) DNaming_DataMapIteratorOfDataMapOfShapeOfName;
%rename(DNaming) DNaming;
