%rename(BinObjMgt_Persistent) BinObjMgt_Persistent;
%rename(Handle_BinObjMgt_SequenceNodeOfSequenceOfAddress) Handle_BinObjMgt_SequenceNodeOfSequenceOfAddress;
%rename(BinObjMgt_DataMapIteratorOfRRelocationTable) BinObjMgt_DataMapIteratorOfRRelocationTable;
%rename(BinObjMgt_SequenceOfAddress) BinObjMgt_SequenceOfAddress;
%rename(BinObjMgt_SequenceNodeOfSequenceOfAddress) BinObjMgt_SequenceNodeOfSequenceOfAddress;
%rename(BinObjMgt_RRelocationTable) BinObjMgt_RRelocationTable;
%rename(Handle_BinObjMgt_DataMapNodeOfRRelocationTable) Handle_BinObjMgt_DataMapNodeOfRRelocationTable;
%rename(BinObjMgt_DataMapNodeOfRRelocationTable) BinObjMgt_DataMapNodeOfRRelocationTable;
