%rename(BinXCAFDrivers) BinXCAFDrivers;
%rename(DocumentRetrievalDriver) BinXCAFDrivers_DocumentRetrievalDriver;
%rename(Handle_DocumentRetrievalDriver) Handle_BinXCAFDrivers_DocumentRetrievalDriver;
%rename(DocumentStorageDriver) BinXCAFDrivers_DocumentStorageDriver;
%rename(Handle_DocumentStorageDriver) Handle_BinXCAFDrivers_DocumentStorageDriver;
