%rename(ApproxSurface) GeomConvert_ApproxSurface;
%rename(CompCurveToBSplineCurve) GeomConvert_CompCurveToBSplineCurve;
%rename(ApproxCurve) GeomConvert_ApproxCurve;
%rename(BSplineCurveToBezierCurve) GeomConvert_BSplineCurveToBezierCurve;
%rename(BSplineSurfaceKnotSplitting) GeomConvert_BSplineSurfaceKnotSplitting;
%rename(BSplineSurfaceToBezierSurface) GeomConvert_BSplineSurfaceToBezierSurface;
%rename(CompBezierSurfacesToBSplineSurface) GeomConvert_CompBezierSurfacesToBSplineSurface;
%rename(BSplineCurveKnotSplitting) GeomConvert_BSplineCurveKnotSplitting;
%rename(GeomConvert) GeomConvert;
