%rename(Handle_MeshAlgo_DataMapNodeOfDataMapOfIntegerCirc) Handle_MeshAlgo_DataMapNodeOfDataMapOfIntegerCirc;
%rename(MeshAlgo_DataMapOfIntegerCirc) MeshAlgo_DataMapOfIntegerCirc;
%rename(MeshAlgo) MeshAlgo;
%rename(MeshAlgo_CircleTool) MeshAlgo_CircleTool;
%rename(MeshAlgo_DataMapIteratorOfDataMapOfIntegerCirc) MeshAlgo_DataMapIteratorOfDataMapOfIntegerCirc;
%rename(MeshAlgo_DataMapNodeOfDataMapOfIntegerCirc) MeshAlgo_DataMapNodeOfDataMapOfIntegerCirc;
%rename(MeshAlgo_Circ) MeshAlgo_Circ;
