%rename(StdDrivers_DocumentRetrievalDriver) StdDrivers_DocumentRetrievalDriver;
%rename(StdDrivers) StdDrivers;
%rename(Handle_StdDrivers_DocumentStorageDriver) Handle_StdDrivers_DocumentStorageDriver;
%rename(StdDrivers_DocumentStorageDriver) StdDrivers_DocumentStorageDriver;
%rename(Handle_StdDrivers_DocumentRetrievalDriver) Handle_StdDrivers_DocumentRetrievalDriver;
