%rename(LocalAnalysis_NullSecondDerivative) LocalAnalysis_NullSecondDerivative;
%rename(LocalAnalysis_TangentNotDefined) LocalAnalysis_TangentNotDefined;
%rename(LocalAnalysis) LocalAnalysis;
%rename(LocalAnalysis_CurveContinuity) LocalAnalysis_CurveContinuity;
%rename(LocalAnalysis_NullFirstDerivative) LocalAnalysis_NullFirstDerivative;
%rename(LocalAnalysis_SurfaceContinuity) LocalAnalysis_SurfaceContinuity;
%rename(LocalAnalysis_CurvatureNotDefined) LocalAnalysis_CurvatureNotDefined;
%rename(LocalAnalysis_NormalNotDefined) LocalAnalysis_NormalNotDefined;
