%rename(Handle_XCAFDrivers_DocumentRetrievalDriver) Handle_XCAFDrivers_DocumentRetrievalDriver;
%rename(XCAFDrivers_DocumentRetrievalDriver) XCAFDrivers_DocumentRetrievalDriver;
%rename(XCAFDrivers_DocumentStorageDriver) XCAFDrivers_DocumentStorageDriver;
%rename(XCAFDrivers) XCAFDrivers;
%rename(Handle_XCAFDrivers_DocumentStorageDriver) Handle_XCAFDrivers_DocumentStorageDriver;
