%rename(BinMPrsStd) BinMPrsStd;
%rename(Handle_BinMPrsStd_AISPresentationDriver) Handle_BinMPrsStd_AISPresentationDriver;
%rename(BinMPrsStd_PositionDriver) BinMPrsStd_PositionDriver;
%rename(BinMPrsStd_AISPresentationDriver) BinMPrsStd_AISPresentationDriver;
%rename(Handle_BinMPrsStd_PositionDriver) Handle_BinMPrsStd_PositionDriver;
