%rename(Handle_BinMFunction_FunctionDriver) Handle_BinMFunction_FunctionDriver;
%rename(BinMFunction) BinMFunction;
%rename(Handle_BinMFunction_GraphNodeDriver) Handle_BinMFunction_GraphNodeDriver;
%rename(BinMFunction_FunctionDriver) BinMFunction_FunctionDriver;
%rename(Handle_BinMFunction_ScopeDriver) Handle_BinMFunction_ScopeDriver;
%rename(BinMFunction_GraphNodeDriver) BinMFunction_GraphNodeDriver;
%rename(BinMFunction_ScopeDriver) BinMFunction_ScopeDriver;
