%rename(Geom2dToIGES_Geom2dEntity) Geom2dToIGES_Geom2dEntity;
%rename(Geom2dToIGES_Geom2dPoint) Geom2dToIGES_Geom2dPoint;
%rename(Geom2dToIGES_Geom2dVector) Geom2dToIGES_Geom2dVector;
%rename(Geom2dToIGES_Geom2dCurve) Geom2dToIGES_Geom2dCurve;
