%rename(IntCurve_MyImpParToolOfIntImpConicParConic) IntCurve_MyImpParToolOfIntImpConicParConic;
%rename(IntCurve_IntConicConic) IntCurve_IntConicConic;
%rename(IntCurve_IntImpConicParConic) IntCurve_IntImpConicParConic;
%rename(IntCurve_PConicTool) IntCurve_PConicTool;
%rename(IntCurve_ProjectOnPConicTool) IntCurve_ProjectOnPConicTool;
%rename(IntCurve_PConic) IntCurve_PConic;
%rename(IntCurve_IConicTool) IntCurve_IConicTool;
