%rename(CircleTool) MeshAlgo_CircleTool;
%rename(DataMapNodeOfDataMapOfIntegerCirc) MeshAlgo_DataMapNodeOfDataMapOfIntegerCirc;
%rename(DataMapOfIntegerCirc) MeshAlgo_DataMapOfIntegerCirc;
%rename(DataMapIteratorOfDataMapOfIntegerCirc) MeshAlgo_DataMapIteratorOfDataMapOfIntegerCirc;
%rename(Circ) MeshAlgo_Circ;
%rename(MeshAlgo) MeshAlgo;
%rename(Handle_DataMapNodeOfDataMapOfIntegerCirc) Handle_MeshAlgo_DataMapNodeOfDataMapOfIntegerCirc;
