%rename(RWHeaderSection) RWHeaderSection;
%rename(Handle_RWHeaderSection_GeneralModule) Handle_RWHeaderSection_GeneralModule;
%rename(RWHeaderSection_GeneralModule) RWHeaderSection_GeneralModule;
%rename(RWHeaderSection_RWFileSchema) RWHeaderSection_RWFileSchema;
%rename(RWHeaderSection_RWFileName) RWHeaderSection_RWFileName;
%rename(Handle_RWHeaderSection_ReadWriteModule) Handle_RWHeaderSection_ReadWriteModule;
%rename(RWHeaderSection_ReadWriteModule) RWHeaderSection_ReadWriteModule;
%rename(RWHeaderSection_RWFileDescription) RWHeaderSection_RWFileDescription;
