%rename(DocumentRetrievalDriver) XCAFDrivers_DocumentRetrievalDriver;
%rename(DocumentStorageDriver) XCAFDrivers_DocumentStorageDriver;
%rename(Handle_DocumentRetrievalDriver) Handle_XCAFDrivers_DocumentRetrievalDriver;
%rename(XCAFDrivers) XCAFDrivers;
%rename(Handle_DocumentStorageDriver) Handle_XCAFDrivers_DocumentStorageDriver;
