%rename(DocumentRetrievalDriver) XmlDrivers_DocumentRetrievalDriver;
%rename(DocumentStorageDriver) XmlDrivers_DocumentStorageDriver;
%rename(Handle_DocumentRetrievalDriver) Handle_XmlDrivers_DocumentRetrievalDriver;
%rename(XmlDrivers) XmlDrivers;
%rename(Handle_DocumentStorageDriver) Handle_XmlDrivers_DocumentStorageDriver;
