%rename(XmlMPrsStd) XmlMPrsStd;
%rename(Handle_XmlMPrsStd_AISPresentationDriver) Handle_XmlMPrsStd_AISPresentationDriver;
%rename(XmlMPrsStd_PositionDriver) XmlMPrsStd_PositionDriver;
%rename(XmlMPrsStd_AISPresentationDriver) XmlMPrsStd_AISPresentationDriver;
%rename(Handle_XmlMPrsStd_PositionDriver) Handle_XmlMPrsStd_PositionDriver;
