%rename(XmlObjMgt_Persistent) XmlObjMgt_Persistent;
%rename(Handle_XmlObjMgt_DataMapNodeOfRRelocationTable) Handle_XmlObjMgt_DataMapNodeOfRRelocationTable;
%rename(XmlObjMgt_GP) XmlObjMgt_GP;
%rename(XmlObjMgt_DataMapIteratorOfRRelocationTable) XmlObjMgt_DataMapIteratorOfRRelocationTable;
%rename(XmlObjMgt_RRelocationTable) XmlObjMgt_RRelocationTable;
%rename(XmlObjMgt) XmlObjMgt;
%rename(XmlObjMgt_DataMapNodeOfRRelocationTable) XmlObjMgt_DataMapNodeOfRRelocationTable;
