// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBooleanOperations_StateOfShape_HeaderFile
#define _XBooleanOperations_StateOfShape_HeaderFile

//! the derived class of Explorer to find subshapes only once. <br>//! is to be  deferred with inherited classes Cut, Common, <br>
//!          Fuse to perform boolean operations . <br>//! State of a Shape of the 1st solid according to the <br>
//!          2nd one.  State INOROUT is  used when we know that <br>
//!           a shape  is  totally IN or   totally  OUT.  State <br>
//!          INTERSECTED refers to a shape of the 1st solid cut <br>
//!          by   the  2nd solid.   When a  shape has  a  state <br>
//!          different  of  INTERSECTED or UNKNOWN   all of its <br>
//!          subshapes have the same state. <br>
enum XBooleanOperations_StateOfShape {
XBooleanOperations_IN,
XBooleanOperations_OUT,
XBooleanOperations_ON,
XBooleanOperations_UNKNOWN,
XBooleanOperations_INOROUT,
XBooleanOperations_INTERSECTED
};

#ifndef _Standard_PrimitiveTypes_HeaderFile
#include <Standard_PrimitiveTypes.hxx>
#endif

#endif
