// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBooleanOperations_OnceExplorer_HeaderFile
#define _XBooleanOperations_OnceExplorer_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _Standard_Address_HeaderFile
#include <Standard_Address.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _XBooleanOperations_Explorer_HeaderFile
#include <XBooleanOperations_Explorer.hxx>
#endif
#ifndef _TopAbs_ShapeEnum_HeaderFile
#include <TopAbs_ShapeEnum.hxx>
#endif
#ifndef _Standard_OStream_HeaderFile
#include <Standard_OStream.hxx>
#endif
class XBooleanOperations_ShapesDataStructure;



class XBooleanOperations_OnceExplorer  : public XBooleanOperations_Explorer {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
  Standard_EXPORT   XBooleanOperations_OnceExplorer(const XBooleanOperations_ShapesDataStructure& SDS);
  
  Standard_EXPORT   virtual  void Delete() ;
Standard_EXPORT virtual ~XBooleanOperations_OnceExplorer()  {Delete();}
  
  Standard_EXPORT   virtual  void Init(const Standard_Integer aShape,const TopAbs_ShapeEnum TargetToFind,const TopAbs_ShapeEnum TargetToAvoid = TopAbs_SHAPE) ;
  
  Standard_EXPORT   virtual  void Next() ;
  
  Standard_EXPORT   virtual  Standard_Integer Current() ;
  
  Standard_EXPORT   virtual  void Dump(Standard_OStream& S) const;





protected:





private:



Standard_Address myArrayOfBits;
Standard_Integer mySizeOfArrayOfBits;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
