// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBooleanOperations_KindOfInterference_HeaderFile
#define _XBooleanOperations_KindOfInterference_HeaderFile

//! Interferences describe an intersection between two <br>
//!          shapes. They  are classified following a hierarchy <br>
//!          from the lower until the  upper. <br>
enum XBooleanOperations_KindOfInterference {
XBooleanOperations_SurfaceSurface,
XBooleanOperations_EdgeSurface,
XBooleanOperations_VertexSurface,
XBooleanOperations_EdgeEdge,
XBooleanOperations_VertexEdge,
XBooleanOperations_VertexVertex,
XBooleanOperations_UnknownInterference
};

#ifndef _Standard_PrimitiveTypes_HeaderFile
#include <Standard_PrimitiveTypes.hxx>
#endif

#endif
