// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOPTools_CheckStatus_HeaderFile
#define _XBOPTools_CheckStatus_HeaderFile


enum XBOPTools_CheckStatus {
XBOPTools_CHKUNKNOWN,
XBOPTools_VERTEXVERTEX,
XBOPTools_VERTEXEDGE,
XBOPTools_VERTEXFACE,
XBOPTools_EDGEEDGE,
XBOPTools_EDGEEDGECOMBLK,
XBOPTools_EDGEFACE,
XBOPTools_EDGEFACECOMBLK,
XBOPTools_FACEFACE,
XBOPTools_BADSHRANKRANGE,
XBOPTools_NULLSRANKRANGE
};

#ifndef _Standard_PrimitiveTypes_HeaderFile
#include <Standard_PrimitiveTypes.hxx>
#endif

#endif
