// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOP_PWireEdgeSet_HeaderFile
#define _XBOP_PWireEdgeSet_HeaderFile

class XBOP_WireEdgeSet;

typedef XBOP_WireEdgeSet* XBOP_PWireEdgeSet;

#endif
