// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOPTools_SequenceNodeOfSequenceOfCurves_HeaderFile
#define _XBOPTools_SequenceNodeOfSequenceOfCurves_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_XBOPTools_SequenceNodeOfSequenceOfCurves_HeaderFile
#include <Handle_XBOPTools_SequenceNodeOfSequenceOfCurves.hxx>
#endif

#ifndef _XBOPTools_Curve_HeaderFile
#include <XBOPTools_Curve.hxx>
#endif
#ifndef _TCollection_SeqNode_HeaderFile
#include <TCollection_SeqNode.hxx>
#endif
#ifndef _TCollection_SeqNodePtr_HeaderFile
#include <TCollection_SeqNodePtr.hxx>
#endif
class XBOPTools_Curve;
class XBOPTools_SequenceOfCurves;



class XBOPTools_SequenceNodeOfSequenceOfCurves : public TCollection_SeqNode {

public:

  
      XBOPTools_SequenceNodeOfSequenceOfCurves(const XBOPTools_Curve& I,const TCollection_SeqNodePtr& n,const TCollection_SeqNodePtr& p);
  
        XBOPTools_Curve& Value() const;




  DEFINE_STANDARD_RTTI(XBOPTools_SequenceNodeOfSequenceOfCurves)

protected:




private: 


XBOPTools_Curve myValue;


};

#define SeqItem XBOPTools_Curve
#define SeqItem_hxx <XBOPTools_Curve.hxx>
#define TCollection_SequenceNode XBOPTools_SequenceNodeOfSequenceOfCurves
#define TCollection_SequenceNode_hxx <XBOPTools_SequenceNodeOfSequenceOfCurves.hxx>
#define Handle_TCollection_SequenceNode Handle_XBOPTools_SequenceNodeOfSequenceOfCurves
#define TCollection_SequenceNode_Type_() XBOPTools_SequenceNodeOfSequenceOfCurves_Type_()
#define TCollection_Sequence XBOPTools_SequenceOfCurves
#define TCollection_Sequence_hxx <XBOPTools_SequenceOfCurves.hxx>

#include <TCollection_SequenceNode.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
