// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOP_Operation_HeaderFile
#define _XBOP_Operation_HeaderFile


enum XBOP_Operation {
XBOP_COMMON,
XBOP_FUSE,
XBOP_CUT,
XBOP_CUT21,
XBOP_SECTION,
XBOP_UNKNOWN
};

#ifndef _Standard_PrimitiveTypes_HeaderFile
#include <Standard_PrimitiveTypes.hxx>
#endif

#endif
