// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOP_ListNodeOfListOfCheckResult_HeaderFile
#define _XBOP_ListNodeOfListOfCheckResult_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_XBOP_ListNodeOfListOfCheckResult_HeaderFile
#include <Handle_XBOP_ListNodeOfListOfCheckResult.hxx>
#endif

#ifndef _XBOP_CheckResult_HeaderFile
#include <XBOP_CheckResult.hxx>
#endif
#ifndef _TCollection_MapNode_HeaderFile
#include <TCollection_MapNode.hxx>
#endif
#ifndef _TCollection_MapNodePtr_HeaderFile
#include <TCollection_MapNodePtr.hxx>
#endif
class XBOP_CheckResult;
class XBOP_ListOfCheckResult;
class XBOP_ListIteratorOfListOfCheckResult;



class XBOP_ListNodeOfListOfCheckResult : public TCollection_MapNode {

public:

  
      XBOP_ListNodeOfListOfCheckResult(const XBOP_CheckResult& I,const TCollection_MapNodePtr& n);
  
        XBOP_CheckResult& Value() const;




  DEFINE_STANDARD_RTTI(XBOP_ListNodeOfListOfCheckResult)

protected:




private: 


XBOP_CheckResult myValue;


};

#define Item XBOP_CheckResult
#define Item_hxx <XBOP_CheckResult.hxx>
#define TCollection_ListNode XBOP_ListNodeOfListOfCheckResult
#define TCollection_ListNode_hxx <XBOP_ListNodeOfListOfCheckResult.hxx>
#define TCollection_ListIterator XBOP_ListIteratorOfListOfCheckResult
#define TCollection_ListIterator_hxx <XBOP_ListIteratorOfListOfCheckResult.hxx>
#define Handle_TCollection_ListNode Handle_XBOP_ListNodeOfListOfCheckResult
#define TCollection_ListNode_Type_() XBOP_ListNodeOfListOfCheckResult_Type_()
#define TCollection_List XBOP_ListOfCheckResult
#define TCollection_List_hxx <XBOP_ListOfCheckResult.hxx>

#include <TCollection_ListNode.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_ListNode
#undef TCollection_ListNode_hxx
#undef TCollection_ListIterator
#undef TCollection_ListIterator_hxx
#undef Handle_TCollection_ListNode
#undef TCollection_ListNode_Type_
#undef TCollection_List
#undef TCollection_List_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
