// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOPTools_IndexedDataMapOfIntegerPaveSet_HeaderFile
#define _XBOPTools_IndexedDataMapOfIntegerPaveSet_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _TCollection_BasicMap_HeaderFile
#include <TCollection_BasicMap.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _Handle_XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerPaveSet_HeaderFile
#include <Handle_XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerPaveSet.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
#ifndef _Standard_Address_HeaderFile
#include <Standard_Address.hxx>
#endif
class Standard_DomainError;
class Standard_OutOfRange;
class Standard_NoSuchObject;
class XBOPTools_PaveSet;
class TColStd_MapIntegerHasher;
class XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerPaveSet;



class XBOPTools_IndexedDataMapOfIntegerPaveSet  : public TCollection_BasicMap {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
  Standard_EXPORT   XBOPTools_IndexedDataMapOfIntegerPaveSet(const Standard_Integer NbBuckets = 1);
  
  Standard_EXPORT     XBOPTools_IndexedDataMapOfIntegerPaveSet& Assign(const XBOPTools_IndexedDataMapOfIntegerPaveSet& Other) ;
    XBOPTools_IndexedDataMapOfIntegerPaveSet& operator =(const XBOPTools_IndexedDataMapOfIntegerPaveSet& Other) 
{
  return Assign(Other);
}
  
  Standard_EXPORT     void ReSize(const Standard_Integer NbBuckets) ;
  
  Standard_EXPORT     void Clear() ;
~XBOPTools_IndexedDataMapOfIntegerPaveSet()
{
  Clear();
}
  
  Standard_EXPORT     Standard_Integer Add(const Standard_Integer& K,const XBOPTools_PaveSet& I) ;
  
  Standard_EXPORT     void Substitute(const Standard_Integer I,const Standard_Integer& K,const XBOPTools_PaveSet& T) ;
  
  Standard_EXPORT     void RemoveLast() ;
  
  Standard_EXPORT     Standard_Boolean Contains(const Standard_Integer& K) const;
  
  Standard_EXPORT    const Standard_Integer& FindKey(const Standard_Integer I) const;
  
  Standard_EXPORT    const XBOPTools_PaveSet& FindFromIndex(const Standard_Integer I) const;
   const XBOPTools_PaveSet& operator ()(const Standard_Integer I) const
{
  return FindFromIndex(I);
}
  
  Standard_EXPORT     XBOPTools_PaveSet& ChangeFromIndex(const Standard_Integer I) ;
    XBOPTools_PaveSet& operator ()(const Standard_Integer I) 
{
  return ChangeFromIndex(I);
}
  
  Standard_EXPORT     Standard_Integer FindIndex(const Standard_Integer& K) const;
  
  Standard_EXPORT    const XBOPTools_PaveSet& FindFromKey(const Standard_Integer& K) const;
  
  Standard_EXPORT     XBOPTools_PaveSet& ChangeFromKey(const Standard_Integer& K) ;
  
  Standard_EXPORT     Standard_Address FindFromKey1(const Standard_Integer& K) const;
  
  Standard_EXPORT     Standard_Address ChangeFromKey1(const Standard_Integer& K) ;





protected:





private:

  
  Standard_EXPORT   XBOPTools_IndexedDataMapOfIntegerPaveSet(const XBOPTools_IndexedDataMapOfIntegerPaveSet& Other);




};





// other Inline functions and methods (like "C++: function call" methods)


#endif
