// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOPTools_PPaveFiller_HeaderFile
#define _XBOPTools_PPaveFiller_HeaderFile

class XBOPTools_PaveFiller;

typedef XBOPTools_PaveFiller* XBOPTools_PPaveFiller;

#endif
