// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOPTools_IntersectionStatus_HeaderFile
#define _XBOPTools_IntersectionStatus_HeaderFile


enum XBOPTools_IntersectionStatus {
XBOPTools_INTERSECTED,
XBOPTools_BOUNDINGBOXINTERSECTED,
XBOPTools_BOUNDINGBOXOFSUBSHAPESINTERSECTED,
XBOPTools_NONINTERSECTED,
XBOPTools_UNKNOWN
};

#ifndef _Standard_PrimitiveTypes_HeaderFile
#include <Standard_PrimitiveTypes.hxx>
#endif

#endif
