// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOPTools_Curve_HeaderFile
#define _XBOPTools_Curve_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _XIntTools_Curve_HeaderFile
#include <XIntTools_Curve.hxx>
#endif
#ifndef _XBOPTools_PaveSet_HeaderFile
#include <XBOPTools_PaveSet.hxx>
#endif
#ifndef _XBOPTools_ListOfPaveBlock_HeaderFile
#include <XBOPTools_ListOfPaveBlock.hxx>
#endif
#ifndef _TColStd_ListOfInteger_HeaderFile
#include <TColStd_ListOfInteger.hxx>
#endif
class XIntTools_Curve;
class XBOPTools_PaveSet;
class XBOPTools_PaveBlock;
class XBOPTools_ListOfPaveBlock;
class TColStd_ListOfInteger;



//!  Class holds the  structure for storing information about <br>
//! intersection curve and set of paves on it <br>
//! <br>
class XBOPTools_Curve  {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
//! Empty constructor <br>
  Standard_EXPORT   XBOPTools_Curve();
  
//! Constructor <br>
  Standard_EXPORT   XBOPTools_Curve(const XIntTools_Curve& aIC);
  
//! Modifier <br>
  Standard_EXPORT     void SetCurve(const XIntTools_Curve& aIC) ;
  
//! Selector <br>
  Standard_EXPORT    const XIntTools_Curve& Curve() const;
  
//! Selector <br>
//! <br>
  Standard_EXPORT     XBOPTools_PaveSet& Set() ;
  
//! Adds the PaveBlock  <aPB> to the pave set <br>
  Standard_EXPORT     void AppendNewBlock(const XBOPTools_PaveBlock& aPB) ;
  
//! Returns the PaveBlock-s attached to the curve <br>
  Standard_EXPORT    const XBOPTools_ListOfPaveBlock& NewPaveBlocks() const;
  
//! Returns indices TechnoVertices attached to the curve <br>
  Standard_EXPORT     TColStd_ListOfInteger& TechnoVertices() ;





protected:





private:



XIntTools_Curve myCurve;
XBOPTools_PaveSet myPaveSet;
XBOPTools_ListOfPaveBlock myNewPBs;
TColStd_ListOfInteger myTechnoVertices;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
