// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XIntTools_ListIteratorOfListOfCurveRangeSample_HeaderFile
#define _XIntTools_ListIteratorOfListOfCurveRangeSample_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _Standard_Address_HeaderFile
#include <Standard_Address.hxx>
#endif
#ifndef _Handle_XIntTools_ListNodeOfListOfCurveRangeSample_HeaderFile
#include <Handle_XIntTools_ListNodeOfListOfCurveRangeSample.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class Standard_NoMoreObject;
class Standard_NoSuchObject;
class XIntTools_ListOfCurveRangeSample;
class XIntTools_CurveRangeSample;
class XIntTools_ListNodeOfListOfCurveRangeSample;



class XIntTools_ListIteratorOfListOfCurveRangeSample  {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
  Standard_EXPORT   XIntTools_ListIteratorOfListOfCurveRangeSample();
  
  Standard_EXPORT   XIntTools_ListIteratorOfListOfCurveRangeSample(const XIntTools_ListOfCurveRangeSample& L);
  
  Standard_EXPORT     void Initialize(const XIntTools_ListOfCurveRangeSample& L) ;
  
        Standard_Boolean More() const;
  
  Standard_EXPORT     void Next() ;
  
  Standard_EXPORT     XIntTools_CurveRangeSample& Value() const;


friend class XIntTools_ListOfCurveRangeSample;



protected:





private:



Standard_Address current;
Standard_Address previous;


};

#define Item XIntTools_CurveRangeSample
#define Item_hxx <XIntTools_CurveRangeSample.hxx>
#define TCollection_ListNode XIntTools_ListNodeOfListOfCurveRangeSample
#define TCollection_ListNode_hxx <XIntTools_ListNodeOfListOfCurveRangeSample.hxx>
#define TCollection_ListIterator XIntTools_ListIteratorOfListOfCurveRangeSample
#define TCollection_ListIterator_hxx <XIntTools_ListIteratorOfListOfCurveRangeSample.hxx>
#define Handle_TCollection_ListNode Handle_XIntTools_ListNodeOfListOfCurveRangeSample
#define TCollection_ListNode_Type_() XIntTools_ListNodeOfListOfCurveRangeSample_Type_()
#define TCollection_List XIntTools_ListOfCurveRangeSample
#define TCollection_List_hxx <XIntTools_ListOfCurveRangeSample.hxx>

#include <TCollection_ListIterator.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_ListNode
#undef TCollection_ListNode_hxx
#undef TCollection_ListIterator
#undef TCollection_ListIterator_hxx
#undef Handle_TCollection_ListNode
#undef TCollection_ListNode_Type_
#undef TCollection_List
#undef TCollection_List_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
