// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XIntTools_SequenceOfPntOn2Faces_HeaderFile
#define _XIntTools_SequenceOfPntOn2Faces_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _TCollection_BaseSequence_HeaderFile
#include <TCollection_BaseSequence.hxx>
#endif
#ifndef _Handle_XIntTools_SequenceNodeOfSequenceOfPntOn2Faces_HeaderFile
#include <Handle_XIntTools_SequenceNodeOfSequenceOfPntOn2Faces.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
class Standard_NoSuchObject;
class Standard_OutOfRange;
class XIntTools_PntOn2Faces;
class XIntTools_SequenceNodeOfSequenceOfPntOn2Faces;



class XIntTools_SequenceOfPntOn2Faces  : public TCollection_BaseSequence {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
      XIntTools_SequenceOfPntOn2Faces();
  
  Standard_EXPORT     void Clear() ;
~XIntTools_SequenceOfPntOn2Faces()
{
  Clear();
}
  
  Standard_EXPORT    const XIntTools_SequenceOfPntOn2Faces& Assign(const XIntTools_SequenceOfPntOn2Faces& Other) ;
   const XIntTools_SequenceOfPntOn2Faces& operator =(const XIntTools_SequenceOfPntOn2Faces& Other) 
{
  return Assign(Other);
}
  
  Standard_EXPORT     void Append(const XIntTools_PntOn2Faces& T) ;
  
        void Append(XIntTools_SequenceOfPntOn2Faces& S) ;
  
  Standard_EXPORT     void Prepend(const XIntTools_PntOn2Faces& T) ;
  
        void Prepend(XIntTools_SequenceOfPntOn2Faces& S) ;
  
        void InsertBefore(const Standard_Integer Index,const XIntTools_PntOn2Faces& T) ;
  
        void InsertBefore(const Standard_Integer Index,XIntTools_SequenceOfPntOn2Faces& S) ;
  
  Standard_EXPORT     void InsertAfter(const Standard_Integer Index,const XIntTools_PntOn2Faces& T) ;
  
        void InsertAfter(const Standard_Integer Index,XIntTools_SequenceOfPntOn2Faces& S) ;
  
  Standard_EXPORT    const XIntTools_PntOn2Faces& First() const;
  
  Standard_EXPORT    const XIntTools_PntOn2Faces& Last() const;
  
        void Split(const Standard_Integer Index,XIntTools_SequenceOfPntOn2Faces& Sub) ;
  
  Standard_EXPORT    const XIntTools_PntOn2Faces& Value(const Standard_Integer Index) const;
   const XIntTools_PntOn2Faces& operator()(const Standard_Integer Index) const
{
  return Value(Index);
}
  
  Standard_EXPORT     void SetValue(const Standard_Integer Index,const XIntTools_PntOn2Faces& I) ;
  
  Standard_EXPORT     XIntTools_PntOn2Faces& ChangeValue(const Standard_Integer Index) ;
    XIntTools_PntOn2Faces& operator()(const Standard_Integer Index) 
{
  return ChangeValue(Index);
}
  
  Standard_EXPORT     void Remove(const Standard_Integer Index) ;
  
  Standard_EXPORT     void Remove(const Standard_Integer FromIndex,const Standard_Integer ToIndex) ;





protected:





private:

  
  Standard_EXPORT   XIntTools_SequenceOfPntOn2Faces(const XIntTools_SequenceOfPntOn2Faces& Other);




};

#define SeqItem XIntTools_PntOn2Faces
#define SeqItem_hxx <XIntTools_PntOn2Faces.hxx>
#define TCollection_SequenceNode XIntTools_SequenceNodeOfSequenceOfPntOn2Faces
#define TCollection_SequenceNode_hxx <XIntTools_SequenceNodeOfSequenceOfPntOn2Faces.hxx>
#define Handle_TCollection_SequenceNode Handle_XIntTools_SequenceNodeOfSequenceOfPntOn2Faces
#define TCollection_SequenceNode_Type_() XIntTools_SequenceNodeOfSequenceOfPntOn2Faces_Type_()
#define TCollection_Sequence XIntTools_SequenceOfPntOn2Faces
#define TCollection_Sequence_hxx <XIntTools_SequenceOfPntOn2Faces.hxx>

#include <TCollection_Sequence.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
