// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XIntTools_MapOfCurveSample_HeaderFile
#define _XIntTools_MapOfCurveSample_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _TCollection_BasicMap_HeaderFile
#include <TCollection_BasicMap.hxx>
#endif
#ifndef _Handle_XIntTools_StdMapNodeOfMapOfCurveSample_HeaderFile
#include <Handle_XIntTools_StdMapNodeOfMapOfCurveSample.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class Standard_DomainError;
class XIntTools_CurveRangeSample;
class XIntTools_CurveRangeSampleMapHasher;
class XIntTools_StdMapNodeOfMapOfCurveSample;
class XIntTools_MapIteratorOfMapOfCurveSample;



class XIntTools_MapOfCurveSample  : public TCollection_BasicMap {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
  Standard_EXPORT   XIntTools_MapOfCurveSample(const Standard_Integer NbBuckets = 1);
  
  Standard_EXPORT     XIntTools_MapOfCurveSample& Assign(const XIntTools_MapOfCurveSample& Other) ;
    XIntTools_MapOfCurveSample& operator =(const XIntTools_MapOfCurveSample& Other) 
{
  return Assign(Other);
}
  
  Standard_EXPORT     void ReSize(const Standard_Integer NbBuckets) ;
  
  Standard_EXPORT     void Clear() ;
~XIntTools_MapOfCurveSample()
{
  Clear();
}
  
  Standard_EXPORT     Standard_Boolean Add(const XIntTools_CurveRangeSample& aKey) ;
  
  Standard_EXPORT     Standard_Boolean Contains(const XIntTools_CurveRangeSample& aKey) const;
  
  Standard_EXPORT     Standard_Boolean Remove(const XIntTools_CurveRangeSample& aKey) ;





protected:





private:

  
  Standard_EXPORT   XIntTools_MapOfCurveSample(const XIntTools_MapOfCurveSample& Other);




};





// other Inline functions and methods (like "C++: function call" methods)


#endif
