// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBooleanOperations_ShapeAndInterferences_HeaderFile
#define _XBooleanOperations_ShapeAndInterferences_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _Bnd_Box_HeaderFile
#include <Bnd_Box.hxx>
#endif
#ifndef _XBooleanOperations_AncestorsAndSuccessors_HeaderFile
#include <XBooleanOperations_AncestorsAndSuccessors.hxx>
#endif
#ifndef _TopoDS_Shape_HeaderFile
#include <TopoDS_Shape.hxx>
#endif
#ifndef _XBooleanOperations_StateOfShape_HeaderFile
#include <XBooleanOperations_StateOfShape.hxx>
#endif
#ifndef _TopAbs_ShapeEnum_HeaderFile
#include <TopAbs_ShapeEnum.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _Standard_Address_HeaderFile
#include <Standard_Address.hxx>
#endif
#ifndef _TopAbs_Orientation_HeaderFile
#include <TopAbs_Orientation.hxx>
#endif
class XBooleanOperations_ShapesDataStructure;
class TopoDS_Shape;
class Bnd_Box;



class XBooleanOperations_ShapeAndInterferences  {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
  Standard_EXPORT   XBooleanOperations_ShapeAndInterferences();
  
       const TopoDS_Shape& GetShape() const;
  
        TopAbs_ShapeEnum GetShapeType() const;
  
        XBooleanOperations_StateOfShape GetState() const;
  
        void SetState(const XBooleanOperations_StateOfShape theState) ;
  
       const Bnd_Box& GetBoundingBox() const;
  
        Standard_Integer NumberOfAncestors() const;
  
        Standard_Integer NumberOfSuccessors() const;
  
        Standard_Integer GetAncestor(const Standard_Integer index) const;
  
        Standard_Integer GetSuccessor(const Standard_Integer index) const;
  
        void GetAncestors(Standard_Address& theArrayOfAncestors,Standard_Integer& AncestorsSize) const;
  
        void GetSuccessors(Standard_Address& theArrayOfSuccessors,Standard_Integer& SuccessorsSize) const;
  
        TopAbs_Orientation GetOrientation(const Standard_Integer index) const;
  //! sets an interference in <myInterferencesList>. <br>//! to display the fields. <br>
        void GetOrientations(Standard_Address& theArrayOfOrientations,Standard_Integer& OrientationsSize) const;


friend class XBooleanOperations_ShapesDataStructure;



protected:





private:



Bnd_Box myBoundingBox;
XBooleanOperations_AncestorsAndSuccessors myAncestorsAndSuccessors;
TopoDS_Shape myShape;
XBooleanOperations_StateOfShape myState;


};


#include <XBooleanOperations_ShapeAndInterferences.lxx>



// other Inline functions and methods (like "C++: function call" methods)


#endif
