// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOPTools_ListOfPave_HeaderFile
#define _XBOPTools_ListOfPave_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _Standard_Address_HeaderFile
#include <Standard_Address.hxx>
#endif
#ifndef _Handle_XBOPTools_ListNodeOfListOfPave_HeaderFile
#include <Handle_XBOPTools_ListNodeOfListOfPave.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class Standard_NoSuchObject;
class XBOPTools_ListIteratorOfListOfPave;
class XBOPTools_Pave;
class XBOPTools_ListNodeOfListOfPave;



class XBOPTools_ListOfPave  {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
  Standard_EXPORT   XBOPTools_ListOfPave();
  
  Standard_EXPORT     void Assign(const XBOPTools_ListOfPave& Other) ;
    void operator=(const XBOPTools_ListOfPave& Other) 
{
  Assign(Other);
}
  
  Standard_EXPORT     Standard_Integer Extent() const;
  
  Standard_EXPORT     void Clear() ;
~XBOPTools_ListOfPave()
{
  Clear();
}
  
        Standard_Boolean IsEmpty() const;
  
  Standard_EXPORT     void Prepend(const XBOPTools_Pave& I) ;
  
  Standard_EXPORT     void Prepend(const XBOPTools_Pave& I,XBOPTools_ListIteratorOfListOfPave& theIt) ;
  
  Standard_EXPORT     void Prepend(XBOPTools_ListOfPave& Other) ;
  
  Standard_EXPORT     void Append(const XBOPTools_Pave& I) ;
  
  Standard_EXPORT     void Append(const XBOPTools_Pave& I,XBOPTools_ListIteratorOfListOfPave& theIt) ;
  
  Standard_EXPORT     void Append(XBOPTools_ListOfPave& Other) ;
  
  Standard_EXPORT     XBOPTools_Pave& First() const;
  
  Standard_EXPORT     XBOPTools_Pave& Last() const;
  
  Standard_EXPORT     void RemoveFirst() ;
  
  Standard_EXPORT     void Remove(XBOPTools_ListIteratorOfListOfPave& It) ;
  
  Standard_EXPORT     void InsertBefore(const XBOPTools_Pave& I,XBOPTools_ListIteratorOfListOfPave& It) ;
  
  Standard_EXPORT     void InsertBefore(XBOPTools_ListOfPave& Other,XBOPTools_ListIteratorOfListOfPave& It) ;
  
  Standard_EXPORT     void InsertAfter(const XBOPTools_Pave& I,XBOPTools_ListIteratorOfListOfPave& It) ;
  
  Standard_EXPORT     void InsertAfter(XBOPTools_ListOfPave& Other,XBOPTools_ListIteratorOfListOfPave& It) ;


friend class XBOPTools_ListIteratorOfListOfPave;



protected:





private:

  
  Standard_EXPORT   XBOPTools_ListOfPave(const XBOPTools_ListOfPave& Other);


Standard_Address myFirst;
Standard_Address myLast;


};

#define Item XBOPTools_Pave
#define Item_hxx <XBOPTools_Pave.hxx>
#define TCollection_ListNode XBOPTools_ListNodeOfListOfPave
#define TCollection_ListNode_hxx <XBOPTools_ListNodeOfListOfPave.hxx>
#define TCollection_ListIterator XBOPTools_ListIteratorOfListOfPave
#define TCollection_ListIterator_hxx <XBOPTools_ListIteratorOfListOfPave.hxx>
#define Handle_TCollection_ListNode Handle_XBOPTools_ListNodeOfListOfPave
#define TCollection_ListNode_Type_() XBOPTools_ListNodeOfListOfPave_Type_()
#define TCollection_List XBOPTools_ListOfPave
#define TCollection_List_hxx <XBOPTools_ListOfPave.hxx>

#include <TCollection_List.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_ListNode
#undef TCollection_ListNode_hxx
#undef TCollection_ListIterator
#undef TCollection_ListIterator_hxx
#undef Handle_TCollection_ListNode
#undef TCollection_ListNode_Type_
#undef TCollection_List
#undef TCollection_List_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
