// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOPTools_ListNodeOfListOfInterference_HeaderFile
#define _XBOPTools_ListNodeOfListOfInterference_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_XBOPTools_ListNodeOfListOfInterference_HeaderFile
#include <Handle_XBOPTools_ListNodeOfListOfInterference.hxx>
#endif

#ifndef _XBOPTools_Interference_HeaderFile
#include <XBOPTools_Interference.hxx>
#endif
#ifndef _TCollection_MapNode_HeaderFile
#include <TCollection_MapNode.hxx>
#endif
#ifndef _TCollection_MapNodePtr_HeaderFile
#include <TCollection_MapNodePtr.hxx>
#endif
class XBOPTools_Interference;
class XBOPTools_ListOfInterference;
class XBOPTools_ListIteratorOfListOfInterference;



class XBOPTools_ListNodeOfListOfInterference : public TCollection_MapNode {

public:

  
      XBOPTools_ListNodeOfListOfInterference(const XBOPTools_Interference& I,const TCollection_MapNodePtr& n);
  
        XBOPTools_Interference& Value() const;




  DEFINE_STANDARD_RTTI(XBOPTools_ListNodeOfListOfInterference)

protected:




private: 


XBOPTools_Interference myValue;


};

#define Item XBOPTools_Interference
#define Item_hxx <XBOPTools_Interference.hxx>
#define TCollection_ListNode XBOPTools_ListNodeOfListOfInterference
#define TCollection_ListNode_hxx <XBOPTools_ListNodeOfListOfInterference.hxx>
#define TCollection_ListIterator XBOPTools_ListIteratorOfListOfInterference
#define TCollection_ListIterator_hxx <XBOPTools_ListIteratorOfListOfInterference.hxx>
#define Handle_TCollection_ListNode Handle_XBOPTools_ListNodeOfListOfInterference
#define TCollection_ListNode_Type_() XBOPTools_ListNodeOfListOfInterference_Type_()
#define TCollection_List XBOPTools_ListOfInterference
#define TCollection_List_hxx <XBOPTools_ListOfInterference.hxx>

#include <TCollection_ListNode.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_ListNode
#undef TCollection_ListNode_hxx
#undef TCollection_ListIterator
#undef TCollection_ListIterator_hxx
#undef Handle_TCollection_ListNode
#undef TCollection_ListNode_Type_
#undef TCollection_List
#undef TCollection_List_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
