// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOP_ListIteratorOfListOfListOfLoop_HeaderFile
#define _XBOP_ListIteratorOfListOfListOfLoop_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _Standard_Address_HeaderFile
#include <Standard_Address.hxx>
#endif
#ifndef _Handle_XBOP_ListNodeOfListOfListOfLoop_HeaderFile
#include <Handle_XBOP_ListNodeOfListOfListOfLoop.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class Standard_NoMoreObject;
class Standard_NoSuchObject;
class XBOP_ListOfListOfLoop;
class XBOP_ListOfLoop;
class XBOP_ListNodeOfListOfListOfLoop;



class XBOP_ListIteratorOfListOfListOfLoop  {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
  Standard_EXPORT   XBOP_ListIteratorOfListOfListOfLoop();
  
  Standard_EXPORT   XBOP_ListIteratorOfListOfListOfLoop(const XBOP_ListOfListOfLoop& L);
  
  Standard_EXPORT     void Initialize(const XBOP_ListOfListOfLoop& L) ;
  
        Standard_Boolean More() const;
  
  Standard_EXPORT     void Next() ;
  
  Standard_EXPORT     XBOP_ListOfLoop& Value() const;


friend class XBOP_ListOfListOfLoop;



protected:





private:



Standard_Address current;
Standard_Address previous;


};

#define Item XBOP_ListOfLoop
#define Item_hxx <XBOP_ListOfLoop.hxx>
#define TCollection_ListNode XBOP_ListNodeOfListOfListOfLoop
#define TCollection_ListNode_hxx <XBOP_ListNodeOfListOfListOfLoop.hxx>
#define TCollection_ListIterator XBOP_ListIteratorOfListOfListOfLoop
#define TCollection_ListIterator_hxx <XBOP_ListIteratorOfListOfListOfLoop.hxx>
#define Handle_TCollection_ListNode Handle_XBOP_ListNodeOfListOfListOfLoop
#define TCollection_ListNode_Type_() XBOP_ListNodeOfListOfListOfLoop_Type_()
#define TCollection_List XBOP_ListOfListOfLoop
#define TCollection_List_hxx <XBOP_ListOfListOfLoop.hxx>

#include <TCollection_ListIterator.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_ListNode
#undef TCollection_ListNode_hxx
#undef TCollection_ListIterator
#undef TCollection_ListIterator_hxx
#undef Handle_TCollection_ListNode
#undef TCollection_ListNode_Type_
#undef TCollection_List
#undef TCollection_List_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
