// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger_HeaderFile
#define _XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger_HeaderFile
#include <Handle_XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger.hxx>
#endif

#ifndef _XBOPTColStd_ShapeWithRank_HeaderFile
#include <XBOPTColStd_ShapeWithRank.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _TCollection_MapNodePtr_HeaderFile
#include <TCollection_MapNodePtr.hxx>
#endif
#ifndef _TCollection_MapNode_HeaderFile
#include <TCollection_MapNode.hxx>
#endif
class XBOPTColStd_ShapeWithRank;
class XBOPTColStd_ShapeWithRankHasher;
class XBOPTColStd_IndexedDataMapOfSWRInteger;



class XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger : public TCollection_MapNode {

public:

  
      XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger(const XBOPTColStd_ShapeWithRank& K1,const Standard_Integer K2,const Standard_Integer& I,const TCollection_MapNodePtr& n1,const TCollection_MapNodePtr& n2);
  
        XBOPTColStd_ShapeWithRank& Key1() const;
  
        Standard_Integer& Key2() const;
  
        TCollection_MapNodePtr& Next2() const;
  
        Standard_Integer& Value() const;




  DEFINE_STANDARD_RTTI(XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger)

protected:




private: 


XBOPTColStd_ShapeWithRank myKey1;
Standard_Integer myKey2;
Standard_Integer myValue;
TCollection_MapNodePtr myNext2;


};

#define TheKey XBOPTColStd_ShapeWithRank
#define TheKey_hxx <XBOPTColStd_ShapeWithRank.hxx>
#define TheItem Standard_Integer
#define TheItem_hxx <Standard_Integer.hxx>
#define Hasher XBOPTColStd_ShapeWithRankHasher
#define Hasher_hxx <XBOPTColStd_ShapeWithRankHasher.hxx>
#define TCollection_IndexedDataMapNode XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger
#define TCollection_IndexedDataMapNode_hxx <XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger.hxx>
#define Handle_TCollection_IndexedDataMapNode Handle_XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger
#define TCollection_IndexedDataMapNode_Type_() XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger_Type_()
#define TCollection_IndexedDataMap XBOPTColStd_IndexedDataMapOfSWRInteger
#define TCollection_IndexedDataMap_hxx <XBOPTColStd_IndexedDataMapOfSWRInteger.hxx>

#include <TCollection_IndexedDataMapNode.lxx>

#undef TheKey
#undef TheKey_hxx
#undef TheItem
#undef TheItem_hxx
#undef Hasher
#undef Hasher_hxx
#undef TCollection_IndexedDataMapNode
#undef TCollection_IndexedDataMapNode_hxx
#undef Handle_TCollection_IndexedDataMapNode
#undef TCollection_IndexedDataMapNode_Type_
#undef TCollection_IndexedDataMap
#undef TCollection_IndexedDataMap_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
