// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfPaveBlock_HeaderFile
#define _XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfPaveBlock_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfPaveBlock_HeaderFile
#include <Handle_XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfPaveBlock.hxx>
#endif

#ifndef _XBOPTools_PaveBlock_HeaderFile
#include <XBOPTools_PaveBlock.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _XBOPTools_IMapOfPaveBlock_HeaderFile
#include <XBOPTools_IMapOfPaveBlock.hxx>
#endif
#ifndef _TCollection_MapNodePtr_HeaderFile
#include <TCollection_MapNodePtr.hxx>
#endif
#ifndef _TCollection_MapNode_HeaderFile
#include <TCollection_MapNode.hxx>
#endif
class XBOPTools_PaveBlock;
class XBOPTools_IMapOfPaveBlock;
class XBOPTools_PaveBlockMapHasher;
class XBOPTools_IDMapOfPaveBlockIMapOfPaveBlock;



class XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfPaveBlock : public TCollection_MapNode {

public:

  
      XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfPaveBlock(const XBOPTools_PaveBlock& K1,const Standard_Integer K2,const XBOPTools_IMapOfPaveBlock& I,const TCollection_MapNodePtr& n1,const TCollection_MapNodePtr& n2);
  
        XBOPTools_PaveBlock& Key1() const;
  
        Standard_Integer& Key2() const;
  
        TCollection_MapNodePtr& Next2() const;
  
        XBOPTools_IMapOfPaveBlock& Value() const;




  DEFINE_STANDARD_RTTI(XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfPaveBlock)

protected:




private: 


XBOPTools_PaveBlock myKey1;
Standard_Integer myKey2;
XBOPTools_IMapOfPaveBlock myValue;
TCollection_MapNodePtr myNext2;


};

#define TheKey XBOPTools_PaveBlock
#define TheKey_hxx <XBOPTools_PaveBlock.hxx>
#define TheItem XBOPTools_IMapOfPaveBlock
#define TheItem_hxx <XBOPTools_IMapOfPaveBlock.hxx>
#define Hasher XBOPTools_PaveBlockMapHasher
#define Hasher_hxx <XBOPTools_PaveBlockMapHasher.hxx>
#define TCollection_IndexedDataMapNode XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfPaveBlock
#define TCollection_IndexedDataMapNode_hxx <XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfPaveBlock.hxx>
#define Handle_TCollection_IndexedDataMapNode Handle_XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfPaveBlock
#define TCollection_IndexedDataMapNode_Type_() XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfPaveBlock_Type_()
#define TCollection_IndexedDataMap XBOPTools_IDMapOfPaveBlockIMapOfPaveBlock
#define TCollection_IndexedDataMap_hxx <XBOPTools_IDMapOfPaveBlockIMapOfPaveBlock.hxx>

#include <TCollection_IndexedDataMapNode.lxx>

#undef TheKey
#undef TheKey_hxx
#undef TheItem
#undef TheItem_hxx
#undef Hasher
#undef Hasher_hxx
#undef TCollection_IndexedDataMapNode
#undef TCollection_IndexedDataMapNode_hxx
#undef Handle_TCollection_IndexedDataMapNode
#undef TCollection_IndexedDataMapNode_Type_
#undef TCollection_IndexedDataMap
#undef TCollection_IndexedDataMap_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
