// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOP_CheckStatus_HeaderFile
#define _XBOP_CheckStatus_HeaderFile


enum XBOP_CheckStatus {
XBOP_CheckUnknown,
XBOP_BadType,
XBOP_SelfIntersect,
XBOP_TooSmallEdge,
XBOP_NonRecoverableFace,
XBOP_IncompatibilityOfVertex,
XBOP_IncompatibilityOfEdge,
XBOP_IncompatibilityOfFace
};

#ifndef _Standard_PrimitiveTypes_HeaderFile
#include <Standard_PrimitiveTypes.hxx>
#endif

#endif
