// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOP_ListOfLoop_HeaderFile
#define _XBOP_ListOfLoop_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _Standard_Address_HeaderFile
#include <Standard_Address.hxx>
#endif
#ifndef _Handle_XBOP_Loop_HeaderFile
#include <Handle_XBOP_Loop.hxx>
#endif
#ifndef _Handle_XBOP_ListNodeOfListOfLoop_HeaderFile
#include <Handle_XBOP_ListNodeOfListOfLoop.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class Standard_NoSuchObject;
class XBOP_ListIteratorOfListOfLoop;
class XBOP_Loop;
class XBOP_ListNodeOfListOfLoop;



class XBOP_ListOfLoop  {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
  Standard_EXPORT   XBOP_ListOfLoop();
  
  Standard_EXPORT     void Assign(const XBOP_ListOfLoop& Other) ;
    void operator=(const XBOP_ListOfLoop& Other) 
{
  Assign(Other);
}
  
  Standard_EXPORT     Standard_Integer Extent() const;
  
  Standard_EXPORT     void Clear() ;
~XBOP_ListOfLoop()
{
  Clear();
}
  
        Standard_Boolean IsEmpty() const;
  
  Standard_EXPORT     void Prepend(const Handle(XBOP_Loop)& I) ;
  
  Standard_EXPORT     void Prepend(const Handle(XBOP_Loop)& I,XBOP_ListIteratorOfListOfLoop& theIt) ;
  
  Standard_EXPORT     void Prepend(XBOP_ListOfLoop& Other) ;
  
  Standard_EXPORT     void Append(const Handle(XBOP_Loop)& I) ;
  
  Standard_EXPORT     void Append(const Handle(XBOP_Loop)& I,XBOP_ListIteratorOfListOfLoop& theIt) ;
  
  Standard_EXPORT     void Append(XBOP_ListOfLoop& Other) ;
  
  Standard_EXPORT     Handle_XBOP_Loop& First() const;
  
  Standard_EXPORT     Handle_XBOP_Loop& Last() const;
  
  Standard_EXPORT     void RemoveFirst() ;
  
  Standard_EXPORT     void Remove(XBOP_ListIteratorOfListOfLoop& It) ;
  
  Standard_EXPORT     void InsertBefore(const Handle(XBOP_Loop)& I,XBOP_ListIteratorOfListOfLoop& It) ;
  
  Standard_EXPORT     void InsertBefore(XBOP_ListOfLoop& Other,XBOP_ListIteratorOfListOfLoop& It) ;
  
  Standard_EXPORT     void InsertAfter(const Handle(XBOP_Loop)& I,XBOP_ListIteratorOfListOfLoop& It) ;
  
  Standard_EXPORT     void InsertAfter(XBOP_ListOfLoop& Other,XBOP_ListIteratorOfListOfLoop& It) ;


friend class XBOP_ListIteratorOfListOfLoop;



protected:





private:

  
  Standard_EXPORT   XBOP_ListOfLoop(const XBOP_ListOfLoop& Other);


Standard_Address myFirst;
Standard_Address myLast;


};

#define Item Handle_XBOP_Loop
#define Item_hxx <XBOP_Loop.hxx>
#define TCollection_ListNode XBOP_ListNodeOfListOfLoop
#define TCollection_ListNode_hxx <XBOP_ListNodeOfListOfLoop.hxx>
#define TCollection_ListIterator XBOP_ListIteratorOfListOfLoop
#define TCollection_ListIterator_hxx <XBOP_ListIteratorOfListOfLoop.hxx>
#define Handle_TCollection_ListNode Handle_XBOP_ListNodeOfListOfLoop
#define TCollection_ListNode_Type_() XBOP_ListNodeOfListOfLoop_Type_()
#define TCollection_List XBOP_ListOfLoop
#define TCollection_List_hxx <XBOP_ListOfLoop.hxx>

#include <TCollection_List.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_ListNode
#undef TCollection_ListNode_hxx
#undef TCollection_ListIterator
#undef TCollection_ListIterator_hxx
#undef Handle_TCollection_ListNode
#undef TCollection_ListNode_Type_
#undef TCollection_List
#undef TCollection_List_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
