// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOP_ListNodeOfListOfEdgeInfo_HeaderFile
#define _XBOP_ListNodeOfListOfEdgeInfo_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_XBOP_ListNodeOfListOfEdgeInfo_HeaderFile
#include <Handle_XBOP_ListNodeOfListOfEdgeInfo.hxx>
#endif

#ifndef _XBOP_EdgeInfo_HeaderFile
#include <XBOP_EdgeInfo.hxx>
#endif
#ifndef _TCollection_MapNode_HeaderFile
#include <TCollection_MapNode.hxx>
#endif
#ifndef _TCollection_MapNodePtr_HeaderFile
#include <TCollection_MapNodePtr.hxx>
#endif
class XBOP_EdgeInfo;
class XBOP_ListOfEdgeInfo;
class XBOP_ListIteratorOfListOfEdgeInfo;



class XBOP_ListNodeOfListOfEdgeInfo : public TCollection_MapNode {

public:

  
      XBOP_ListNodeOfListOfEdgeInfo(const XBOP_EdgeInfo& I,const TCollection_MapNodePtr& n);
  
        XBOP_EdgeInfo& Value() const;




  DEFINE_STANDARD_RTTI(XBOP_ListNodeOfListOfEdgeInfo)

protected:




private: 


XBOP_EdgeInfo myValue;


};

#define Item XBOP_EdgeInfo
#define Item_hxx <XBOP_EdgeInfo.hxx>
#define TCollection_ListNode XBOP_ListNodeOfListOfEdgeInfo
#define TCollection_ListNode_hxx <XBOP_ListNodeOfListOfEdgeInfo.hxx>
#define TCollection_ListIterator XBOP_ListIteratorOfListOfEdgeInfo
#define TCollection_ListIterator_hxx <XBOP_ListIteratorOfListOfEdgeInfo.hxx>
#define Handle_TCollection_ListNode Handle_XBOP_ListNodeOfListOfEdgeInfo
#define TCollection_ListNode_Type_() XBOP_ListNodeOfListOfEdgeInfo_Type_()
#define TCollection_List XBOP_ListOfEdgeInfo
#define TCollection_List_hxx <XBOP_ListOfEdgeInfo.hxx>

#include <TCollection_ListNode.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_ListNode
#undef TCollection_ListNode_hxx
#undef TCollection_ListIterator
#undef TCollection_ListIterator_hxx
#undef Handle_TCollection_ListNode
#undef TCollection_ListNode_Type_
#undef TCollection_List
#undef TCollection_List_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
