// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOPTools_ListNodeOfListOfCheckResults_HeaderFile
#define _XBOPTools_ListNodeOfListOfCheckResults_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_XBOPTools_ListNodeOfListOfCheckResults_HeaderFile
#include <Handle_XBOPTools_ListNodeOfListOfCheckResults.hxx>
#endif

#ifndef _XBOPTools_CheckResult_HeaderFile
#include <XBOPTools_CheckResult.hxx>
#endif
#ifndef _TCollection_MapNode_HeaderFile
#include <TCollection_MapNode.hxx>
#endif
#ifndef _TCollection_MapNodePtr_HeaderFile
#include <TCollection_MapNodePtr.hxx>
#endif
class XBOPTools_CheckResult;
class XBOPTools_ListOfCheckResults;
class XBOPTools_ListIteratorOfListOfCheckResults;



class XBOPTools_ListNodeOfListOfCheckResults : public TCollection_MapNode {

public:

  
      XBOPTools_ListNodeOfListOfCheckResults(const XBOPTools_CheckResult& I,const TCollection_MapNodePtr& n);
  
        XBOPTools_CheckResult& Value() const;




  DEFINE_STANDARD_RTTI(XBOPTools_ListNodeOfListOfCheckResults)

protected:




private: 


XBOPTools_CheckResult myValue;


};

#define Item XBOPTools_CheckResult
#define Item_hxx <XBOPTools_CheckResult.hxx>
#define TCollection_ListNode XBOPTools_ListNodeOfListOfCheckResults
#define TCollection_ListNode_hxx <XBOPTools_ListNodeOfListOfCheckResults.hxx>
#define TCollection_ListIterator XBOPTools_ListIteratorOfListOfCheckResults
#define TCollection_ListIterator_hxx <XBOPTools_ListIteratorOfListOfCheckResults.hxx>
#define Handle_TCollection_ListNode Handle_XBOPTools_ListNodeOfListOfCheckResults
#define TCollection_ListNode_Type_() XBOPTools_ListNodeOfListOfCheckResults_Type_()
#define TCollection_List XBOPTools_ListOfCheckResults
#define TCollection_List_hxx <XBOPTools_ListOfCheckResults.hxx>

#include <TCollection_ListNode.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_ListNode
#undef TCollection_ListNode_hxx
#undef TCollection_ListIterator
#undef TCollection_ListIterator_hxx
#undef Handle_TCollection_ListNode
#undef TCollection_ListNode_Type_
#undef TCollection_List
#undef TCollection_List_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
