// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOPTools_SequenceOfCurves_HeaderFile
#define _XBOPTools_SequenceOfCurves_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _TCollection_BaseSequence_HeaderFile
#include <TCollection_BaseSequence.hxx>
#endif
#ifndef _Handle_XBOPTools_SequenceNodeOfSequenceOfCurves_HeaderFile
#include <Handle_XBOPTools_SequenceNodeOfSequenceOfCurves.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
class Standard_NoSuchObject;
class Standard_OutOfRange;
class XBOPTools_Curve;
class XBOPTools_SequenceNodeOfSequenceOfCurves;



class XBOPTools_SequenceOfCurves  : public TCollection_BaseSequence {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
      XBOPTools_SequenceOfCurves();
  
  Standard_EXPORT     void Clear() ;
~XBOPTools_SequenceOfCurves()
{
  Clear();
}
  
  Standard_EXPORT    const XBOPTools_SequenceOfCurves& Assign(const XBOPTools_SequenceOfCurves& Other) ;
   const XBOPTools_SequenceOfCurves& operator =(const XBOPTools_SequenceOfCurves& Other) 
{
  return Assign(Other);
}
  
  Standard_EXPORT     void Append(const XBOPTools_Curve& T) ;
  
        void Append(XBOPTools_SequenceOfCurves& S) ;
  
  Standard_EXPORT     void Prepend(const XBOPTools_Curve& T) ;
  
        void Prepend(XBOPTools_SequenceOfCurves& S) ;
  
        void InsertBefore(const Standard_Integer Index,const XBOPTools_Curve& T) ;
  
        void InsertBefore(const Standard_Integer Index,XBOPTools_SequenceOfCurves& S) ;
  
  Standard_EXPORT     void InsertAfter(const Standard_Integer Index,const XBOPTools_Curve& T) ;
  
        void InsertAfter(const Standard_Integer Index,XBOPTools_SequenceOfCurves& S) ;
  
  Standard_EXPORT    const XBOPTools_Curve& First() const;
  
  Standard_EXPORT    const XBOPTools_Curve& Last() const;
  
        void Split(const Standard_Integer Index,XBOPTools_SequenceOfCurves& Sub) ;
  
  Standard_EXPORT    const XBOPTools_Curve& Value(const Standard_Integer Index) const;
   const XBOPTools_Curve& operator()(const Standard_Integer Index) const
{
  return Value(Index);
}
  
  Standard_EXPORT     void SetValue(const Standard_Integer Index,const XBOPTools_Curve& I) ;
  
  Standard_EXPORT     XBOPTools_Curve& ChangeValue(const Standard_Integer Index) ;
    XBOPTools_Curve& operator()(const Standard_Integer Index) 
{
  return ChangeValue(Index);
}
  
  Standard_EXPORT     void Remove(const Standard_Integer Index) ;
  
  Standard_EXPORT     void Remove(const Standard_Integer FromIndex,const Standard_Integer ToIndex) ;





protected:





private:

  
  Standard_EXPORT   XBOPTools_SequenceOfCurves(const XBOPTools_SequenceOfCurves& Other);




};

#define SeqItem XBOPTools_Curve
#define SeqItem_hxx <XBOPTools_Curve.hxx>
#define TCollection_SequenceNode XBOPTools_SequenceNodeOfSequenceOfCurves
#define TCollection_SequenceNode_hxx <XBOPTools_SequenceNodeOfSequenceOfCurves.hxx>
#define Handle_TCollection_SequenceNode Handle_XBOPTools_SequenceNodeOfSequenceOfCurves
#define TCollection_SequenceNode_Type_() XBOPTools_SequenceNodeOfSequenceOfCurves_Type_()
#define TCollection_Sequence XBOPTools_SequenceOfCurves
#define TCollection_Sequence_hxx <XBOPTools_SequenceOfCurves.hxx>

#include <TCollection_Sequence.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
