// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOPTools_ListNodeOfListOfPaveBlock_HeaderFile
#define _XBOPTools_ListNodeOfListOfPaveBlock_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_XBOPTools_ListNodeOfListOfPaveBlock_HeaderFile
#include <Handle_XBOPTools_ListNodeOfListOfPaveBlock.hxx>
#endif

#ifndef _XBOPTools_PaveBlock_HeaderFile
#include <XBOPTools_PaveBlock.hxx>
#endif
#ifndef _TCollection_MapNode_HeaderFile
#include <TCollection_MapNode.hxx>
#endif
#ifndef _TCollection_MapNodePtr_HeaderFile
#include <TCollection_MapNodePtr.hxx>
#endif
class XBOPTools_PaveBlock;
class XBOPTools_ListOfPaveBlock;
class XBOPTools_ListIteratorOfListOfPaveBlock;



class XBOPTools_ListNodeOfListOfPaveBlock : public TCollection_MapNode {

public:

  
      XBOPTools_ListNodeOfListOfPaveBlock(const XBOPTools_PaveBlock& I,const TCollection_MapNodePtr& n);
  
        XBOPTools_PaveBlock& Value() const;




  DEFINE_STANDARD_RTTI(XBOPTools_ListNodeOfListOfPaveBlock)

protected:




private: 


XBOPTools_PaveBlock myValue;


};

#define Item XBOPTools_PaveBlock
#define Item_hxx <XBOPTools_PaveBlock.hxx>
#define TCollection_ListNode XBOPTools_ListNodeOfListOfPaveBlock
#define TCollection_ListNode_hxx <XBOPTools_ListNodeOfListOfPaveBlock.hxx>
#define TCollection_ListIterator XBOPTools_ListIteratorOfListOfPaveBlock
#define TCollection_ListIterator_hxx <XBOPTools_ListIteratorOfListOfPaveBlock.hxx>
#define Handle_TCollection_ListNode Handle_XBOPTools_ListNodeOfListOfPaveBlock
#define TCollection_ListNode_Type_() XBOPTools_ListNodeOfListOfPaveBlock_Type_()
#define TCollection_List XBOPTools_ListOfPaveBlock
#define TCollection_List_hxx <XBOPTools_ListOfPaveBlock.hxx>

#include <TCollection_ListNode.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_ListNode
#undef TCollection_ListNode_hxx
#undef TCollection_ListIterator
#undef TCollection_ListIterator_hxx
#undef Handle_TCollection_ListNode
#undef TCollection_ListNode_Type_
#undef TCollection_List
#undef TCollection_List_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
