// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOPTools_ListOfCoupleOfInteger_HeaderFile
#define _XBOPTools_ListOfCoupleOfInteger_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _Standard_Address_HeaderFile
#include <Standard_Address.hxx>
#endif
#ifndef _Handle_XBOPTools_ListNodeOfListOfCoupleOfInteger_HeaderFile
#include <Handle_XBOPTools_ListNodeOfListOfCoupleOfInteger.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class Standard_NoSuchObject;
class XBOPTools_ListIteratorOfListOfCoupleOfInteger;
class XBOPTools_CoupleOfInteger;
class XBOPTools_ListNodeOfListOfCoupleOfInteger;



class XBOPTools_ListOfCoupleOfInteger  {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
  Standard_EXPORT   XBOPTools_ListOfCoupleOfInteger();
  
  Standard_EXPORT     void Assign(const XBOPTools_ListOfCoupleOfInteger& Other) ;
    void operator=(const XBOPTools_ListOfCoupleOfInteger& Other) 
{
  Assign(Other);
}
  
  Standard_EXPORT     Standard_Integer Extent() const;
  
  Standard_EXPORT     void Clear() ;
~XBOPTools_ListOfCoupleOfInteger()
{
  Clear();
}
  
        Standard_Boolean IsEmpty() const;
  
  Standard_EXPORT     void Prepend(const XBOPTools_CoupleOfInteger& I) ;
  
  Standard_EXPORT     void Prepend(const XBOPTools_CoupleOfInteger& I,XBOPTools_ListIteratorOfListOfCoupleOfInteger& theIt) ;
  
  Standard_EXPORT     void Prepend(XBOPTools_ListOfCoupleOfInteger& Other) ;
  
  Standard_EXPORT     void Append(const XBOPTools_CoupleOfInteger& I) ;
  
  Standard_EXPORT     void Append(const XBOPTools_CoupleOfInteger& I,XBOPTools_ListIteratorOfListOfCoupleOfInteger& theIt) ;
  
  Standard_EXPORT     void Append(XBOPTools_ListOfCoupleOfInteger& Other) ;
  
  Standard_EXPORT     XBOPTools_CoupleOfInteger& First() const;
  
  Standard_EXPORT     XBOPTools_CoupleOfInteger& Last() const;
  
  Standard_EXPORT     void RemoveFirst() ;
  
  Standard_EXPORT     void Remove(XBOPTools_ListIteratorOfListOfCoupleOfInteger& It) ;
  
  Standard_EXPORT     void InsertBefore(const XBOPTools_CoupleOfInteger& I,XBOPTools_ListIteratorOfListOfCoupleOfInteger& It) ;
  
  Standard_EXPORT     void InsertBefore(XBOPTools_ListOfCoupleOfInteger& Other,XBOPTools_ListIteratorOfListOfCoupleOfInteger& It) ;
  
  Standard_EXPORT     void InsertAfter(const XBOPTools_CoupleOfInteger& I,XBOPTools_ListIteratorOfListOfCoupleOfInteger& It) ;
  
  Standard_EXPORT     void InsertAfter(XBOPTools_ListOfCoupleOfInteger& Other,XBOPTools_ListIteratorOfListOfCoupleOfInteger& It) ;


friend class XBOPTools_ListIteratorOfListOfCoupleOfInteger;



protected:





private:

  
  Standard_EXPORT   XBOPTools_ListOfCoupleOfInteger(const XBOPTools_ListOfCoupleOfInteger& Other);


Standard_Address myFirst;
Standard_Address myLast;


};

#define Item XBOPTools_CoupleOfInteger
#define Item_hxx <XBOPTools_CoupleOfInteger.hxx>
#define TCollection_ListNode XBOPTools_ListNodeOfListOfCoupleOfInteger
#define TCollection_ListNode_hxx <XBOPTools_ListNodeOfListOfCoupleOfInteger.hxx>
#define TCollection_ListIterator XBOPTools_ListIteratorOfListOfCoupleOfInteger
#define TCollection_ListIterator_hxx <XBOPTools_ListIteratorOfListOfCoupleOfInteger.hxx>
#define Handle_TCollection_ListNode Handle_XBOPTools_ListNodeOfListOfCoupleOfInteger
#define TCollection_ListNode_Type_() XBOPTools_ListNodeOfListOfCoupleOfInteger_Type_()
#define TCollection_List XBOPTools_ListOfCoupleOfInteger
#define TCollection_List_hxx <XBOPTools_ListOfCoupleOfInteger.hxx>

#include <TCollection_List.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_ListNode
#undef TCollection_ListNode_hxx
#undef TCollection_ListIterator
#undef TCollection_ListIterator_hxx
#undef Handle_TCollection_ListNode
#undef TCollection_ListNode_Type_
#undef TCollection_List
#undef TCollection_List_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
