// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOP_LoopEnum_HeaderFile
#define _XBOP_LoopEnum_HeaderFile


enum XBOP_LoopEnum {
XBOP_ANYLOOP,
XBOP_BOUNDARY,
XBOP_BLOCK
};

#ifndef _Standard_PrimitiveTypes_HeaderFile
#include <Standard_PrimitiveTypes.hxx>
#endif

#endif
