// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOP_PBuilder_HeaderFile
#define _XBOP_PBuilder_HeaderFile

class XBOP_Builder;

typedef XBOP_Builder* XBOP_PBuilder;

#endif
