// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOPTools_IDMapOfPaveBlockIMapOfPaveBlock_HeaderFile
#define _XBOPTools_IDMapOfPaveBlockIMapOfPaveBlock_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _TCollection_BasicMap_HeaderFile
#include <TCollection_BasicMap.hxx>
#endif
#ifndef _Handle_XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfPaveBlock_HeaderFile
#include <Handle_XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfPaveBlock.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
#ifndef _Standard_Address_HeaderFile
#include <Standard_Address.hxx>
#endif
class Standard_DomainError;
class Standard_OutOfRange;
class Standard_NoSuchObject;
class XBOPTools_PaveBlock;
class XBOPTools_IMapOfPaveBlock;
class XBOPTools_PaveBlockMapHasher;
class XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfPaveBlock;



class XBOPTools_IDMapOfPaveBlockIMapOfPaveBlock  : public TCollection_BasicMap {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
  Standard_EXPORT   XBOPTools_IDMapOfPaveBlockIMapOfPaveBlock(const Standard_Integer NbBuckets = 1);
  
  Standard_EXPORT     XBOPTools_IDMapOfPaveBlockIMapOfPaveBlock& Assign(const XBOPTools_IDMapOfPaveBlockIMapOfPaveBlock& Other) ;
    XBOPTools_IDMapOfPaveBlockIMapOfPaveBlock& operator =(const XBOPTools_IDMapOfPaveBlockIMapOfPaveBlock& Other) 
{
  return Assign(Other);
}
  
  Standard_EXPORT     void ReSize(const Standard_Integer NbBuckets) ;
  
  Standard_EXPORT     void Clear() ;
~XBOPTools_IDMapOfPaveBlockIMapOfPaveBlock()
{
  Clear();
}
  
  Standard_EXPORT     Standard_Integer Add(const XBOPTools_PaveBlock& K,const XBOPTools_IMapOfPaveBlock& I) ;
  
  Standard_EXPORT     void Substitute(const Standard_Integer I,const XBOPTools_PaveBlock& K,const XBOPTools_IMapOfPaveBlock& T) ;
  
  Standard_EXPORT     void RemoveLast() ;
  
  Standard_EXPORT     Standard_Boolean Contains(const XBOPTools_PaveBlock& K) const;
  
  Standard_EXPORT    const XBOPTools_PaveBlock& FindKey(const Standard_Integer I) const;
  
  Standard_EXPORT    const XBOPTools_IMapOfPaveBlock& FindFromIndex(const Standard_Integer I) const;
   const XBOPTools_IMapOfPaveBlock& operator ()(const Standard_Integer I) const
{
  return FindFromIndex(I);
}
  
  Standard_EXPORT     XBOPTools_IMapOfPaveBlock& ChangeFromIndex(const Standard_Integer I) ;
    XBOPTools_IMapOfPaveBlock& operator ()(const Standard_Integer I) 
{
  return ChangeFromIndex(I);
}
  
  Standard_EXPORT     Standard_Integer FindIndex(const XBOPTools_PaveBlock& K) const;
  
  Standard_EXPORT    const XBOPTools_IMapOfPaveBlock& FindFromKey(const XBOPTools_PaveBlock& K) const;
  
  Standard_EXPORT     XBOPTools_IMapOfPaveBlock& ChangeFromKey(const XBOPTools_PaveBlock& K) ;
  
  Standard_EXPORT     Standard_Address FindFromKey1(const XBOPTools_PaveBlock& K) const;
  
  Standard_EXPORT     Standard_Address ChangeFromKey1(const XBOPTools_PaveBlock& K) ;





protected:





private:

  
  Standard_EXPORT   XBOPTools_IDMapOfPaveBlockIMapOfPaveBlock(const XBOPTools_IDMapOfPaveBlockIMapOfPaveBlock& Other);




};





// other Inline functions and methods (like "C++: function call" methods)


#endif
