// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOP_ShellShell_HeaderFile
#define _XBOP_ShellShell_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _XBOP_ShellSolid_HeaderFile
#include <XBOP_ShellSolid.hxx>
#endif
class XBOPTools_DSFiller;



//!        Performs  Boolean Operations (BO) <br>
//!        Common,Cut,Fuse for arguments that <br>
//!        are of type shell/shell <br>
//! <br>
class XBOP_ShellShell  : public XBOP_ShellSolid {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
//! Empty constructor; <br>
  Standard_EXPORT   XBOP_ShellShell();
  
//! see base  classes, please <br>
  Standard_EXPORT   virtual  void DoWithFiller(const XBOPTools_DSFiller& aDSF) ;
  
//! Destructor <br>
  Standard_EXPORT   virtual  void Destroy() ;
Standard_EXPORT virtual ~XBOP_ShellShell(){Destroy();}
  
//! see base  classes, please <br>
  Standard_EXPORT   virtual  void BuildResult() ;
  
//! see base  classes, please <br>
  Standard_EXPORT   virtual  void DoNewFaces() ;





protected:





private:





};





// other Inline functions and methods (like "C++: function call" methods)


#endif
