// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOPTools_InterferencePool_HeaderFile
#define _XBOPTools_InterferencePool_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _XBooleanOperations_PShapesDataStructure_HeaderFile
#include <XBooleanOperations_PShapesDataStructure.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _XBOPTools_CArray1OfInterferenceLine_HeaderFile
#include <XBOPTools_CArray1OfInterferenceLine.hxx>
#endif
#ifndef _XBOPTools_CArray1OfSSInterference_HeaderFile
#include <XBOPTools_CArray1OfSSInterference.hxx>
#endif
#ifndef _XBOPTools_CArray1OfESInterference_HeaderFile
#include <XBOPTools_CArray1OfESInterference.hxx>
#endif
#ifndef _XBOPTools_CArray1OfVSInterference_HeaderFile
#include <XBOPTools_CArray1OfVSInterference.hxx>
#endif
#ifndef _XBOPTools_CArray1OfEEInterference_HeaderFile
#include <XBOPTools_CArray1OfEEInterference.hxx>
#endif
#ifndef _XBOPTools_CArray1OfVEInterference_HeaderFile
#include <XBOPTools_CArray1OfVEInterference.hxx>
#endif
#ifndef _XBOPTools_CArray1OfVVInterference_HeaderFile
#include <XBOPTools_CArray1OfVVInterference.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
#ifndef _XBooleanOperations_KindOfInterference_HeaderFile
#include <XBooleanOperations_KindOfInterference.hxx>
#endif
#ifndef _XBOPTools_PShapeShapeInterference_HeaderFile
#include <XBOPTools_PShapeShapeInterference.hxx>
#endif
class XBooleanOperations_ShapesDataStructure;
class XBOPTools_CArray1OfInterferenceLine;
class XBOPTools_CArray1OfSSInterference;
class XBOPTools_CArray1OfESInterference;
class XBOPTools_CArray1OfVSInterference;
class XBOPTools_CArray1OfEEInterference;
class XBOPTools_CArray1OfVEInterference;
class XBOPTools_CArray1OfVVInterference;



//!  Class for storing information about <br>
//! results of all interferences for all shapes <br>
class XBOPTools_InterferencePool  {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
//! Empty constructor <br>
  Standard_EXPORT   XBOPTools_InterferencePool();
  
//! Constructor <br>
  Standard_EXPORT   XBOPTools_InterferencePool(const XBooleanOperations_ShapesDataStructure& aDS);
  
//! Modifier <br>
  Standard_EXPORT     void SetDS(const XBooleanOperations_ShapesDataStructure& aDS) ;
  
//! Selector <br>
  Standard_EXPORT     XBooleanOperations_PShapesDataStructure DS() const;
  
//! Returns  TRUE if the shape with DS_index  <anInd> <br>
//! has at least one  interference with non-empty result <br>
  Standard_EXPORT     Standard_Boolean HasInterference(const Standard_Integer anInd) const;
  
//! Returns  TRUE if the interference between shapes <br>
//! <anInd1> and <anInd2> has already been computed. <br>
  Standard_EXPORT     Standard_Boolean IsComputed(const Standard_Integer anInd1,const Standard_Integer anInd2) const;
  
//! Sorts types of shapes <anInd1> and <anInd2> in increasing order <br>
  Standard_EXPORT     void SortTypes(Standard_Integer& anInd1,Standard_Integer& anInd2) const;
  
//! Gets the type of interference in accordance with the types of <br>
//! shapes  <anInd1> and <anInd2> <br>
  Standard_EXPORT     XBooleanOperations_KindOfInterference InterferenceType(const Standard_Integer anInd1,const Standard_Integer anInd2) const;
  
//! Adds the info about interference in InterferenceLine-s for <br>
//! shapes  <anInd1> and <anInd2> <br>
  Standard_EXPORT     void AddInterference(const Standard_Integer anInd1,const Standard_Integer anInd2,const XBooleanOperations_KindOfInterference aType,const Standard_Integer anIndex) ;
  
//! Returns the reference to complete array of interference line-s <br>
  Standard_EXPORT    const XBOPTools_CArray1OfInterferenceLine& InterferenceTable() const;
  
//! Returns the reference to array Of F/F interferences <br>
  Standard_EXPORT     XBOPTools_CArray1OfSSInterference& SSInterferences() ;
  
//! Returns the reference to array Of E/F interferences <br>
  Standard_EXPORT     XBOPTools_CArray1OfESInterference& ESInterferences() ;
  
//! Returns the reference to array Of V/F interferences <br>
  Standard_EXPORT     XBOPTools_CArray1OfVSInterference& VSInterferences() ;
  
//! Returns the reference to arrray Of E/E interferences <br>
  Standard_EXPORT     XBOPTools_CArray1OfEEInterference& EEInterferences() ;
  
//! Returns the reference to arrray Of  V/E interferences <br>
  Standard_EXPORT     XBOPTools_CArray1OfVEInterference& VEInterferences() ;
  
//! Returns the reference to arrray Of  V/V interferences <br>
  Standard_EXPORT     XBOPTools_CArray1OfVVInterference& VVInterferences() ;
  
  Standard_EXPORT    const XBOPTools_CArray1OfSSInterference& SSInterfs() const;
  
  Standard_EXPORT    const XBOPTools_CArray1OfESInterference& ESInterfs() const;
  
  Standard_EXPORT    const XBOPTools_CArray1OfVSInterference& VSInterfs() const;
  
  Standard_EXPORT    const XBOPTools_CArray1OfEEInterference& EEInterfs() const;
  
  Standard_EXPORT    const XBOPTools_CArray1OfVEInterference& VEInterfs() const;
  
  Standard_EXPORT    const XBOPTools_CArray1OfVVInterference& VVInterfs() const;
  
  Standard_EXPORT     XBOPTools_PShapeShapeInterference GetInterference(const Standard_Integer anIndex,const XBooleanOperations_KindOfInterference aType) const;





protected:





private:



XBooleanOperations_PShapesDataStructure myDS;
Standard_Integer myNbSourceShapes;
XBOPTools_CArray1OfInterferenceLine myInterferenceTable;
XBOPTools_CArray1OfSSInterference mySSInterferences;
XBOPTools_CArray1OfESInterference myESInterferences;
XBOPTools_CArray1OfVSInterference myVSInterferences;
XBOPTools_CArray1OfEEInterference myEEInterferences;
XBOPTools_CArray1OfVEInterference myVEInterferences;
XBOPTools_CArray1OfVVInterference myVVInterferences;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
