// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XBOPTools_ListOfCheckResults_HeaderFile
#define _XBOPTools_ListOfCheckResults_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _Standard_Address_HeaderFile
#include <Standard_Address.hxx>
#endif
#ifndef _Handle_XBOPTools_ListNodeOfListOfCheckResults_HeaderFile
#include <Handle_XBOPTools_ListNodeOfListOfCheckResults.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class Standard_NoSuchObject;
class XBOPTools_ListIteratorOfListOfCheckResults;
class XBOPTools_CheckResult;
class XBOPTools_ListNodeOfListOfCheckResults;



class XBOPTools_ListOfCheckResults  {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
  Standard_EXPORT   XBOPTools_ListOfCheckResults();
  
  Standard_EXPORT     void Assign(const XBOPTools_ListOfCheckResults& Other) ;
    void operator=(const XBOPTools_ListOfCheckResults& Other) 
{
  Assign(Other);
}
  
  Standard_EXPORT     Standard_Integer Extent() const;
  
  Standard_EXPORT     void Clear() ;
~XBOPTools_ListOfCheckResults()
{
  Clear();
}
  
        Standard_Boolean IsEmpty() const;
  
  Standard_EXPORT     void Prepend(const XBOPTools_CheckResult& I) ;
  
  Standard_EXPORT     void Prepend(const XBOPTools_CheckResult& I,XBOPTools_ListIteratorOfListOfCheckResults& theIt) ;
  
  Standard_EXPORT     void Prepend(XBOPTools_ListOfCheckResults& Other) ;
  
  Standard_EXPORT     void Append(const XBOPTools_CheckResult& I) ;
  
  Standard_EXPORT     void Append(const XBOPTools_CheckResult& I,XBOPTools_ListIteratorOfListOfCheckResults& theIt) ;
  
  Standard_EXPORT     void Append(XBOPTools_ListOfCheckResults& Other) ;
  
  Standard_EXPORT     XBOPTools_CheckResult& First() const;
  
  Standard_EXPORT     XBOPTools_CheckResult& Last() const;
  
  Standard_EXPORT     void RemoveFirst() ;
  
  Standard_EXPORT     void Remove(XBOPTools_ListIteratorOfListOfCheckResults& It) ;
  
  Standard_EXPORT     void InsertBefore(const XBOPTools_CheckResult& I,XBOPTools_ListIteratorOfListOfCheckResults& It) ;
  
  Standard_EXPORT     void InsertBefore(XBOPTools_ListOfCheckResults& Other,XBOPTools_ListIteratorOfListOfCheckResults& It) ;
  
  Standard_EXPORT     void InsertAfter(const XBOPTools_CheckResult& I,XBOPTools_ListIteratorOfListOfCheckResults& It) ;
  
  Standard_EXPORT     void InsertAfter(XBOPTools_ListOfCheckResults& Other,XBOPTools_ListIteratorOfListOfCheckResults& It) ;


friend class XBOPTools_ListIteratorOfListOfCheckResults;



protected:





private:

  
  Standard_EXPORT   XBOPTools_ListOfCheckResults(const XBOPTools_ListOfCheckResults& Other);


Standard_Address myFirst;
Standard_Address myLast;


};

#define Item XBOPTools_CheckResult
#define Item_hxx <XBOPTools_CheckResult.hxx>
#define TCollection_ListNode XBOPTools_ListNodeOfListOfCheckResults
#define TCollection_ListNode_hxx <XBOPTools_ListNodeOfListOfCheckResults.hxx>
#define TCollection_ListIterator XBOPTools_ListIteratorOfListOfCheckResults
#define TCollection_ListIterator_hxx <XBOPTools_ListIteratorOfListOfCheckResults.hxx>
#define Handle_TCollection_ListNode Handle_XBOPTools_ListNodeOfListOfCheckResults
#define TCollection_ListNode_Type_() XBOPTools_ListNodeOfListOfCheckResults_Type_()
#define TCollection_List XBOPTools_ListOfCheckResults
#define TCollection_List_hxx <XBOPTools_ListOfCheckResults.hxx>

#include <TCollection_List.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_ListNode
#undef TCollection_ListNode_hxx
#undef TCollection_ListIterator
#undef TCollection_ListIterator_hxx
#undef Handle_TCollection_ListNode
#undef TCollection_ListNode_Type_
#undef TCollection_List
#undef TCollection_List_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
