// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XIntTools_ListOfCurveRangeSample_HeaderFile
#define _XIntTools_ListOfCurveRangeSample_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _Standard_Address_HeaderFile
#include <Standard_Address.hxx>
#endif
#ifndef _Handle_XIntTools_ListNodeOfListOfCurveRangeSample_HeaderFile
#include <Handle_XIntTools_ListNodeOfListOfCurveRangeSample.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class Standard_NoSuchObject;
class XIntTools_ListIteratorOfListOfCurveRangeSample;
class XIntTools_CurveRangeSample;
class XIntTools_ListNodeOfListOfCurveRangeSample;



class XIntTools_ListOfCurveRangeSample  {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
  Standard_EXPORT   XIntTools_ListOfCurveRangeSample();
  
  Standard_EXPORT     void Assign(const XIntTools_ListOfCurveRangeSample& Other) ;
    void operator=(const XIntTools_ListOfCurveRangeSample& Other) 
{
  Assign(Other);
}
  
  Standard_EXPORT     Standard_Integer Extent() const;
  
  Standard_EXPORT     void Clear() ;
~XIntTools_ListOfCurveRangeSample()
{
  Clear();
}
  
        Standard_Boolean IsEmpty() const;
  
  Standard_EXPORT     void Prepend(const XIntTools_CurveRangeSample& I) ;
  
  Standard_EXPORT     void Prepend(const XIntTools_CurveRangeSample& I,XIntTools_ListIteratorOfListOfCurveRangeSample& theIt) ;
  
  Standard_EXPORT     void Prepend(XIntTools_ListOfCurveRangeSample& Other) ;
  
  Standard_EXPORT     void Append(const XIntTools_CurveRangeSample& I) ;
  
  Standard_EXPORT     void Append(const XIntTools_CurveRangeSample& I,XIntTools_ListIteratorOfListOfCurveRangeSample& theIt) ;
  
  Standard_EXPORT     void Append(XIntTools_ListOfCurveRangeSample& Other) ;
  
  Standard_EXPORT     XIntTools_CurveRangeSample& First() const;
  
  Standard_EXPORT     XIntTools_CurveRangeSample& Last() const;
  
  Standard_EXPORT     void RemoveFirst() ;
  
  Standard_EXPORT     void Remove(XIntTools_ListIteratorOfListOfCurveRangeSample& It) ;
  
  Standard_EXPORT     void InsertBefore(const XIntTools_CurveRangeSample& I,XIntTools_ListIteratorOfListOfCurveRangeSample& It) ;
  
  Standard_EXPORT     void InsertBefore(XIntTools_ListOfCurveRangeSample& Other,XIntTools_ListIteratorOfListOfCurveRangeSample& It) ;
  
  Standard_EXPORT     void InsertAfter(const XIntTools_CurveRangeSample& I,XIntTools_ListIteratorOfListOfCurveRangeSample& It) ;
  
  Standard_EXPORT     void InsertAfter(XIntTools_ListOfCurveRangeSample& Other,XIntTools_ListIteratorOfListOfCurveRangeSample& It) ;


friend class XIntTools_ListIteratorOfListOfCurveRangeSample;



protected:





private:

  
  Standard_EXPORT   XIntTools_ListOfCurveRangeSample(const XIntTools_ListOfCurveRangeSample& Other);


Standard_Address myFirst;
Standard_Address myLast;


};

#define Item XIntTools_CurveRangeSample
#define Item_hxx <XIntTools_CurveRangeSample.hxx>
#define TCollection_ListNode XIntTools_ListNodeOfListOfCurveRangeSample
#define TCollection_ListNode_hxx <XIntTools_ListNodeOfListOfCurveRangeSample.hxx>
#define TCollection_ListIterator XIntTools_ListIteratorOfListOfCurveRangeSample
#define TCollection_ListIterator_hxx <XIntTools_ListIteratorOfListOfCurveRangeSample.hxx>
#define Handle_TCollection_ListNode Handle_XIntTools_ListNodeOfListOfCurveRangeSample
#define TCollection_ListNode_Type_() XIntTools_ListNodeOfListOfCurveRangeSample_Type_()
#define TCollection_List XIntTools_ListOfCurveRangeSample
#define TCollection_List_hxx <XIntTools_ListOfCurveRangeSample.hxx>

#include <TCollection_List.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_ListNode
#undef TCollection_ListNode_hxx
#undef TCollection_ListIterator
#undef TCollection_ListIterator_hxx
#undef Handle_TCollection_ListNode
#undef TCollection_ListNode_Type_
#undef TCollection_List
#undef TCollection_List_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
