// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XIntTools_ListOfSurfaceRangeSample_HeaderFile
#define _XIntTools_ListOfSurfaceRangeSample_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _Standard_Address_HeaderFile
#include <Standard_Address.hxx>
#endif
#ifndef _Handle_XIntTools_ListNodeOfListOfSurfaceRangeSample_HeaderFile
#include <Handle_XIntTools_ListNodeOfListOfSurfaceRangeSample.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class Standard_NoSuchObject;
class XIntTools_ListIteratorOfListOfSurfaceRangeSample;
class XIntTools_SurfaceRangeSample;
class XIntTools_ListNodeOfListOfSurfaceRangeSample;



class XIntTools_ListOfSurfaceRangeSample  {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
  Standard_EXPORT   XIntTools_ListOfSurfaceRangeSample();
  
  Standard_EXPORT     void Assign(const XIntTools_ListOfSurfaceRangeSample& Other) ;
    void operator=(const XIntTools_ListOfSurfaceRangeSample& Other) 
{
  Assign(Other);
}
  
  Standard_EXPORT     Standard_Integer Extent() const;
  
  Standard_EXPORT     void Clear() ;
~XIntTools_ListOfSurfaceRangeSample()
{
  Clear();
}
  
        Standard_Boolean IsEmpty() const;
  
  Standard_EXPORT     void Prepend(const XIntTools_SurfaceRangeSample& I) ;
  
  Standard_EXPORT     void Prepend(const XIntTools_SurfaceRangeSample& I,XIntTools_ListIteratorOfListOfSurfaceRangeSample& theIt) ;
  
  Standard_EXPORT     void Prepend(XIntTools_ListOfSurfaceRangeSample& Other) ;
  
  Standard_EXPORT     void Append(const XIntTools_SurfaceRangeSample& I) ;
  
  Standard_EXPORT     void Append(const XIntTools_SurfaceRangeSample& I,XIntTools_ListIteratorOfListOfSurfaceRangeSample& theIt) ;
  
  Standard_EXPORT     void Append(XIntTools_ListOfSurfaceRangeSample& Other) ;
  
  Standard_EXPORT     XIntTools_SurfaceRangeSample& First() const;
  
  Standard_EXPORT     XIntTools_SurfaceRangeSample& Last() const;
  
  Standard_EXPORT     void RemoveFirst() ;
  
  Standard_EXPORT     void Remove(XIntTools_ListIteratorOfListOfSurfaceRangeSample& It) ;
  
  Standard_EXPORT     void InsertBefore(const XIntTools_SurfaceRangeSample& I,XIntTools_ListIteratorOfListOfSurfaceRangeSample& It) ;
  
  Standard_EXPORT     void InsertBefore(XIntTools_ListOfSurfaceRangeSample& Other,XIntTools_ListIteratorOfListOfSurfaceRangeSample& It) ;
  
  Standard_EXPORT     void InsertAfter(const XIntTools_SurfaceRangeSample& I,XIntTools_ListIteratorOfListOfSurfaceRangeSample& It) ;
  
  Standard_EXPORT     void InsertAfter(XIntTools_ListOfSurfaceRangeSample& Other,XIntTools_ListIteratorOfListOfSurfaceRangeSample& It) ;


friend class XIntTools_ListIteratorOfListOfSurfaceRangeSample;



protected:





private:

  
  Standard_EXPORT   XIntTools_ListOfSurfaceRangeSample(const XIntTools_ListOfSurfaceRangeSample& Other);


Standard_Address myFirst;
Standard_Address myLast;


};

#define Item XIntTools_SurfaceRangeSample
#define Item_hxx <XIntTools_SurfaceRangeSample.hxx>
#define TCollection_ListNode XIntTools_ListNodeOfListOfSurfaceRangeSample
#define TCollection_ListNode_hxx <XIntTools_ListNodeOfListOfSurfaceRangeSample.hxx>
#define TCollection_ListIterator XIntTools_ListIteratorOfListOfSurfaceRangeSample
#define TCollection_ListIterator_hxx <XIntTools_ListIteratorOfListOfSurfaceRangeSample.hxx>
#define Handle_TCollection_ListNode Handle_XIntTools_ListNodeOfListOfSurfaceRangeSample
#define TCollection_ListNode_Type_() XIntTools_ListNodeOfListOfSurfaceRangeSample_Type_()
#define TCollection_List XIntTools_ListOfSurfaceRangeSample
#define TCollection_List_hxx <XIntTools_ListOfSurfaceRangeSample.hxx>

#include <TCollection_List.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_ListNode
#undef TCollection_ListNode_hxx
#undef TCollection_ListIterator
#undef TCollection_ListIterator_hxx
#undef Handle_TCollection_ListNode
#undef TCollection_ListNode_Type_
#undef TCollection_List
#undef TCollection_List_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
