// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XIntTools_StdMapNodeOfMapOfSurfaceSample_HeaderFile
#define _XIntTools_StdMapNodeOfMapOfSurfaceSample_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_XIntTools_StdMapNodeOfMapOfSurfaceSample_HeaderFile
#include <Handle_XIntTools_StdMapNodeOfMapOfSurfaceSample.hxx>
#endif

#ifndef _XIntTools_SurfaceRangeSample_HeaderFile
#include <XIntTools_SurfaceRangeSample.hxx>
#endif
#ifndef _TCollection_MapNode_HeaderFile
#include <TCollection_MapNode.hxx>
#endif
#ifndef _TCollection_MapNodePtr_HeaderFile
#include <TCollection_MapNodePtr.hxx>
#endif
class XIntTools_SurfaceRangeSample;
class XIntTools_SurfaceRangeSampleMapHasher;
class XIntTools_MapOfSurfaceSample;
class XIntTools_MapIteratorOfMapOfSurfaceSample;



class XIntTools_StdMapNodeOfMapOfSurfaceSample : public TCollection_MapNode {

public:

  
      XIntTools_StdMapNodeOfMapOfSurfaceSample(const XIntTools_SurfaceRangeSample& K,const TCollection_MapNodePtr& n);
  
        XIntTools_SurfaceRangeSample& Key() const;




  DEFINE_STANDARD_RTTI(XIntTools_StdMapNodeOfMapOfSurfaceSample)

protected:




private: 


XIntTools_SurfaceRangeSample myKey;


};

#define TheKey XIntTools_SurfaceRangeSample
#define TheKey_hxx <XIntTools_SurfaceRangeSample.hxx>
#define Hasher XIntTools_SurfaceRangeSampleMapHasher
#define Hasher_hxx <XIntTools_SurfaceRangeSampleMapHasher.hxx>
#define TCollection_StdMapNode XIntTools_StdMapNodeOfMapOfSurfaceSample
#define TCollection_StdMapNode_hxx <XIntTools_StdMapNodeOfMapOfSurfaceSample.hxx>
#define TCollection_MapIterator XIntTools_MapIteratorOfMapOfSurfaceSample
#define TCollection_MapIterator_hxx <XIntTools_MapIteratorOfMapOfSurfaceSample.hxx>
#define Handle_TCollection_StdMapNode Handle_XIntTools_StdMapNodeOfMapOfSurfaceSample
#define TCollection_StdMapNode_Type_() XIntTools_StdMapNodeOfMapOfSurfaceSample_Type_()
#define TCollection_Map XIntTools_MapOfSurfaceSample
#define TCollection_Map_hxx <XIntTools_MapOfSurfaceSample.hxx>

#include <TCollection_StdMapNode.lxx>

#undef TheKey
#undef TheKey_hxx
#undef Hasher
#undef Hasher_hxx
#undef TCollection_StdMapNode
#undef TCollection_StdMapNode_hxx
#undef TCollection_MapIterator
#undef TCollection_MapIterator_hxx
#undef Handle_TCollection_StdMapNode
#undef TCollection_StdMapNode_Type_
#undef TCollection_Map
#undef TCollection_Map_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
