// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _XIntTools_PntOn2Faces_HeaderFile
#define _XIntTools_PntOn2Faces_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
#ifndef _XIntTools_PntOnFace_HeaderFile
#include <XIntTools_PntOnFace.hxx>
#endif
class XIntTools_PntOnFace;


//! Contains two points PntOnFace from XIntTools and a flag <br>
class XIntTools_PntOn2Faces  {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
//! Empty constructor <br>
  Standard_EXPORT   XIntTools_PntOn2Faces();
  
//! Initializes me by two points aP1 and aP2 <br>
  Standard_EXPORT   XIntTools_PntOn2Faces(const XIntTools_PntOnFace& aP1,const XIntTools_PntOnFace& aP2);
  
//! Modifier <br>
  Standard_EXPORT     void SetP1(const XIntTools_PntOnFace& aP1) ;
  
//! Modifier <br>
  Standard_EXPORT     void SetP2(const XIntTools_PntOnFace& aP2) ;
  
//! Modifier <br>
  Standard_EXPORT     void SetValid(const Standard_Boolean bF) ;
  
//! Selector <br>
  Standard_EXPORT    const XIntTools_PntOnFace& P1() const;
  
//! Selector <br>
  Standard_EXPORT    const XIntTools_PntOnFace& P2() const;
  
//! Selector <br>
  Standard_EXPORT     Standard_Boolean IsValid() const;





protected:





private:



Standard_Boolean myIsValid;
XIntTools_PntOnFace myPnt1;
XIntTools_PntOnFace myPnt2;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
