%rename(Handle_AppBlend_SequenceNodeOfSequenceOfArray1OfPnt2d) Handle_AppBlend_SequenceNodeOfSequenceOfArray1OfPnt2d;
%rename(AppBlend_SequenceNodeOfSequenceOfArray1OfPnt2d) AppBlend_SequenceNodeOfSequenceOfArray1OfPnt2d;
%rename(AppBlend_Approx) AppBlend_Approx;
%rename(AppBlend_SequenceOfArray1OfPnt2d) AppBlend_SequenceOfArray1OfPnt2d;
