%rename(Geom2dLProp_CLProps2d) Geom2dLProp_CLProps2d;
%rename(Geom2dLProp_NumericCurInf2d) Geom2dLProp_NumericCurInf2d;
%rename(Geom2dLProp_Curve2dTool) Geom2dLProp_Curve2dTool;
%rename(Geom2dLProp_FCurNulOfNumericCurInf2d) Geom2dLProp_FCurNulOfNumericCurInf2d;
%rename(Geom2dLProp_CurAndInf2d) Geom2dLProp_CurAndInf2d;
%rename(Geom2dLProp_FCurExtOfNumericCurInf2d) Geom2dLProp_FCurExtOfNumericCurInf2d;
