%rename(ShapeConstruct_MakeTriangulation) ShapeConstruct_MakeTriangulation;
%rename(ShapeConstruct_ProjectCurveOnSurface) ShapeConstruct_ProjectCurveOnSurface;
%rename(Handle_ShapeConstruct_ProjectCurveOnSurface) Handle_ShapeConstruct_ProjectCurveOnSurface;
%rename(ShapeConstruct_CompBezierCurvesToBSplineCurve) ShapeConstruct_CompBezierCurvesToBSplineCurve;
%rename(ShapeConstruct_Curve) ShapeConstruct_Curve;
%rename(ShapeConstruct) ShapeConstruct;
%rename(ShapeConstruct_CompBezierCurves2dToBSplineCurve2d) ShapeConstruct_CompBezierCurves2dToBSplineCurve2d;
